## 설정

In [1]:
import shutil
import datetime
import pandas as pd
import warnings
import os
import calendar
warnings.filterwarnings('ignore')

from chart_portal import *
from table_portal import *
from Plotly_scatter import *
from docx.text.run import *
from docx.shared import Cm, Inches
# from datetime import datetime, timedelta

In [2]:
# import numpy as np
# pd.set_option('display.max_rows', 1000)

In [3]:
#DRM 방지(default.docx)
def findfile(name, path):
    for dirpath, dirname, filename in os.walk(path):
        if name in filename:
            return os.path.join(dirpath, name)

file_path=os.path.abspath("")
srcpath = findfile("default.docx.org", file_path)
dir, file = os.path.split(srcpath)
shutil.copy2(srcpath, dir+"\default.docx")

'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\docx\\templates\\default.docx'

In [4]:
from document_portal import *
# report version
rtype = '월간' # 연간, 반기

In [5]:
# region_list = [ 'KR', 'CN', 'NA', 'EU', 'SG', 'RU']
region_list = [ 'KR', 'CN', 'NA', 'EU', 'SG', 'RU', 'GLOBAL']
# region = 'All'
# regions = ['KR', 'CN', 'NA', 'EU', 'SG', 'RU', 'GLOBAL']
# regions = ['KR']
# regions = ['EU']
# regions = ['CN']
# regions = ['SG']
regions = ['RU']
# regions = ['NA', 'GLOBAL']

In [6]:
#month = '9월'

In [7]:
# 메타 정보
from dateutil.relativedelta import relativedelta, MO

today = datetime.date.today()
y = today.year
# m = today.month
m = today + relativedelta(months=-1)
d = today.day
w = today.weekday()
m = m.strftime("%m").lstrip("0").replace(" 0"," ")
print(m)
m = int(m)
month = m
print("month:",month)

ym = today.strftime('%Y%m')
print(ym)
ym2 = (today + relativedelta(months=-1)).strftime('%Y%m')
print(ym2)
print(type(ym), type(ym2))

v = '1'

ym = '202405'
ym2 = '202405'
year = '2024'
month = '05'
# year_int = 2024
# month_int = 4

now = datetime.datetime.now()
format_now = now.strftime("%Y%m%d%H%M")
print(format_now)

# _, first_day = calendar.monthrange(int(year), int(month))
# start_date = f"{year}-{month}-{first_day}"

_, last_day = calendar.monthrange(int(year), int(month))
end_date = f"{year}-{month}-{last_day}"

# print(start_date)
print(end_date)

# if region == 'All':
#     # regex = '(KR|KR2|CN|NA|EU|SG|RU|IN|Global|All|"KR Bigdata"|"KR R&D")'
#     regex = '(KR|CN|NA|EU|SG|RU|All)'
# else:
#     regex = region
#     # regex = f'({region}|{region}2)'

5
month: 5
202406
202405
<class 'str'> <class 'str'>
202406111341
2024-05-31

In [8]:
from datetime import datetime, timedelta
from calendar import monthrange

def period(year, month):
    first_day = datetime(year, month, 1)
    last_day = first_day + timedelta(days=calendar.monthrange(year, month)[1])
    return first_day.strftime('%Y-%m-%d'), last_day.strftime('%Y-%m-%d %H:%M:%S')

first_date, last_date = period(int(year), int(month))
print(first_date, last_date)

next_month = int(month) + 1
first_date_next, last_date_next = period(int(year), next_month)
print(first_date_next, last_date_next)

2024-05-01 2024-06-01 00:00:00
2024-06-01 2024-07-01 00:00:00

In [9]:
# Document 기본 폰트
style = document.styles['Normal']
# style.font.name = '맑은고딕'
style.font.name = 'Calibri'
style.font.size = Pt(11)
# style._element.rPr.rFonts.set(qn('w:eastAsia'), '맑은고딕')
style._element.rPr.rFonts.set(qn('w:eastAsia'), 'Calibri')

In [10]:
# Chart 기본 폰트
alt.themes.register('맑은고딕', hanfont)
alt.themes.enable('맑은고딕')

ThemeRegistry.enable('맑은고딕')

## LOGIN

In [11]:
import httpx

async def login(username, password):
    async with httpx.AsyncClient() as client:
        login_data = {"username": username, "password": password}
        login_response = await client.post("http://10.11.66.85:8080/users/login", data=login_data)
        
        if login_response.status_code == 200:
            access_token = login_response.json().get("access_token")
            return access_token
        else:
            return None

async def fetch_data(access_token, data_endpoint, request_header):
    async with httpx.AsyncClient() as client:
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        }
        data_response = await client.post(data_endpoint, headers=headers, json=request_header)
        
        if data_response.status_code == 200:
            fetched_data = data_response.json()
            return fetched_data
        else:
            return None

async def login_and_fetch_data(username, password, data_endpoint):
    access_token = await login(username, password)
    
    if access_token:
        fetched_data = await fetch_data(access_token, data_endpoint)
        return fetched_data
    else:
        return "Login failed"

# Replace 'username_here' and 'password_here' with actual credentials
username = 'test2@test2.com'
password = '2222'

access_token = await login(username, password)

In [12]:
import sys
print(sys.version)

3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

In [13]:
print(access_token)

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0MkB0ZXN0Mi5jb20iLCJleHAiOjE3MTgxNjcyOTJ9._PIGNWea3OhODXcG2_K73Q3u7__eAnSdhAvzo_Lv9I0

In [14]:
# import requests

# data = {
#     "region": "KR",
#     "az": "1",
#     "tenant": "PRD",
#     "customer": "CDO",
#     "progress": "IN_PROGRESS",
#     # "shared_medias": ["Kakao"],
#     # "asset_type": None,
#     # "asset_name": None,
#     # "shift_start_date": None,
#     # "shift_type": None,
#     # "level_1_engineer1": None,
#     # "level_1_engineer2": None,
#     # "level_2_engineers": None,
#     # "event_type": None,
#     "event": "testtest",
#     # "action": "test",
#     # "ticket_no": None,
#     "occurred_at": "2024-01-16T06:17:58.976Z",
#     # "acknowledged_at": None,
#     # "propagated_at": None,
#     # "resolved_at": None,
#     "is_use": True,
#     "is_alarm": True
# }


# def put_event(data):
#     url = 'http://10.11.66.85:8080/events/create'

#     headers = {
#         "Authorization": f"Bearer {access_token}",
#         "Content-Type": "application/json",
#     }
#     # headers = {
#     #     'accept': '*/*',
#     #     'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0MkB0ZXN0Mi5jb20iLCJleHAiOjE3MDUzNzM3NTJ9.0Y5BjoAa-nITuzY1FgKhaTRncsSDIZqIR9RzEtzdFEk',
#     #     'Content-Type': 'application/json',
#     # }
#     response = requests.post(url, headers=headers, json=data)
#     return response
# response = put_event(data)

# # Check the response status
# if response.status_code == 204:  # Assuming HTTP status code 201 for successful creation
#     print("Record created successfully!")
#     # print("Response:", response.json())  # Print the response data if available
# else:
#     print("Failed to create record. Status code:", response.status_code)
#     print("Error message:", response.text)  # Print the error message if available

In [15]:
# # async def get_lastevent():
# data_endpoint = 'http://10.11.66.85:8080/events/list'
# # Request header
# request_header = {
#     "skip": 0,
#     "limit": 10000,
#     "from_YYYYMMDDHH24MI": "202401010000",
#     "to_YYYYMMDDHH24MI": "202401310000",
#     "region": [],
#     "az": [],
#     "tenant": [],
#     "customer": [],
#     "progress": [],
#     "is_draft": False,
#     "is_use": True
# }
# # Call the function
    
# result = await fetch_data(access_token, data_endpoint, request_header)
# # list(result.items())[-1][-1][-1]
# list(result.items())[-1][-1][-1]

In [16]:
# df = pd.DataFrame(result.__dict__)

## (신규포탈)논의점(완료)

In [17]:
data_endpoint = 'http://10.11.66.85:8080/discussions/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [18]:
df = pd.DataFrame(result['data'])

In [19]:
print(df)

      id  year month day  region az tenant customer     progress  \
0    557  2024    04  03      KR  2    PRD      CCS    Completed
1     66  2024    03  27  GLOBAL  1    PRD      CCS  In-progress
2    267  2024    01  31      KR  1    PRD      CCS  In-progress
3    459  2024    02  14      KR  1    PRD      CCS  In-progress
4    198  2024    03  27      KR  2    STG      CCS    Completed
..   ...   ...   ...  ..     ... ..    ...      ...          ...
564  542  2022    08  01      EU  1    PRD      CCS    Completed
565  196  2023    09  01      NA  2    PRD      CCS    Completed
566  497  2023    06  01      KR  2    PRD      CCS    Completed
567  458  2023    08  01      NA  2    PRD      CCS    Completed
568  156  2022    11  01      KR  1    STG      CCS    Completed

                                                 title  \
0    (완료) K8S 상암2센터 운영계 Cluster VM 패키지 설치 (24.04.12...
1                              (진행중) Redis 버전 업그레이드 현황
2                                     의왕 신운영계 스토리지 사용량
3                    의왕 구운영계 A10 임대장비 반납을 위한 서비스 이관 요청
4    (완료) K8S 상암2센터 검증계 Cluster Kernel 패치 (24.03.06...
..                                                 ...
564                                               None
565                                               None
566                                               None
567                                               None
568                                               None

                                      discussion_topic         completed_at  \
0    <h1><span style="font-size:24px"><strong>(완료)&...  2024-06-10 18:51:37
1    <h2><strong>(진행중)&nbsp;<a href="https://conflu...                 None
2    <h1><span style="font-size:24px"><strong>(진행중)...                 None
3    <h1><span style="font-size:24px"><strong>(진행중)...                 None
4    <h1><span style="font-size:24px"><strong>(완료)<...  2024-05-22 10:02:17
..                                                 ...                  ...
564  EUTMS-L7(A10) 유지보수 계약 부재에 따른 이슈EU법인에서 직접 구매로 국...                 None
565  ●NA2 긴급 장애 대응 불가 6/27~ (운영자용 DBsafer 정책 논의 필요)...                 None
566  ●KR 상암 2센터 특정 랙 CPU, Memory Allocation 80% 초과 ...                 None
567  ●NA2 긴급 장애 대응 불가 6/27~ (운영자용 DBsafer 정책 논의 필요)...                 None
568  I-SAMS 보안점검 (완료) NW - 120건 중 118건, 2건 회수대상 장비로...                 None

     is_draft  is_use   flag updater       created_at_str       updated_at_str
0       False    True   True     최원석  2024-04-03 11:13:00  2024-06-10 18:59:34
1       False    True   True     송윤진  2024-03-27 13:49:00  2024-06-05 13:32:49
2       False    True  False     정동영  2024-02-05 15:42:00  2024-06-05 08:14:39
3       False    True  False     오창민  2024-02-14 11:27:00  2024-05-29 12:38:21
4       False    True   True     최원석  2024-03-27 12:33:00  2024-05-22 10:53:02
..        ...     ...    ...     ...                  ...                  ...
564     False    True  False   test2  2024-01-04 17:52:00  2024-01-04 17:52:00
565     False    True  False   test2  2024-01-04 17:52:00  2024-01-04 17:52:00
566     False    True  False   test2  2024-01-04 17:52:00  2024-01-04 17:52:00
567     False    True  False   test2  2024-01-04 17:52:00  2024-01-04 17:52:00
568     False    True  False   test2  2024-01-04 17:52:00  2024-01-04 17:52:00

[569 rows x 18 columns]

In [20]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [21]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'title', 'discussion_topic', 'completed_at', 'is_draft',
       'is_use', 'flag', 'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [22]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'progress', 'title', 'discussion_topic', 'completed_at', 'created_at_str']]

In [23]:
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', '작업내용',  'completed_at', 'created_at']

In [24]:
df.head()

,년,월,리전,AZ,테넌트,진행상태,제목,작업내용,completed_at,created_at
0,2024,04,KR,2,PRD,Completed,(완료) K8S 상암2센터 운영계 Cluster VM 패키지 설치 (24.04.12...,"<h1><span style=""font-size:24px""><strong>(완료)&...",2024-06-10 18:51:37,2024-04-03 11:13:00
1,2024,03,GLOBAL,1,PRD,In-progress,(진행중) Redis 버전 업그레이드 현황,"<h2><strong>(진행중)&nbsp;<a href=""https://conflu...",None,2024-03-27 13:49:00
2,2024,01,KR,1,PRD,In-progress,의왕 신운영계 스토리지 사용량,"<h1><span style=""font-size:24px""><strong>(진행중)...",None,2024-02-05 15:42:00
3,2024,02,KR,1,PRD,In-progress,의왕 구운영계 A10 임대장비 반납을 위한 서비스 이관 요청,"<h1><span style=""font-size:24px""><strong>(진행중)...",None,2024-02-14 11:27:00
4,2024,03,KR,2,STG,Completed,(완료) K8S 상암2센터 검증계 Cluster Kernel 패치 (24.03.06...,"<h1><span style=""font-size:24px""><strong>(완료)<...",2024-05-22 10:02:17,2024-03-27 12:33:00

In [25]:
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
# df_filtered_current = df[df['Region'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월']==month) & (df['년']==y) ]

In [26]:
df_filtered_current

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 작업내용, completed_at, created_at]
Index: []

In [27]:
# df_completed = df[ df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
# df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) &  df['completed_at'].between('2024-04-01', '2024-04-30')]
df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & (df_filtered['completed_at'] >= first_date) & (df_filtered['completed_at']<= last_date)]

completed_rows = len(df_completed)
completed = len(df_completed)
print(completed_rows)

0

In [28]:
# df_incompleted = df[ df['테넌트'].isin(['STG']) & df['년'].isin([year]) & df['월'].isin([month]) ]
df_incompleted = df_filtered[ (df_filtered['진행상태'].isin(['In-progress'])) & (df_filtered['created_at']<= last_date)]
# print(incompleted)
incompleted_rows = len(df_incompleted)
incompleted = len(df_incompleted)
print(incompleted_rows)

merge_for_current = pd.concat([df_completed, df_incompleted])
print(merge_for_current)

2
       년   월  리전 AZ  테넌트         진행상태                                  제목  \
11  2024  01  RU  1  PRD  In-progress             러시아 CCS 운영계 Rescue노드 필요
13  2024  01  RU  1  PRD  In-progress  데이터센터 On-site Support (현장지원서비스) 부재

                                                 작업내용 completed_at  \
11  <p><strong><span style="font-size:24px">러시아 CC...         None
13  <p><strong><span style="font-size:24px">데이터센터 ...         None

             created_at
11  2024-02-05 15:42:00
13  2024-02-05 15:42:00

In [29]:
# # 리전 & 운영계, 월간보고서용
# df_filtered = df[df['Region'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월']==month) ]
# df_filtered_current = df[df['Region'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월']==month) & (df['년']==y) ]

# df_completed = df_filtered[(df_filtered['년']==y) & (df_filtered['월']==month) & (df_filtered['진행상태']=='완료') ]
# completed_rows = len(df_completed)
# completed = counter(df_completed, regex)

# df_incompleted = df_filtered[(df_filtered['년']==y) & (df_filtered['월']==month) & (df_filtered['진행상태']!='완료') ]
# incompleted_rows = len(df_incompleted)
# incompleted = counter(df_incompleted, regex)

In [30]:
print(len(regions))

1

In [31]:
# Chart
if len(regions) > 1: # == 'All':
    # Data
    rowsc = df_completed
    rowsi = df_incompleted
    
    # Chart
    document.add_heading('주요 이벤트', level=1)
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, region_list)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, region_list)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/summaryc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/summaryi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2 )
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text('{0:^45}완료'.format(''))
        run.add_picture(f'./charts/summaryc_{y}_{m}_{d}_{v}_1.png' , width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text('{0:^45}진행'.format(''))
        run.add_picture(f'./charts/summaryi_{y}_{m}_{d}_{v}_1.png' , width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, region_list)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/summaryi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/summaryi_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, region_list)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/summaryc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/summaryc_{y}_{m}_{d}_{v}_1.png')
else:
    document.add_heading('주요 이벤트', level=1)
    t = completed + incompleted
    if t == completed :
        if t == 0 : 
            document.add_paragraph(f'총 {t} 건', style='List Bullet')
        else:
            document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
    else :
        document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 진행: {incompleted} 건)', style='List Bullet')
    pass

In [32]:
df_filtered.columns

Index(['년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', '작업내용', 'completed_at',
       'created_at'],
      dtype='object')

In [33]:
df_filtered_selectedColumns=df_filtered[['월', '리전', '진행상태', '작업내용']]
df_filtered_selectedColumns.sort_values(by=['리전'], ascending=False, inplace=True)
df_filtered_selectedColumns.reset_index(drop=True, inplace=True)
df_filtered=df_filtered_selectedColumns

In [34]:
df_filtered

     월  리전         진행상태                                               작업내용
0   01  RU  In-progress  <p><strong><span style="font-size:24px">러시아 CC...
1   09  RU    Completed  ●데이터센터 On-site Support (현장지원서비스) 부재 이슈 (==> 장애...
2   02  RU    Completed  ●보안툴 도입 전 기술 검토 요청 (K8S) => 요청사항: 보안 툴 도입 전 3선...
3   07  RU    Completed  RUCloudPrdComdR101 메모리 에러이슈 : RUCloudPrdComdR1...
4   11  RU    Completed  ● 러시아 CCS 운영계 Rescue노드 필요 RU CCS 운영계 Rescue 노드...
..  ..  ..          ...                                                ...
92  09  RU    Completed  ● 러시아 CCS 운영계 Rescue노드 필요 RU CCS 운영계 Rescue 노드...
93  12  RU    Completed  ● 러시아 CCS 운영계 Rescue노드 필요 RU CCS 운영계 Rescue 노드...
94  09  RU    Completed  ●정기점검 진행을 위한 프로세스 확인대상: A10, Netapp, Dell, Pal...
95  07  RU    Completed  ●러시아 CPU 사용률 기준(80%) 초과로 VM생성 중단- 러시아↔ 미국 부문별 ...
96  07  RU    Completed  MongoDB 업무 이관업무 인수인계 체크리스트 (완료) 몽고디비 인수인계 회의 (...

[97 rows x 4 columns]

In [35]:
print(merge_for_current)
# print(os.environ['PATH'])

if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addSummaryTable_all(merge_for_current)
    else:
        addSummaryTable(merge_for_current)
                        
#addSummaryTable(df_filtered, regex, month)
document.add_page_break()

       년   월  리전 AZ  테넌트         진행상태                                  제목  \
11  2024  01  RU  1  PRD  In-progress             러시아 CCS 운영계 Rescue노드 필요
13  2024  01  RU  1  PRD  In-progress  데이터센터 On-site Support (현장지원서비스) 부재

                                                 작업내용 completed_at  \
11  <p><strong><span style="font-size:24px">러시아 CC...         None
13  <p><strong><span style="font-size:24px">데이터센터 ...         None

             created_at
11  2024-02-05 15:42:00
13  2024-02-05 15:42:00

In [36]:
document.save('demo.docx')

## (신규포탈)인시던트핸들링(완료)

In [37]:
data_endpoint = 'http://10.11.66.85:8080/events/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": "202406041056",
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "shared_medias": [],
    "asset_type": [],
    "event_type": [],
    "report_type": 0,
    # "is_use": True,
    # "is_alarm": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [38]:
df = pd.DataFrame(result['completed'])

In [39]:
df

,id,year,month,day,region,az,tenant,customer,progress,shared_medias,...,ticket_no,occurred_at,acknowledged_at,propagated_at,resolved_at,is_use,is_alarm,updater,created_at_str,updated_at_str
0,1,2023,04,01,SG,1,PRD,CCS,Completed,Kakao & mail,...,None,2023-04-01 00:50:00,2023-04-01 00:50:00,2023-04-01 00:50:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
1,2,2023,04,01,NA,1,PRD,CCS,Completed,Kakao & Mail,...,NACLOUD-2352,2023-04-01 03:47:00,2023-04-01 03:47:00,2023-04-01 03:47:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
2,3,2023,04,01,NA,1,PRD,CCS,Completed,Kakao & Mail,...,None,2023-04-01 16:04:00,2023-04-01 16:05:00,2023-04-01 16:05:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
3,4,2023,04,01,SG,1,PRD,CCS,Completed,"kakao, Jira Ticket &Mail",...,SGCLOUD- 2314,2023-04-01 21:30:00,2023-04-01 21:30:00,2023-04-01 21:30:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
4,5,2023,04,01,EU,1,PRD,CCS,Completed,Kakao,...,None,2023-04-01 23:20:00,2023-04-01 23:20:00,2023-04-01 23:20:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6316,6318,2024,05,01,KR,1,PRD,CCS,Completed,kakao & Mail,...,None,2024-06-01 00:04:00,2024-06-01 00:04:00,2024-06-01 00:04:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
6317,6319,2024,05,01,KR,1,PRD,CCS,Completed,kakao & Mail,...,None,2024-06-01 00:01:00,2024-06-01 00:01:00,2024-06-01 00:01:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
6318,6320,2024,05,01,NA,1,PRD,CCS,Completed,kakao & Mail,...,None,2024-06-01 07:34:00,2024-06-01 07:34:00,2024-06-01 07:34:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
6319,6321,2024,05,01,NA,1,PRD,CCS,Completed,kakao & Mail,...,None,2024-06-01 03:56:00,2024-06-01 03:56:00,2024-06-01 03:56:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21
6320,5879,2024,05,01,NA,2,PRD,CCS,Completed,kakao & ticket,...,NACLOUD-4157,2024-05-03 05:00:00,2024-05-03 05:01:00,2024-05-03 05:01:00,None,True,True,문광훈,2024-06-04 10:55:21,2024-06-04 10:55:21

In [40]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'shared_medias', 'asset_type', 'asset_name',
       'shift_start_date', 'shift_type', 'level_1_engineer1',
       'level_1_engineer2', 'level_2_engineers', 'event_type', 'event',
       'action', 'ticket_no', 'occurred_at', 'acknowledged_at',
       'propagated_at', 'resolved_at', 'is_use', 'is_alarm', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [41]:
df = df[['year', 'month', 'region', 'az', 'tenant', 
         'shift_start_date','level_1_engineer1', 'level_1_engineer2',
         'level_2_engineers', 'event_type', 'event',
         'action', 'progress', 'ticket_no', 'occurred_at', 'acknowledged_at',
         'propagated_at', 'resolved_at', 'is_use', 'is_alarm',
         'created_at_str', 'updated_at_str']]

In [42]:
# df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', '대상', '작업내용', '시작일', '완료일']
df.columns = ['년', '월', '리전', 'AZ', '테넌트',
              '날짜', 'level_1_engineer1', 'level_1_engineer2',
              'level_2_engineers', '이벤트유형', '장애이벤트',
              '조치내용', '진행상태', 'JIRA_Ticket_No', '장애발생시간', '발생인지시간',
              '장애전파시간', 'resolved_at', 'is_use', 'is_alarm',
              'created_at', 'updated_at']

In [43]:
# 리전 & 운영계, 월간보고서용
# months = "04"

df['리전'] = df['리전'].str.upper()
df['테넌트'] = df['테넌트'].str.upper()

df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
# df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['updated_at'].between('2024-02-01', '2024-02-29') ]

In [44]:
df_filtered_current

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 날짜, level_1_engineer1, level_1_engineer2, level_2_engineers, 이벤트유형, 장애이벤트, 조치내용, 진행상태, JIRA_Ticket_No, 장애발생시간, 발생인지시간, 장애전파시간, resolved_at, is_use, is_alarm, created_at, updated_at]
Index: []

[0 rows x 22 columns]

In [45]:
df_filtered

,년,월,리전,AZ,테넌트,날짜,level_1_engineer1,level_1_engineer2,level_2_engineers,이벤트유형,...,진행상태,JIRA_Ticket_No,장애발생시간,발생인지시간,장애전파시간,resolved_at,is_use,is_alarm,created_at,updated_at
125,2023,04,RU,1,PRD,1681084800000,강신우,이한새,None,None,...,Completed,None,2023-04-11 15:02:00,2023-04-11 15:02:00,2023-04-11 15:02:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1496,2023,06,RU,1,PRD,1687737600000,Subramanya,Ashok,None,None,...,Completed,RUCLOUD-984,2023-06-27 07:02:00,2023-06-27 07:02:00,2023-06-27 07:02:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1628,2023,07,RU,1,PRD,1688515200000,Mohamed,Aslam & Ram,None,None,...,Completed,RUCLOUD-994,2023-07-06 04:45:00,2023-07-06 04:45:00,2023-07-06 04:45:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1689,2023,07,RU,1,PRD,1688947200000,정진호,문광훈,None,None,...,Completed,RUCLOUD-997,2023-07-10 18:30:00,2023-07-10 18:35:00,2023-07-10 18:35:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1690,2023,07,RU,1,PRD,1688947200000,정진호,문광훈,None,None,...,Completed,RUCLOUD-997,2023-07-10 18:30:00,2023-07-10 18:35:00,2023-07-10 18:35:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1715,2023,07,RU,1,PRD,1689033600000,Manikandan / Radhika,Anand,None,None,...,Completed,RUCLOUD-997,2023-07-11 23:07:00,2023-07-11 23:07:00,2023-07-11 23:07:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1735,2023,07,RU,1,PRD,1689120000000,정진호,문광훈,None,None,...,Completed,RUCLOUD-1006,2023-07-12 21:09:00,2023-07-12 21:10:00,2023-07-12 21:10:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1743,2023,07,RU,1,PRD,1689206400000,김의현,김범준,None,None,...,Completed,None,2023-07-14 16:52:00,2023-07-14 16:53:00,2023-07-14 16:54:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1872,2023,07,RU,1,PRD,1690070400000,Radhika,Aslam and Saju,None,None,...,Completed,None,2023-07-24 01:52:00,2023-07-24 01:53:00,2023-07-24 01:53:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
1873,2023,07,RU,1,PRD,1690070400000,Radhika,Aslam and Saju,None,None,...,Completed,None,2023-07-24 03:21:00,2023-07-24 03:23:00,2023-07-24 03:23:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2024,2023,08,RU,1,PRD,1691107200000,김범준,김의현,None,None,...,Completed,None,2023-08-04 15:08:00,2023-08-04 15:10:00,2023-08-04 15:13:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2050,2023,08,RU,1,PRD,1691366400000,김의현,오창민,None,None,...,Completed,None,2023-08-07 19:07:00,2023-08-07 19:10:00,2023-08-07 19:16:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2060,2023,08,RU,1,PRD,1691452800000,김의현,오창민,None,None,...,Completed,None,2023-08-08 19:47:00,2023-08-08 19:48:00,2023-08-08 19:49:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2062,2023,08,RU,1,PRD,1691452800000,김의현,오창민,None,None,...,Completed,None,2023-08-08 20:37:00,2023-08-08 20:37:00,2023-08-08 20:38:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2161,2023,08,RU,1,PRD,1691971200000,Manikandan / Radhika,Anand,None,None,...,Completed,RUCLOUD-1036,2023-08-15 03:44:00,2023-08-15 03:44:00,2023-08-15 03:44:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2182,2023,08,RU,1,PRD,1692144000000,강신우,이시형,None,None,...,Completed,None,2023-08-16 08:57:00,2023-08-16 08:59:00,2023-08-16 08:59:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2255,2023,08,RU,1,PRD,1692576000000,Manikandan / Radhika,Ram & Ananda,None,None,...,Completed,None,2023-08-21 23:43:00,2023-08-21 23:43:00,2023-08-21 23:43:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2352,2023,08,RU,1,PRD,1692921600000,Manikandan,"Saju, Anand",None,None,...,Completed,None,2023-08-27 12:35:00,2023-08-27 12:35:00,2023-08-27 12:35:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2781,2023,09,RU,1,PRD,1694908800000,Srinivas S,Dhadapani & Ram,None,None,...,Completed,None,2023-09-16 13:09:00,2023-09-16 13:10:00,2023-09-16 13:10:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2870,2023,09,RU,1,PRD,1695340800000,김범준,임정현,None,None,...,Completed,RUCLOUD-1070,2023-09-22 12:16:00,2023-09-22 12:18:00,2023-09-22 12:18:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
2995,2023,09,RU,1,PRD,1695859200000,정진호,김범준,None,None,...,Completed,RUCLOUD-1075,2023-09-29 13:11:00,2023-09-29 13:21:00,2023-09-29 13:21:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3245,2023,10,RU,1,PRD,1697760000000,박기완,장재봉,None,None,...,Completed,None,2023-10-20 12:19:00,2023-10-20 12:19:00,2023-10-20 12:19:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3251,2023,10,RU,1,PRD,1697760000000,Radhika,Saju maideen & Aslam,None,None,...,Completed,None,2023-10-20 22:19:00,2023-10-21 22:18:59,2023-10-21 22:18:59,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3301,2023,10,RU,1,PRD,1698192000000,Manikandan,Ashok & Aslam,None,None,...,Completed,None,2023-10-26 00:20:00,2023-10-26 00:20:00,2023-10-26 00:20:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3324,2023,10,RU,1,PRD,1698364800000,홍성현,김의현,None,None,...,Completed,None,2023-10-27 10:00:00,2023-10-27 10:00:00,2023-10-27 10:00:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3419,2023,11,RU,1,PRD,1698883200000,정진호,소유진,None,None,...,Completed,None,2023-11-02 17:11:00,2023-11-02 17:14:00,2023-11-02 17:14:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3422,2023,11,RU,1,PRD,1698883200000,정진호,소유진,None,None,...,Completed,None,2023-11-02 19:12:00,2023-11-02 19:14:00,2023-11-02 19:14:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3504,2023,11,RU,1,PRD,1699401600000,Srinivas S,None,None,None,...,Completed,None,2023-11-08 12:16:00,2023-11-08 12:16:00,2023-11-08 12:16:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3581,2023,11,RU,1,PRD,1699574400000,박기완,고희경,None,None,...,Completed,None,2023-11-13 12:48:00,2023-11-13 12:48:00,2023-11-13 12:48:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3754,2023,11,RU,1,PRD,1700438400000,이시형,"채한길,박정민",None,None,...,Completed,None,2023-11-20 18:35:00,2023-11-20 18:35:00,2023-11-20 18:35:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3779,2023,11,RU,1,PRD,1700611200000,박기완,장재봉,None,None,...,Completed,None,2023-11-22 12:19:00,2023-11-22 12:19:00,2023-11-22 12:19:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
3941,2023,12,RU,1,PRD,1701561600000,"Manikandan, Radhika",Ram,None,None,...,Completed,None,2023-12-04 02:55:00,2023-12-04 02:55:00,2023-12-04 02:55:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4096,2024,02,RU,1,PRD,1706832000000,Subramanyaa & Ashok,Aslam,None,None,...,Completed,None,2024-02-03 01:07:00,2024-02-03 01:07:00,2024-02-03 01:07:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4167,2024,02,RU,1,PRD,1706832000000,Subramanyaa & Ashok,Aslam,None,None,...,Completed,None,2024-02-03 02:07:00,2024-02-03 02:07:00,2024-02-03 02:07:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4197,2023,12,RU,1,PRD,1703116800000,오창민,문광훈,None,None,...,Completed,RUCLOUD-1157,2023-12-21 18:22:00,2023-12-21 18:22:00,2023-12-21 18:22:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4235,2023,12,RU,1,PRD,1703289600000,Manikandan,Aslam,None,None,...,Completed,RUCLOUD-1160,2023-12-24 02:30:00,2023-12-24 02:30:00,2023-12-24 02:30:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4352,2024,01,RU,1,PRD,1704326400000,홍성현,문광훈,None,None,...,Completed,None,2024-01-04 14:27:00,2024-01-04 14:27:00,2024-01-04 14:27:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4420,2024,01,RU,1,PRD,1704931200000,Manikandan,Saju,None,None,...,Completed,RUCLOUD-1176,2024-01-12 01:15:00,2024-01-12 01:15:00,2024-01-12 01:15:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4472,2024,01,RU,1,PRD,1705363200000,"Ananda, Ashok,Radhika","Saju,Aslam",None,None,...,Completed,None,2024-01-17 13:51:00,2024-01-17 13:51:00,2024-01-17 13:51:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4688,2024,02,RU,1,PRD,1707177600000,Subramanyaa & Ashok,Dhandapani & Ram,None,None,...,Completed,None,2024-02-06 22:32:00,2024-02-06 22:32:00,2024-02-06 22:32:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4784,2024,02,RU,1,PRD,1707955200000,고희경,박정민,None,None,...,Completed,RUCLOUD-1212,2024-02-15 14:41:00,2024-02-15 14:46:00,2024-02-15 14:46:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
4964,2024,02,RU,1,PRD,1709078400000,김의현,박기완,None,None,...,Completed,None,2024-02-28 20:26:00,2024-02-28 20:26:00,2024-02-28 20:27:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5147,2024,03,RU,1,PRD,1710460800000,Subramanyaa & Ashok,"Saju, Ram",None,None,...,Completed,None,2024-03-16 05:20:00,2024-03-16 05:20:00,2024-03-16 05:20:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5379,2024,04,RU,1,PRD,1712102400000,김의현,"소유진, 용진수",None,None,...,Completed,None,2024-04-03 17:40:00,2024-04-03 17:41:00,2024-04-03 17:42:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5380,2024,04,RU,1,PRD,1712102400000,김의현,"소유진, 용진수",None,None,...,Completed,None,2024-04-03 17:50:00,2024-04-03 17:50:00,2024-04-03 17:51:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5429,2024,04,RU,1,PRD,1712361600000,"Manikandan, Ananda","Saju,Dhandapani",None,None,...,Completed,None,2024-04-07 00:16:00,2024-04-07 00:16:00,2024-04-07 00:16:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5448,2024,04,RU,1,PRD,1712534400000,"Manikandan, Ananda","Dhandapani,Saju",None,None,...,Completed,None,2024-04-09 04:22:00,2024-04-09 04:22:00,2024-04-09 04:22:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5514,2024,04,RU,1,PRD,1712880000000,Ashok,Dhandapani.Ram,None,None,...,Completed,None,2024-04-13 03:05:00,2024-04-13 03:05:00,2024-04-13 03:05:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21
5705,2024,04,RU,1,PRD,1713916800000,정진호,박기완,None,None,...,Completed,None,2024-04-24 14:16:00,2024-04-24 14:16:00,2024-04-24 14:16:00,None,True,True,2024-06-04 10:55:21,2024-06-04 10:55:21

In [46]:
# df['장애전파소요시간'] = (pd.to_datetime(df['장애전파시간'])-pd.to_datetime(df['장애발생시간'])).astype('timedelta64[m]')
df_filtered_current['발생인지시간'].replace('1900-01-01T00:00:00', '', inplace=True)
df_filtered_current['장애전파시간'].replace('1900-01-01T00:00:00', '', inplace=True)

print(df['발생인지시간'])

0       2023-04-01 00:50:00
1       2023-04-01 03:47:00
2       2023-04-01 16:05:00
3       2023-04-01 21:30:00
4       2023-04-01 23:20:00
               ...
6316    2024-06-01 00:04:00
6317    2024-06-01 00:01:00
6318    2024-06-01 07:34:00
6319    2024-06-01 03:56:00
6320    2024-05-03 05:01:00
Name: 발생인지시간, Length: 6321, dtype: object

In [47]:
df_filtered_current['장애인지소요시간'] = (pd.to_datetime(df_filtered_current['발생인지시간'])-pd.to_datetime(df_filtered_current['장애발생시간'])).astype('timedelta64[m]')
df_filtered_current['장애전파소요시간'] = (pd.to_datetime(df_filtered_current['장애전파시간'])-pd.to_datetime(df_filtered_current['발생인지시간'])).astype('timedelta64[m]')

print("before", df_filtered)
# #장애인지
df_filtered, timeslot = getTables(df_filtered, regions, year, month)
print("timeslot",timeslot)
print(type(timeslot))

# #장애전파
df_filtered, timeslot2 = getTables2(df_filtered, regions, year, month)
    
# SLA failed
df_failed = df_filtered_current[(df_filtered_current['장애인지소요시간'] > 15)]
df_failed[['날짜', '장애이벤트', '조치내용', 'JIRA_Ticket_No', '장애인지소요시간']]
print(df_failed)

# SLA failed 장애 인지
df_failed2 = df_filtered_current[(df_filtered_current['장애전파소요시간'] > 15)]
df_failed2[['날짜', '장애이벤트', '조치내용', 'JIRA_Ticket_No', '장애전파소요시간']]

df_completed = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) & df['진행상태'].isin(['Completed']) ]
completed = len(df_completed)

df_incompleted = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) & df['진행상태'].isin(['In-progress']) ]
incompleted = len(df_incompleted)

before          년   월  리전 AZ  테넌트             날짜       level_1_engineer1  \
125   2023  04  RU  1  PRD  1681084800000                     강신우
1496  2023  06  RU  1  PRD  1687737600000              Subramanya
1628  2023  07  RU  1  PRD  1688515200000                 Mohamed
1689  2023  07  RU  1  PRD  1688947200000                     정진호
1690  2023  07  RU  1  PRD  1688947200000                     정진호
1715  2023  07  RU  1  PRD  1689033600000    Manikandan / Radhika
1735  2023  07  RU  1  PRD  1689120000000                     정진호
1743  2023  07  RU  1  PRD  1689206400000                     김의현
1872  2023  07  RU  1  PRD  1690070400000                 Radhika
1873  2023  07  RU  1  PRD  1690070400000                 Radhika
2024  2023  08  RU  1  PRD  1691107200000                     김범준
2050  2023  08  RU  1  PRD  1691366400000                     김의현
2060  2023  08  RU  1  PRD  1691452800000                     김의현
2062  2023  08  RU  1  PRD  1691452800000                     김의현
2161  2023  08  RU  1  PRD  1691971200000    Manikandan / Radhika
2182  2023  08  RU  1  PRD  1692144000000                     강신우
2255  2023  08  RU  1  PRD  1692576000000    Manikandan / Radhika
2352  2023  08  RU  1  PRD  1692921600000              Manikandan
2781  2023  09  RU  1  PRD  1694908800000              Srinivas S
2870  2023  09  RU  1  PRD  1695340800000                     김범준
2995  2023  09  RU  1  PRD  1695859200000                     정진호
3245  2023  10  RU  1  PRD  1697760000000                     박기완
3251  2023  10  RU  1  PRD  1697760000000                 Radhika
3301  2023  10  RU  1  PRD  1698192000000              Manikandan
3324  2023  10  RU  1  PRD  1698364800000                     홍성현
3419  2023  11  RU  1  PRD  1698883200000                     정진호
3422  2023  11  RU  1  PRD  1698883200000                     정진호
3504  2023  11  RU  1  PRD  1699401600000              Srinivas S
3581  2023  11  RU  1  PRD  1699574400000                     박기완
3754  2023  11  RU  1  PRD  1700438400000                     이시형
3779  2023  11  RU  1  PRD  1700611200000                     박기완
3941  2023  12  RU  1  PRD  1701561600000     Manikandan, Radhika
4096  2024  02  RU  1  PRD  1706832000000     Subramanyaa & Ashok
4167  2024  02  RU  1  PRD  1706832000000     Subramanyaa & Ashok
4197  2023  12  RU  1  PRD  1703116800000                     오창민
4235  2023  12  RU  1  PRD  1703289600000              Manikandan
4352  2024  01  RU  1  PRD  1704326400000                     홍성현
4420  2024  01  RU  1  PRD  1704931200000              Manikandan
4472  2024  01  RU  1  PRD  1705363200000  Ananda, Ashok,Radhika
4688  2024  02  RU  1  PRD  1707177600000     Subramanyaa & Ashok
4784  2024  02  RU  1  PRD  1707955200000                     고희경
4964  2024  02  RU  1  PRD  1709078400000                     김의현
5147  2024  03  RU  1  PRD  1710460800000     Subramanyaa & Ashok
5379  2024  04  RU  1  PRD  1712102400000                     김의현
5380  2024  04  RU  1  PRD  1712102400000                     김의현
5429  2024  04  RU  1  PRD  1712361600000      Manikandan, Ananda
5448  2024  04  RU  1  PRD  1712534400000      Manikandan, Ananda
5514  2024  04  RU  1  PRD  1712880000000                   Ashok
5705  2024  04  RU  1  PRD  1713916800000                     정진호

         level_1_engineer2 level_2_engineers 이벤트유형  ...       진행상태  \
125                    이한새              None  None  ...  Completed
1496                 Ashok              None  None  ...  Completed
1628           Aslam & Ram              None  None  ...  Completed
1689                   문광훈              None  None  ...  Completed
1690                   문광훈              None  None  ...  Completed
1715                 Anand              None  None  ...  Completed
1735                   문광훈              None  None  ...  Completed
1743                   김범준              None  None  ...  Completed
1872        Aslam and Saju              None  None  ...  Completed
1873        Aslam and Saju              None  None  ...  Completed
2024                   김의현              None  None  ...  Completed
2050                   오창민              None  None  ...  Completed
2060                   오창민              None  None  ...  Completed
2062                   오창민              None  None  ...  Completed
2161                 Anand              None  None  ...  Completed
2182                   이시형              None  None  ...  Completed
2255          Ram & Ananda              None  None  ...  Completed
2352           Saju, Anand              None  None  ...  Completed
2781       Dhadapani & Ram              None  None  ...  Completed
2870                   임정현              None  None  ...  Completed
2995                   김범준              None  None  ...  Completed
3245                   장재봉              None  None  ...  Completed
3251  Saju maideen & Aslam              None  None  ...  Completed
3301         Ashok & Aslam              None  None  ...  Completed
3324                   김의현              None  None  ...  Completed
3419                   소유진              None  None  ...  Completed
3422                   소유진              None  None  ...  Completed
3504                  None              None  None  ...  Completed
3581                   고희경              None  None  ...  Completed
3754               채한길,박정민              None  None  ...  Completed
3779                   장재봉              None  None  ...  Completed
3941                   Ram              None  None  ...  Completed
4096                 Aslam              None  None  ...  Completed
4167                 Aslam              None  None  ...  Completed
4197                   문광훈              None  None  ...  Completed
4235                 Aslam              None  None  ...  Completed
4352                   문광훈              None  None  ...  Completed
4420                  Saju              None  None  ...  Completed
4472            Saju,Aslam              None  None  ...  Completed
4688      Dhandapani & Ram              None  None  ...  Completed
4784                   박정민              None  None  ...  Completed
4964                   박기완              None  None  ...  Completed
5147             Saju, Ram              None  None  ...  Completed
5379              소유진, 용진수              None  None  ...  Completed
5380              소유진, 용진수              None  None  ...  Completed
5429       Saju,Dhandapani              None  None  ...  Completed
5448       Dhandapani,Saju              None  None  ...  Completed
5514        Dhandapani.Ram              None  None  ...  Completed
5705                   박기완              None  None  ...  Completed

     JIRA_Ticket_No               장애발생시간               발생인지시간  \
125            None  2023-04-11 15:02:00  2023-04-11 15:02:00
1496    RUCLOUD-984  2023-06-27 07:02:00  2023-06-27 07:02:00
1628    RUCLOUD-994  2023-07-06 04:45:00  2023-07-06 04:45:00
1689    RUCLOUD-997  2023-07-10 18:30:00  2023-07-10 18:35:00
1690    RUCLOUD-997  2023-07-10 18:30:00  2023-07-10 18:35:00
1715    RUCLOUD-997  2023-07-11 23:07:00  2023-07-11 23:07:00
1735   RUCLOUD-1006  2023-07-12 21:09:00  2023-07-12 21:10:00
1743           None  2023-07-14 16:52:00  2023-07-14 16:53:00
1872           None  2023-07-24 01:52:00  2023-07-24 01:53:00
1873           None  2023-07-24 03:21:00  2023-07-24 03:23:00
2024           None  2023-08-04 15:08:00  2023-08-04 15:10:00
2050           None  2023-08-07 19:07:00  2023-08-07 19:10:00
2060           None  2023-08-08 19:47:00  2023-08-08 19:48:00
2062           None  2023-08-08 20:37:00  2023-08-08 20:37:00
2161   RUCLOUD-1036  2023-08-15 03:44:00  2023-08-15 03:44:00
2182           None  2023-08-16 08:57:00  2023-08-16 08:59:00
2255           None  2023-08-21 23:43:00  2023-08-21 23:43:00
2352           None  2023-08-27 12:35:00  2023-08-27 12:35:00
2781           None  2023-09-16 13:09:00  2023-09-16 13:10:00
2870   RUCLOUD-1070  2023-09-22 12:16:00  2023-09-22 12:18:00
2995   RUCLOUD-1075  2023-09-29 13:11:00  2023-09-29 13:21:00
3245           None  2023-10-20 12:19:00  2023-10-20 12:19:00
3251           None  2023-10-20 22:19:00  2023-10-21 22:18:59
3301           None  2023-10-26 00:20:00  2023-10-26 00:20:00
3324           None  2023-10-27 10:00:00  2023-10-27 10:00:00
3419           None  2023-11-02 17:11:00  2023-11-02 17:14:00
3422           None  2023-11-02 19:12:00  2023-11-02 19:14:00
3504           None  2023-11-08 12:16:00  2023-11-08 12:16:00
3581           None  2023-11-13 12:48:00  2023-11-13 12:48:00
3754           None  2023-11-20 18:35:00  2023-11-20 18:35:00
3779           None  2023-11-22 12:19:00  2023-11-22 12:19:00
3941           None  2023-12-04 02:55:00  2023-12-04 02:55:00
4096           None  2024-02-03 01:07:00  2024-02-03 01:07:00
4167           None  2024-02-03 02:07:00  2024-02-03 02:07:00
4197   RUCLOUD-1157  2023-12-21 18:22:00  2023-12-21 18:22:00
4235   RUCLOUD-1160  2023-12-24 02:30:00  2023-12-24 02:30:00
4352           None  2024-01-04 14:27:00  2024-01-04 14:27:00
4420   RUCLOUD-1176  2024-01-12 01:15:00  2024-01-12 01:15:00
4472           None  2024-01-17 13:51:00  2024-01-17 13:51:00
4688           None  2024-02-06 22:32:00  2024-02-06 22:32:00
4784   RUCLOUD-1212  2024-02-15 14:41:00  2024-02-15 14:46:00
4964           None  2024-02-28 20:26:00  2024-02-28 20:26:00
5147           None  2024-03-16 05:20:00  2024-03-16 05:20:00
5379           None  2024-04-03 17:40:00  2024-04-03 17:41:00
5380           None  2024-04-03 17:50:00  2024-04-03 17:50:00
5429           None  2024-04-07 00:16:00  2024-04-07 00:16:00
5448           None  2024-04-09 04:22:00  2024-04-09 04:22:00
5514           None  2024-04-13 03:05:00  2024-04-13 03:05:00
5705           None  2024-04-24 14:16:00  2024-04-24 14:16:00

                   장애전파시간 resolved_at is_use is_alarm           created_at  \
125   2023-04-11 15:02:00        None   True     True  2024-06-04 10:55:21
1496  2023-06-27 07:02:00        None   True     True  2024-06-04 10:55:21
1628  2023-07-06 04:45:00        None   True     True  2024-06-04 10:55:21
1689  2023-07-10 18:35:00        None   True     True  2024-06-04 10:55:21
1690  2023-07-10 18:35:00        None   True     True  2024-06-04 10:55:21
1715  2023-07-11 23:07:00        None   True     True  2024-06-04 10:55:21
1735  2023-07-12 21:10:00        None   True     True  2024-06-04 10:55:21
1743  2023-07-14 16:54:00        None   True     True  2024-06-04 10:55:21
1872  2023-07-24 01:53:00        None   True     True  2024-06-04 10:55:21
1873  2023-07-24 03:23:00        None   True     True  2024-06-04 10:55:21
2024  2023-08-04 15:13:00        None   True     True  2024-06-04 10:55:21
2050  2023-08-07 19:16:00        None   True     True  2024-06-04 10:55:21
2060  2023-08-08 19:49:00        None   True     True  2024-06-04 10:55:21
2062  2023-08-08 20:38:00        None   True     True  2024-06-04 10:55:21
2161  2023-08-15 03:44:00        None   True     True  2024-06-04 10:55:21
2182  2023-08-16 08:59:00        None   True     True  2024-06-04 10:55:21
2255  2023-08-21 23:43:00        None   True     True  2024-06-04 10:55:21
2352  2023-08-27 12:35:00        None   True     True  2024-06-04 10:55:21
2781  2023-09-16 13:10:00        None   True     True  2024-06-04 10:55:21
2870  2023-09-22 12:18:00        None   True     True  2024-06-04 10:55:21
2995  2023-09-29 13:21:00        None   True     True  2024-06-04 10:55:21
3245  2023-10-20 12:19:00        None   True     True  2024-06-04 10:55:21
3251  2023-10-21 22:18:59        None   True     True  2024-06-04 10:55:21
3301  2023-10-26 00:20:00        None   True     True  2024-06-04 10:55:21
3324  2023-10-27 10:00:00        None   True     True  2024-06-04 10:55:21
3419  2023-11-02 17:14:00        None   True     True  2024-06-04 10:55:21
3422  2023-11-02 19:14:00        None   True     True  2024-06-04 10:55:21
3504  2023-11-08 12:16:00        None   True     True  2024-06-04 10:55:21
3581  2023-11-13 12:48:00        None   True     True  2024-06-04 10:55:21
3754  2023-11-20 18:35:00        None   True     True  2024-06-04 10:55:21
3779  2023-11-22 12:19:00        None   True     True  2024-06-04 10:55:21
3941  2023-12-04 02:55:00        None   True     True  2024-06-04 10:55:21
4096  2024-02-03 01:07:00        None   True     True  2024-06-04 10:55:21
4167  2024-02-03 02:07:00        None   True     True  2024-06-04 10:55:21
4197  2023-12-21 18:22:00        None   True     True  2024-06-04 10:55:21
4235  2023-12-24 02:30:00        None   True     True  2024-06-04 10:55:21
4352  2024-01-04 14:27:00        None   True     True  2024-06-04 10:55:21
4420  2024-01-12 01:15:00        None   True     True  2024-06-04 10:55:21
4472  2024-01-17 13:51:00        None   True     True  2024-06-04 10:55:21
4688  2024-02-06 22:32:00        None   True     True  2024-06-04 10:55:21
4784  2024-02-15 14:46:00        None   True     True  2024-06-04 10:55:21
4964  2024-02-28 20:27:00        None   True     True  2024-06-04 10:55:21
5147  2024-03-16 05:20:00        None   True     True  2024-06-04 10:55:21
5379  2024-04-03 17:42:00        None   True     True  2024-06-04 10:55:21
5380  2024-04-03 17:51:00        None   True     True  2024-06-04 10:55:21
5429  2024-04-07 00:16:00        None   True     True  2024-06-04 10:55:21
5448  2024-04-09 04:22:00        None   True     True  2024-06-04 10:55:21
5514  2024-04-13 03:05:00        None   True     True  2024-06-04 10:55:21
5705  2024-04-24 14:16:00        None   True     True  2024-06-04 10:55:21

               updated_at
125   2024-06-04 10:55:21
1496  2024-06-04 10:55:21
1628  2024-06-04 10:55:21
1689  2024-06-04 10:55:21
1690  2024-06-04 10:55:21
1715  2024-06-04 10:55:21
1735  2024-06-04 10:55:21
1743  2024-06-04 10:55:21
1872  2024-06-04 10:55:21
1873  2024-06-04 10:55:21
2024  2024-06-04 10:55:21
2050  2024-06-04 10:55:21
2060  2024-06-04 10:55:21
2062  2024-06-04 10:55:21
2161  2024-06-04 10:55:21
2182  2024-06-04 10:55:21
2255  2024-06-04 10:55:21
2352  2024-06-04 10:55:21
2781  2024-06-04 10:55:21
2870  2024-06-04 10:55:21
2995  2024-06-04 10:55:21
3245  2024-06-04 10:55:21
3251  2024-06-04 10:55:21
3301  2024-06-04 10:55:21
3324  2024-06-04 10:55:21
3419  2024-06-04 10:55:21
3422  2024-06-04 10:55:21
3504  2024-06-04 10:55:21
3581  2024-06-04 10:55:21
3754  2024-06-04 10:55:21
3779  2024-06-04 10:55:21
3941  2024-06-04 10:55:21
4096  2024-06-04 10:55:21
4167  2024-06-04 10:55:21
4197  2024-06-04 10:55:21
4235  2024-06-04 10:55:21
4352  2024-06-04 10:55:21
4420  2024-06-04 10:55:21
4472  2024-06-04 10:55:21
4688  2024-06-04 10:55:21
4784  2024-06-04 10:55:21
4964  2024-06-04 10:55:21
5147  2024-06-04 10:55:21
5379  2024-06-04 10:55:21
5380  2024-06-04 10:55:21
5429  2024-06-04 10:55:21
5448  2024-06-04 10:55:21
5514  2024-06-04 10:55:21
5705  2024-06-04 10:55:21

[49 rows x 22 columns]
timeslot Empty DataFrame
Columns: [일, 장애인지, 리전]
Index: []
<class 'pandas.core.frame.DataFrame'>
Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 날짜, level_1_engineer1, level_1_engineer2, level_2_engineers, 이벤트유형, 장애이벤트, 조치내용, 진행상태, JIRA_Ticket_No, 장애발생시간, 발생인지시간, 장애전파시간, resolved_at, is_use, is_alarm, created_at, updated_at, 장애인지소요시간, 장애전파소요시간]
Index: []

[0 rows x 24 columns]

In [48]:
print(completed, incompleted)

0 0

In [49]:
print(timeslot, timeslot2)

Empty DataFrame
Columns: [일, 장애인지, 리전]
Index: [] Empty DataFrame
Columns: [일, 장애전파, 리전]
Index: []

In [50]:
# Chart - Pie 차트

# if region == 'All':
if len(regions) > 1: # == 'All':
    # Data
    rowsc = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Completed']))]
    rowsi = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['In-progress']))]
    
    # Chart
    document.add_heading('모니터링(인시던트핸들링)', level=1) 
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 미완료: {incompleted})', style='List Bullet')
    
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/monc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/moni_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format())
        run.add_picture(f'./charts/monc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}미완료".format())
        run.add_picture(f'./charts/moni_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/moni_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/moni_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/monc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/monc_{y}_{m}_{d}_{v}_1.png')
else:
    document.add_heading('모니터링(인시던트핸들링)', level=1) 
    t = completed + incompleted
    document.add_paragraph(f'총 {t} 건 ', style='List Bullet')
    pass

# Chart - 스캐터 차트    
# 장애 인지
# chart = getScatterChart(timeslot, month)
filename = f'./charts/mon_{regions}_{y}_{m}_{d}_2.png'
chart = create_scatter_ack(timeslot)
chart_to_image(chart, filename)
resize_image(filename, target_width_cm=16, target_height_cm=10)
# chart_to_image(chart, resize)
# chart_to_image(chart, filename)
# chart.save(f'./charts/mon_{regions}_{y}_{m}_{d}_2.png')

# 장애 전파
# chart = getScatterChart2(timeslot2, month)
filename = f'./charts/mon_{regions}_{y}_{m}_{d}_4.png'
chart = create_scatter_pro(timeslot2)
chart_to_image(chart, filename)
resize_image(filename, target_width_cm=16, target_height_cm=10)
# chart_to_image(chart, resize)
# chart_to_image(chart, filename)
# chart.save(f'./charts/mon_{regions}_{y}_{m}_{d}_4.png')

# Chart - 라인 차트
df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# data = counter_3d_incident(df_filtered, ym)
data = counter_3d(df_filtered,ym2)
chart = getLineChart_new(data)
# chart = getLineChart2(df_filtered, month)
# chart = getLineChart2s(df_filtered, month)
chart.save(f'./charts/mon_{regions}_{y}_{m}_{d}_3.png')

Timeslot Empty DataFrame
Columns: [일, 장애인지, 리전]
Index: []
Timeslot Empty DataFrame
Columns: [일, 장애전파, 리전]
Index: []
ym_index 28
realList ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
dup ['202311', '202404', '202304', '202310', '202307', '202309', '202312', '202401', '202403', '202306', '202308', '202402']
최대값: 202404
최솟값: 202304
YM ['202405']
YM ['202405', '202404']
CL [0, 6]
YM ['202405', '202404', '202403']
CL [0, 6, 1]
YM ['202405', '202404', '202403', '202402']
CL [0, 6, 1, 5]
YM ['202405', '202404', '202403', '202402', '202401']
CL [0, 6, 1, 5, 3]
YM ['202405', '202404', '202403', '202402', '202401', '202312']
CL [0, 6, 1, 5, 3, 3]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311']
CL [0, 6, 1, 5, 3, 3, 6]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310']
CL [0, 6, 1, 5, 3, 3, 6, 4]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309']
CL [0, 6, 1, 5, 3, 3, 6, 4, 3]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308']
CL [0, 6, 1, 5, 3, 3, 6, 4, 3, 8]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307']
CL [0, 6, 1, 5, 3, 3, 6, 4, 3, 8, 8]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
CL [0, 6, 1, 5, 3, 3, 6, 4, 3, 8, 8, 1]
      Date  합계
0   202405   0
1   202404   6
2   202403   1
3   202402   5
4   202401   3
5   202312   3
6   202311   6
7   202310   4
8   202309   3
9   202308   8
10  202307   8
11  202306   1

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

In [51]:
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/mon_{regions}_{y}_{m}_{d}_3.png')
document.add_page_break()

# Document
document.add_paragraph(f'일별 장애인지 소요시간(분) 현황', style='List Bullet')
document.add_paragraph(f'장애인지SLO(15분) 초과: {len(df_failed)} 건', style='List Bullet')
document.add_picture(f'./charts/mon_{regions}_{y}_{m}_{d}_2.png')

if df_failed.empty :
    pass
else:
    addFailedTable(df_failed, month)
    
p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)
    
# Document
document.add_paragraph(f'일별 장애전파 소요시간(분) 현황', style='List Bullet')
document.add_paragraph(f'장애전파SLO(15분) 초과: {len(df_failed2)} 건', style='List Bullet')
document.add_picture(f'./charts/mon_{regions}_{y}_{m}_{d}_4.png')

# document.add_page_break()
##  (향후) 평균 소요 시간, 최대 소요 시간 추가 하자!!!
if df_failed2.empty :
    pass
else:
    addFailedTable2(df_failed2, month)

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)
document.add_page_break()

In [52]:
document.save('demo.docx')

## (신규포탈)이슈관리(완료)

In [53]:
data_endpoint = 'http://10.11.66.85:8080/issues/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [54]:
df = pd.DataFrame(result['data'])

In [55]:
print(df.columns)

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'title', 'target', 'description', 'completed_at',
       'occurred_at', 'resolved_at', 'ticket_no', 'is_draft', 'is_use',
       'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [56]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'progress', 'title', 'target', 'description', 'completed_at',
        'occurred_at', 'resolved_at', 'created_at_str','updated_at_str']]

In [57]:
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', '대상', '작업내용','completed_at', '시작일', '완료일', 'created_at', 'updated_at']

In [58]:
df.head()

,년,월,리전,AZ,테넌트,진행상태,제목,대상,작업내용,completed_at,시작일,완료일,created_at,updated_at
0,2024,05,NA,2,PRD,Completed,com19-0105.us-west-1.hcloud.h53 System status ...,<p>com19-0105.us-west-1.hcloud.h53</p>\n,<p>- com19-0105.us-west-1.hcloud.h53 DIMM B7 m...,2024-06-10 08:57:39,2024-05-27T11:29:47,None,2024-05-29 11:32:15,2024-06-10 08:57:39
1,2024,05,NA,1,PRD,Completed,na_cloud_prd_netapp na_cloud_prd_netapp got Fa...,<p>NA_CLOUD_PRD Netapp</p>\n,<p>- Disk fail</p>\n\n<p>-Replacement disk hav...,2024-06-10 08:57:15,2024-05-28T11:32:17,None,2024-05-29 11:34:53,2024-06-10 08:57:15
2,2024,06,NA,2,PRD,Completed,us102-com02-0106.us-west-1.hcloud.h53 : Interf...,<p>us102-com02-0106.us-west-1.hcloud.h53&nbsp;...,<p>us102-com02-0106.us-west-1.hcloud.h53 : Int...,2024-06-07 10:53:52,2024-05-16T19:55:05,None,2024-06-04 19:56:31,2024-06-07 10:53:52
3,2024,05,NA,1,PRD,Completed,nacloudprdcomd514 ping fails,<p>nacloudprdcomd514</p>\n,<p>-nacloudprdcomd514 ping fail.</p>\n\n<p>-Is...,2024-06-07 11:00:27,2024-05-25T11:35:19,None,2024-05-29 11:38:11,2024-06-06 11:00:27
4,2024,02,KR,1,PRD,Completed,의왕 신운영계 HP서버 SSD Disk Wear Out 이슈,<p><strong><strong>krcloudprdcomhr712</strong>...,<ul>\n\t<li><strong>SSD Disk Wear Out (디스크 수명 ...,2024-06-05 13:54:35,2023-12-30T12:11:00,None,2024-02-14 12:12:00,2024-06-05 14:01:31

In [59]:
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

print(df_filtered)
print(df_filtered_current)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & (df_filtered['completed_at'] >= first_date) & (df_filtered['completed_at']<= last_date)]
completed_rows = len(df_completed)
completed = len(df_completed)
print(completed_rows)

df_incompleted = df_filtered[ (df_filtered['진행상태']=='In-progress') & (df_filtered['created_at']<= last_date)]
incompleted_rows = len(df_incompleted)
incompleted = len(df_incompleted)
print(incompleted_rows)

# 보고서 뽑는 시점에 완료된 것중에, 전월 말쯤에 진행중이었다가 현월에 완료된 경우
# 예를들어 3월 27일에 생성됐는데, 4월 3일쯤에 완료처리가 된 경우
# 그러면 3월엔 진행중, 4월엔 완료건으로 들어가야 한다.
if df_filtered[ (df_filtered['진행상태']=='Completed') & (df_filtered['created_at']<= last_date) & (df_filtered['completed_at'] >= first_date_next) & (df_filtered['completed_at']<= last_date_next)] is not None:
    df_incompleted_2 = df_filtered[ (df_filtered['진행상태']=='Completed') & (df_filtered['created_at']<= last_date) & (df_filtered['completed_at'] >= first_date_next) & (df_filtered['completed_at']<= last_date_next)]
    df_incompleted_2['진행상태'] = 'In-progress'
    print("df2", df_incompleted_2)
    df_incompleted = pd.concat([df_incompleted, df_incompleted_2])
    incompleted = len(df_incompleted)

        년   월  리전 AZ  테넌트       진행상태  \
43   2023  04  RU  1  PRD  Completed
72   2022  03  RU  1  PRD  Completed
79   2023  04  RU  1  PRD  Completed
133  2022  10  RU  1  PRD  Completed
163  2022  06  RU  1  PRD  Completed
177  2022  09  RU  1  PRD  Completed
203  2022  01  RU  1  PRD  Completed
267  2022  06  RU  1  PRD  Completed
278  2022  01  RU  1  PRD  Completed
305  2022  04  RU  1  PRD  Completed

                                                    제목  \
43            / disk size is over 90%: ccsrumonitorp02
72                                     RU FW Commit 실패
79   Unable to access Front LED Panel because of a ...
133                   우크라이나 사태로 인한 글로벌 제재로 공식 RMA 지원불가
163                                   PRD CPU 자원 증설 필요
177                   우크라이나 사태로 인한 글로벌 제재로 공식 RMA 지원불가
203                                      러시아 글로벌 회선 작업
267         Dell Technologies Corporation 물리 RMA 지원 불가
278                                    RU IPMI 스크립트 오류
305  팔로알토 방화벽 OS 업그레이드(완료) RU STG FW *2ea(완료) RU PR...

                                                    대상  \
43            ctive 서버와 Standby 서버 데이터 정합성이 맞지않아 알람 발생
72                                 정책 추가 후 Commit 시 실패
79                                       펌웨어 문제로 알람 발생
133  우크라이나 사태로 인한 글로벌 제재로 공식 RMA 지원불가하여 로컬 벤더를 통한 유...
163                                       RU PRD VM 생성
177  우크라이나 사태로 인한 글로벌 제재로 공식 RMA 지원불가하여 로컬 벤더를 통한 유...
203                              한국 ↔ 러시아 글로벌 회선 장애 발생
267                          RucloudPRDcomdr101 메모리 에러
278                                    RU IPMI 스크립트 오류
305                                  팔로알토 방화벽 OS 업그레이드

                                                  작업내용         completed_at  \
43                             정합성 맞추는 작업 진행하여 현재 정상상태  2023-04-01 00:00:00
72   방화벽 정책 추가 후 적용(Commit) 버튼 클릭 시 간헐적으로 Fail 발생문제...  2022-03-01 00:00:00
79                          러시아 법인에서 펌웨어 업그레이드 진행 후 해소  2023-04-01 00:00:00
133                                               None  2022-10-01 00:00:00
163  운영계 (RU-CCS-LINUX) - CPU 자원 부족=> CPU 평균 사용량 12...  2022-06-01 00:00:00
177                                               None  2022-09-01 00:00:00
203  01/15 저녁 7시경 러시아 클라우드 HW장비 Down 알람 발생=> 확인결과 러...  2022-01-01 00:00:00
267  메모리 에러(correctable memory error) 발생RUCloudPrdC...  2022-06-01 00:00:00
278  RU PRD deploy 서버(10.107.17.24)에 대해 RU IPMI Swi...  2022-01-01 00:00:00
305  글로벌 팔로알토 방화벽 8.1.x 버전 EOS로 인한 OS업그레이드=> 8.1.x ...  2022-04-01 00:00:00

                     시작일                  완료일           created_at  \
43   2023-03-16T12:00:00  2023-04-14T00:00:00  2023-04-01 00:00:00
72   2021-11-12T12:00:00  2022-03-17T00:00:00  2022-03-01 00:00:00
79   2023-04-04T12:00:00  2023-04-07T00:00:00  2023-04-01 00:00:00
133  2022-07-25T12:00:00                 None  2022-10-01 00:00:00
163  2021-08-06T12:00:00                 None  2022-06-01 00:00:00
177  2022-05-24T12:00:00                 None  2022-09-01 00:00:00
203  2022-01-05T12:00:00  2022-01-05T00:00:00  2022-01-01 00:00:00
267  2022-06-06T12:00:00                 None  2022-06-01 00:00:00
278  2022-01-01T12:00:00  2022-01-24T00:00:00  2022-01-01 00:00:00
305  2022-02-09T12:00:00  2022-04-07T00:00:00  2022-04-01 00:00:00

              updated_at
43   2024-01-04 17:54:00
72   2024-01-04 17:54:00
79   2024-01-04 17:54:00
133  2024-01-04 17:54:00
163  2024-01-04 17:54:00
177  2024-01-04 17:54:00
203  2024-01-04 17:54:00
267  2024-01-04 17:54:00
278  2024-01-04 17:54:00
305  2024-01-04 17:54:00
Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 대상, 작업내용, completed_at, 시작일, 완료일, created_at, updated_at]
Index: []
0
0
df2 Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 대상, 작업내용, completed_at, 시작일, 완료일, created_at, updated_at]
Index: []

In [60]:
merge_for_current = pd.concat([df_completed, df_incompleted])
print(merge_for_current)

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 대상, 작업내용, completed_at, 시작일, 완료일, created_at, updated_at]
Index: []

In [61]:
# Chart - Pie 차트
t = completed + incompleted

if len(regions) > 1: # == 'All':
    
    # Data
    rowsc = df_completed
    rowsi = df_incompleted
    
    # print(rowsc)
    
    document.add_heading('이슈관리', level=1) 
    # Document
    document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 진행: {incompleted} 건)', style='List Bullet')
    # Chart
    #chartc = getPieChart(sourcec)
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/imc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/imi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format(''))
        run.add_picture(f'./charts/imc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}진행".format(''))
        run.add_picture(f'./charts/imi_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/imi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/imi_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/imc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/imc_{y}_{m}_{d}_{v}_1.png')
    
else:
    document.add_heading('이슈관리', level=1) 
    if t == completed :
        if t == 0 : 
            document.add_paragraph(f'총 {t} 건', style='List Bullet')
        else:
            document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
    else :
        document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 진행: {incompleted} 건)', style='List Bullet')
    pass

# Chart - 라인 차트 
# counter_3d 가 있어야 0이어도 숫자 나옴
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# print(df_filtered)
# data = counter_3d(df_filtered)
# data = counter_3d(df_filtered,ym2)
df_filtered['Date'] = df_filtered.apply(assign_date, axis=1)
print(df_filtered['Date'])
data = counter_3d_temp(df_filtered,ym2)
# data.loc[(data['Date'] == '202402') & (data['합계'] == 2), '합계'] = 3
print(data)
chart = getLineChart_new(data)
chart.save(f'./charts/im_{regions}_{y}_{m}_{d}_2.png', inline=True)

43     202304
72     202203
79     202304
133    202210
163    202206
177    202209
203    202201
267    202206
278    202201
305    202204
Name: Date, dtype: object
      Date  합계
0   202306   0
1   202307   0
2   202308   0
3   202309   0
4   202310   0
5   202311   0
6   202312   0
7   202401   0
8   202402   0
9   202403   0
10  202404   0
11  202405   0

In [62]:
# Document
total_sum = completed + incompleted

document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/im_{regions}_{y}_{m}_{d}_2.png')

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

df_filtered_selectedColumns=df_filtered[['월','리전', 'AZ', '진행상태', '제목', '작업내용']]
df_filtered_selectedColumns.sort_values(by=['리전'], ascending=False, inplace=True)
df_filtered_selectedColumns.reset_index(drop=True, inplace=True)
df_filtered=df_filtered_selectedColumns

# print(df_filtered)
print(merge_for_current)

# Document
# if df_filtered[df_filtered['월']==month].empty :
#     pass
# else:
#     addTable4(df_filtered, regex, month)

document.add_paragraph('상세 현황', style='List Bullet')

if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addTable_issue_all(merge_for_current)
    else:
        addTable_issue(merge_for_current)
# p = document.add_paragraph('')
# run = p.add_run()
# run.add_break(WD_BREAK.LINE)

# document.add_paragraph(f'월별 추세', style='List Bullet')
# document.add_picture(f'./charts/im_{region}_{y}_{m}_{d}_2.png')
document.add_page_break()

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 대상, 작업내용, completed_at, 시작일, 완료일, created_at, updated_at]
Index: []

In [63]:
document.save('demo.docx')

## (신규포탈)장애관리(완료)

In [64]:
data_endpoint = 'http://10.11.66.85:8080/problems/list'
# Request header

request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
async with httpx.AsyncClient(timeout=httpx.Timeout(read_timeout=30)) as client:
    result = await fetch_data(access_token, data_endpoint, request_header)

In [65]:
df = pd.DataFrame(result['data'])

In [66]:
print(df)

       id  year month day region az tenant customer   progress  \
0       8  2024    06  10     NA  1    PRD      CCS  Completed
1       9  2024    06  10     NA  1    PRD      CCS  Completed
2      10  2024    06  10     NA  2    PRD      CCS  Completed
3       7  2024    06  10     NA  1    PRD      CCS  Completed
4       6  2024    06  10     NA  2    PRD      CCS  Completed
..    ...   ...   ...  ..    ... ..    ...      ...        ...
338  1107  2023    07  01     RU  1    PRD      CCS  Completed
339  1036  2023    05  01     NA  2    PRD      CCS  Completed
340  1220  2023    12  01     NA  1    CDO      CCS  Completed
341   987  2022    08  01     KR  1    PRD      CCS  Completed
342  1182  2023    11  01     KR  1    CDO      CCS  Completed

                                                 title  ...  \
0    na_cloud_prd_netapp na_cloud_prd_netapp got Fa...  ...
1                         nacloudprdcomd514 ping fails  ...
2    com19-0105.us-west-1.hcloud.h53 System status ...  ...
3          북미 DR 9000 스토리지에서 디스크 Fault 가 1개 더 발생하였습니다.  ...
4    com05-0106.us-west-1.hcloud.h53 has been resta...  ...
..                                                 ...  ...
338  Correctable memory error on DIMM_A5 RUCloudPrd...  ...
339  US_West_02_L4_PRD_Netapp_Cluster node health s...  ...
340  Problem: hmapc00dn005.pus0c06.hcloud.io Disk r...  ...
341  vpx-prd-a RNAT 세션 증가 및 1센터 DB full connection으...  ...
342  Problem: Physical Disk 0:1:4: Physical disk fa...  ...

                                           description     ticket_no  \
0    <p>- Disk fail</p>\n\n<p>-Replacement disk hav...  NACLOUD-4345
1    <p>-nacloudprdcomd514 ping fail.</p>\n\n<p>-Is...  NACLOUD-4278
2    <p>- com19-0105.us-west-1.hcloud.h53 DIMM B7 m...  NACLOUD-4333
3    <ul>\n\t<li>Disk Fail</li>\n\t<li>Disk Replace...  NACLOUD-4246
4    <ul>\n\t<li>Memory DIMM A1 error.</li>\n\t<li>...  NACLOUD-4223
..                                                 ...           ...
338  DIMM_A5 correctable error.Rebooting the ctrl3 ...   RUCLOUD-986
339  US_West_01_L4_PRD_Netapp_Cluster node health s...  NACLOUD-2239
340  Identified failed disk on the serverDisk repla...  NACLOUD-3395
341  22/08/09 23:30 1센터 db connection 세션이 full차서 장애...          None
342                          4번 Disk Fault 에러 발생RMA 완료    ITSM-10485

    reviewed_at                                        review_desc  \
0          None                                               None
1          None                                               None
2          None                                               None
3          None                                               None
4          None                                               None
..          ...                                                ...
338        None                                               None
339        None                                               None
340        None                                               None
341        None  22/05/03 tibero 엔지니어와 복구 작업 후 log 분석 요청22/05/1...
342        None                                               None

            completed_at is_draft is_use updater       created_at_str  \
0    2024-06-10 17:25:46    False   True     최원석  2024-05-10 17:01:28
1    2024-06-10 17:25:44    False   True     최원석  2024-05-10 17:04:08
2    2024-06-10 17:25:42    False   True     최원석  2024-05-10 17:05:32
3    2024-05-10 16:55:50    False   True     최원석  2024-05-10 16:55:50
4    2024-05-10 16:51:44    False   True     최원석  2024-05-10 16:51:44
..                   ...      ...    ...     ...                  ...
338  2023-07-01 00:00:00    False   True   test2  2023-07-01 00:00:00
339  2023-05-01 00:00:00    False   True   test2  2023-05-01 00:00:00
340  2023-12-01 00:00:00    False   True   test2  2023-12-01 00:00:00
341  2022-08-01 00:00:00    False   True   test2  2022-08-01 00:00:00
342  2023-11-01 00:00:00    False   True   test2  2023-11-01 00:00:00

          updated_at_str
0    2024-06-10 17:25:46
1    2024-06-10 17:25:44
2    2024-06-10 17:25:42
3    2024-06-10 16:55:50
4    2024-06-10 16:51:44
..                   ...
338  2024-01-04 15:22:00
339  2024-01-04 15:22:00
340  2024-01-04 15:22:00
341  2024-01-04 15:22:00
342  2024-01-04 15:22:00

[343 rows x 25 columns]

In [67]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'title', 'target', 'occurred_at', 'person_in_charge',
       'rca_desc', 'impact', 'description', 'ticket_no', 'reviewed_at',
       'review_desc', 'completed_at', 'is_draft', 'is_use', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [68]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'progress', 'title',
         'target', 'occurred_at', 'person_in_charge', 'rca_desc', 'impact', 'description', 'ticket_no',
         'reviewed_at', 'review_desc',  'completed_at', 'is_draft', 'is_use', 'created_at_str', 'updated_at_str']]

In [69]:
# df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', '작업내용']
df.columns = [ '년', '월', '리전', 'AZ', '테넌트', '진행상태', '제목', 
               '내용', 'occurred_at', 'person_in_charge', 'rca_desc', 'impact', '작업내용', 'ticket_no',
               'reviewed_at', 'review_desc', 'completed_at', 'is_draft', 'is_use', 'created_at', 'updated_at']

In [70]:
df.head()

,년,월,리전,AZ,테넌트,진행상태,제목,내용,occurred_at,person_in_charge,...,impact,작업내용,ticket_no,reviewed_at,review_desc,completed_at,is_draft,is_use,created_at,updated_at
0,2024,06,NA,1,PRD,Completed,na_cloud_prd_netapp na_cloud_prd_netapp got Fa...,<p>NA_CLOUD_PRD Netapp</p>\n,2024-05-28T17:00:19,None,...,Reboot,<p>- Disk fail</p>\n\n<p>-Replacement disk hav...,NACLOUD-4345,None,None,2024-06-10 17:25:46,False,True,2024-05-10 17:01:28,2024-06-10 17:25:46
1,2024,06,NA,1,PRD,Completed,nacloudprdcomd514 ping fails,<p>nacloudprdcomd514</p>\n,2024-05-25T17:02:28,Ahmed,...,Reboot,<p>-nacloudprdcomd514 ping fail.</p>\n\n<p>-Is...,NACLOUD-4278,None,None,2024-06-10 17:25:44,False,True,2024-05-10 17:04:08,2024-06-10 17:25:44
2,2024,06,NA,2,PRD,Completed,com19-0105.us-west-1.hcloud.h53 System status ...,<p>com19-0105.us-west-1.hcloud.h53</p>\n,2024-05-29T17:04:39,Ahmed,...,Reboot,<p>- com19-0105.us-west-1.hcloud.h53 DIMM B7 m...,NACLOUD-4333,None,None,2024-06-10 17:25:42,False,True,2024-05-10 17:05:32,2024-06-10 17:25:42
3,2024,06,NA,1,PRD,Completed,북미 DR 9000 스토리지에서 디스크 Fault 가 1개 더 발생하였습니다.,<p><strong>북미&nbsp;DR 9000&nbsp;스토리지</strong><...,2024-05-12T16:51:57,Ahmed,...,Reboot,<ul>\n\t<li>Disk Fail</li>\n\t<li>Disk Replace...,NACLOUD-4246,None,None,2024-05-10 16:55:50,False,True,2024-05-10 16:55:50,2024-06-10 16:55:50
4,2024,06,NA,2,PRD,Completed,com05-0106.us-west-1.hcloud.h53 has been resta...,"<p><strong><a href=""http://com05-0106.us/"">com...",2024-05-12T16:49:04,Ahmed,...,Reboot,<ul>\n\t<li>Memory DIMM A1 error.</li>\n\t<li>...,NACLOUD-4223,None,None,2024-05-10 16:51:44,False,True,2024-05-10 16:51:44,2024-06-10 16:51:44

In [71]:
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

print(df_filtered)
print(df_filtered_current)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & (df_filtered['completed_at'] >= first_date) & (df_filtered['completed_at']<= last_date)]
# completed_rows = len(df_completed)
completed = len(df_completed)
# print(completed_rows)

df_incompleted = df_filtered[ (df_filtered['진행상태']=='In-progress') & (df_filtered['created_at']<= last_date)]
# incompleted_rows = len(df_incompleted)
incompleted = len(df_incompleted)
# print(incompleted_rows)

# 보고서 뽑는 시점에 완료된 것중에, 전월 말쯤에 진행중이었다가 현월에 완료된 경우
# 예를들어 3월 27일에 생성됐는데, 4월 3일쯤에 완료처리가 된 경우
# 그러면 3월엔 진행중, 4월엔 완료건으로 들어가야 한다.
if df_filtered[ (df_filtered['진행상태']=='Completed') & (df_filtered['created_at']<= last_date) & (df_filtered['completed_at'] >= first_date_next) & (df_filtered['completed_at']<= last_date_next)] is not None:
    df_incompleted_2 = df_filtered[ (df_filtered['진행상태']=='Completed') & (df_filtered['created_at']<= last_date) & (df_filtered['completed_at'] >= first_date_next) & (df_filtered['completed_at']<= last_date_next)]
    df_incompleted_2['진행상태'] = 'In-progress'
    print("df2", df_incompleted_2)
    df_incompleted = pd.concat([df_incompleted, df_incompleted_2])
    incompleted = len(df_incompleted)

merge_for_current = pd.concat([df_completed, df_incompleted])
print(merge_for_current)

        년   월  리전 AZ  테넌트       진행상태  \
212  2023  07  RU  1  PRD  Completed
226  2022  12  RU  1  PRD  Completed
338  2023  07  RU  1  PRD  Completed

                                                    제목  \
212  RUCloudPrdBL-A <-> RUCloudPrdL7-A 간 인터페이스 Erro...
226                       ccsrudbp01,02 split brain 발생
338  Correctable memory error on DIMM_A5 RUCloudPrd...

                                           내용          occurred_at  \
212                    RUCloudPrdBL-A eth 28   2023-07-15T00:00:00
226                            ccsrudbp01, 02  1900-01-01T00:00:00
338  OpenStack controller 3 (RUCloudPrdCtl03)  2023-07-03T00:00:00

    person_in_charge  ...  impact  \
212            Ahmed  ...    None
226          고희경,채한길  ...  DB 비정상
338            Ahmed  ...    None

                                                  작업내용  \
212  Sent the inforamtion to RU team to request GIB...
226  Standby Server live migration 작업 중 split brain...
338  DIMM_A5 correctable error.Rebooting the ctrl3 ...

                  ticket_no reviewed_at review_desc         completed_at  \
212             RUCLOUD-997        None        None  2023-07-01 00:00:00
226  RUCLOUD-863RUCLOUD-865        None        None  2022-12-01 00:00:00
338             RUCLOUD-986        None        None  2023-07-01 00:00:00

    is_draft  is_use           created_at           updated_at
212    False    True  2023-07-01 00:00:00  2024-01-04 15:22:00
226    False    True  2022-12-01 00:00:00  2024-01-04 15:22:00
338    False    True  2023-07-01 00:00:00  2024-01-04 15:22:00

[3 rows x 21 columns]
Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 내용, occurred_at, person_in_charge, rca_desc, impact, 작업내용, ticket_no, reviewed_at, review_desc, completed_at, is_draft, is_use, created_at, updated_at]
Index: []

[0 rows x 21 columns]
df2 Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 내용, occurred_at, person_in_charge, rca_desc, impact, 작업내용, ticket_no, reviewed_at, review_desc, completed_at, is_draft, is_use, created_at, updated_at]
Index: []

[0 rows x 21 columns]
Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 내용, occurred_at, person_in_charge, rca_desc, impact, 작업내용, ticket_no, reviewed_at, review_desc, completed_at, is_draft, is_use, created_at, updated_at]
Index: []

[0 rows x 21 columns]

In [72]:
print(df_completed)
print(completed, incompleted)

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 내용, occurred_at, person_in_charge, rca_desc, impact, 작업내용, ticket_no, reviewed_at, review_desc, completed_at, is_draft, is_use, created_at, updated_at]
Index: []

[0 rows x 21 columns]
0 0

In [73]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    
    # Data
    rowsc = df_completed
    rowsi = df_incompleted
    
    document.add_heading('장애(RCA)관리', level=1) 
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    
    # Chart
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format(''))
        run.add_picture(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}진행".format(''))
        run.add_picture(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')

else:
    document.add_heading('장애(RCA)관리', level=1) 
    t = completed + incompleted
    if t == completed :
        if t == 0 : 
            document.add_paragraph(f'총 {t} 건', style='List Bullet')
        else:
            document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
    else :
        document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 이슈: {incompleted} 건)', style='List Bullet')
    pass


# Chart - 라인 차트
# if region == 'SG':
#     data = { '월' : ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'], '합계' : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
#     data = pd.DataFrame(data)
# else:
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# data = counter_3d(df_filtered)
df_filtered['Date'] = df_filtered.apply(assign_date, axis=1)
data = counter_3d_temp(df_filtered,ym2)
# data.loc[(data['Date'] == '202402') & (data['합계'] == 5), '합계'] = 8
chart = getLineChart_new(data)
# chart = getLineChart(data)
chart.save(f'./charts/pm_{regions}_{y}_{m}_{d}_2.png')
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/pm_{regions}_{y}_{m}_{d}_2.png')

In [74]:
print(type(merge_for_current))
print(merge_for_current)
p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

df_filtered.sort_values(by=['리전'], axis=0, ascending=False)

document.add_paragraph('상세 현황', style='List Bullet')

# Document
if merge_for_current.empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addTable4_all(merge_for_current)
    else:
        addTable4(merge_for_current)
        
document.add_page_break()

<class 'pandas.core.frame.DataFrame'>
Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 진행상태, 제목, 내용, occurred_at, person_in_charge, rca_desc, impact, 작업내용, ticket_no, reviewed_at, review_desc, completed_at, is_draft, is_use, created_at, updated_at]
Index: []

[0 rows x 21 columns]

In [75]:
document.save('demo.docx')

## (신규포탈)변경관리(완료)

In [76]:
data_endpoint = 'http://10.11.66.85:8080/changes/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202201010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [77]:
df = pd.DataFrame(result['data'])

In [78]:
print(df)

        id  year month day region az tenant customer  urgency cm_progress  \
0     2217  2024    06  11     KR  2    PRD      CCS  Planned     Created
1     2216  2024    06  11     KR  2    PRD      CCS  Planned     Created
2     2208  2024    06  05     KR  2    PRD      CCS  Planned   Completed
3     2209  2024    06  05     KR  2    PRD      CCS  Planned   Completed
4     2199  2024    06  04     KR  2    PRD      CCS  Planned   Completed
...    ...   ...   ...  ..    ... ..    ...      ...      ...         ...
2060    19  2022    02  01     RU  1    PRD      CCS  Planned   Completed
2061    28  2022    02  01     EU  1    PRD      CCS  Planned   Completed
2062    15  2022    02  01     EU  1    STG      CCS  Planned   Completed
2063    38  2022    02  01     SG  1    PRD      CCS  Planned   Completed
2064    11  2022    02  01     CN  1    PRD      CCS  Planned   Completed

      ... review_date engineer reviewer                 requestor  \
0     ...    20240611      임정현      정종인               이지민/CCS플랫폼팀
1     ...    20240611      임정현      정종인                 이용/SCM운영팀
2     ...    20240605      임정현      정종인  권도용 매니저 고객판매데이터엔지니어링Cell
3     ...    20240605      임정현      정종인      이경룡 책임연구원 / CCS서버개발팀
4     ...    20240605      김은혜      오창민            이창현/그룹웨어서비스개발팀
...   ...         ...      ...      ...                       ...
2060  ...        None     None     None                      None
2061  ...        None     None     None                      None
2062  ...        None     None     None                      None
2063  ...        None     None     None                      None
2064  ...        None     None     None                      None

             completed_at is_draft is_use updater       created_at_str  \
0                    None    False   True     임정현  2024-06-11 11:19:19
1                    None    False   True     임정현  2024-06-11 11:17:40
2     2024-06-11 11:06:19    False   True     임정현  2024-06-05 01:28:53
3     2024-06-11 11:06:12    False   True     임정현  2024-06-05 01:30:20
4     2024-06-11 10:54:26    False   True     김은혜  2024-06-04 16:05:11
...                   ...      ...    ...     ...                  ...
2060  2022-02-01 00:00:00    False   True   test2  2024-01-04 18:33:00
2061  2022-02-01 00:00:00    False   True   test2  2024-01-04 18:33:00
2062  2022-02-01 00:00:00    False   True   test2  2024-01-04 18:33:00
2063  2022-02-01 00:00:00    False   True   test2  2024-01-04 18:33:00
2064  2022-02-01 00:00:00    False   True   test2  2024-01-04 18:33:00

           updated_at_str
0     2024-06-11 11:21:05
1     2024-06-11 11:19:16
2     2024-06-11 11:06:19
3     2024-06-11 11:06:12
4     2024-06-11 10:54:26
...                   ...
2060  2022-02-01 00:00:00
2061  2022-02-01 00:00:00
2062  2022-02-01 00:00:00
2063  2022-02-01 00:00:00
2064  2022-02-01 00:00:00

[2065 rows x 28 columns]

In [79]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'urgency', 'cm_progress', 'work_type', 'task', 'system', 'work_date',
       'local_date', 'impact', 'description', 'ticket_no', 'review_date',
       'engineer', 'reviewer', 'requestor', 'completed_at', 'is_draft',
       'is_use', 'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [80]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'urgency', 'cm_progress', 'work_type', 'task', 'system', 'description', 'ticket_no', 'engineer', 'completed_at', 'is_draft', 'is_use', 'created_at_str', 'updated_at_str']]

In [81]:
df.columns = [ '년', '월', '리전', 'AZ', '테넌트', '긴급도', '진행상태', '작업유형', '제목', '대상', '작업내용', 'ticket_no', 'engineer', 'completed_at', 'is_draft', 'is_use', 'created_at', 'updated_at']

In [82]:
df.head()

,년,월,리전,AZ,테넌트,긴급도,진행상태,작업유형,제목,대상,작업내용,ticket_no,engineer,completed_at,is_draft,is_use,created_at,updated_at
0,2024,06,KR,2,PRD,Planned,Created,Loadbalancer,LB 멤버변경,<p>LB:&nbsp;10.11.91.25:5602</p>\n\n<p>변경VM:&n...,<p>담당자 요청으로 LB 인증서 갱신</p>\n,KRCLOUD-12638,임정현,None,False,True,2024-06-11 11:19:19,2024-06-11 11:21:05
1,2024,06,KR,2,PRD,Planned,Created,Loadbalancer,인증서 갱신,<p>LB:&nbsp;121.78.27.204:443</p>\n,<p>담당자 요청으로 LB 인증서 갱신</p>\n,KRCLOUD-12599,임정현,None,False,True,2024-06-11 11:17:40,2024-06-11 11:19:16
2,2024,06,KR,2,PRD,Planned,Completed,Loadbalancer,LB 멤버 추가,<p>LB:&nbsp;10.11.90.67:8004</p>\n\n<p>추가 VM:&...,<p>담당자 요청으로 LB 멤버 추가</p>\n,KRCLOUD-12503,임정현,2024-06-11 11:06:19,False,True,2024-06-05 01:28:53,2024-06-11 11:06:19
3,2024,06,KR,2,PRD,Planned,Completed,Loadbalancer,LB 생성,<p>LB:&nbsp;10.11.91.38:31100</p>\n,<p>담당자 요청으로 LB 생성</p>\n,KRCLOUD-12533,임정현,2024-06-11 11:06:12,False,True,2024-06-05 01:30:20,2024-06-11 11:06:12
4,2024,06,KR,2,PRD,Planned,Completed,Loadbalancer,LB XFF 설정,"<p>1. api.hmg.gfcsp-hmg-lb-web.kr2-prd-c: 80,4...",<p>담당자 요청으로 운영계 LB XFF 설정 추가 작업</p>\n,KRCLOUD-12604,김은혜,2024-06-11 10:54:26,False,True,2024-06-04 16:05:11,2024-06-11 10:54:26

In [83]:
# 월별추세용, 상세현황용
df_filtered = df[ (df['리전'].isin(regions)) & (df['테넌트'].isin(['PRD'])) & (df['진행상태'].isin(['Completed', 'Failed', 'Canceled', 'Rejected']))]
df_filtered_current = df_filtered[(df_filtered['completed_at'] >= '2024-05-01') & (df_filtered['completed_at'] <= '2024-05-31 23:59:59')]
# df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['updated_at'].between('2024-02-01', '2024-02-29') ]
# df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
# df_filtered = df[df['updated_at'].between('2024-02-01', '2024-02-29')]
# print(df_filtered_current)

# Pivoting
# pivot, total = getPivotTable(df, month, y)

# df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# df_completed = df_filtered_current[ df_filtered_current['진행상태'].isin(['Completed']) ]
df_completed = df_filtered[(df_filtered['completed_at'] >= '2024-05-01') & (df_filtered['completed_at'] <= '2024-05-31 23:59:59')]
completed = len(df_completed)

# df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['In-progress']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# incompleted = len(df_incompleted)

In [84]:
print(df_filtered_current)
print(completed)

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 긴급도, 진행상태, 작업유형, 제목, 대상, 작업내용, ticket_no, engineer, completed_at, is_draft, is_use, created_at, updated_at]
Index: []
0

In [85]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    
    # rowsc = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Completed']))]
    # rowsi = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['In-progress']))]

    document.add_heading('변경관리', level=1) 
    # document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    document.add_paragraph(f'총 {completed}건 (완료: {completed})', style='List Bullet')
    
    # if completed !=0 and incompleted !=0:
    #     datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
    #     sourcec = pivotc
    #     datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
    #     sourcei = pivoti
    #     chartc = getPieChart(sourcec)
    #     charti = getPieChart(sourcei)
    #     chartc.save(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')
    #     charti.save(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
    #     table = document.add_table(rows=1, cols=2)
    #     # --- get the first cell of the first row ---
    #     cell = table.rows[0].cells[0]
    #     # --- by default a cell has one paragraph with zero runs ---
    #     paragraph = cell.paragraphs[0]
    #     # --- add a run in which to place the picture ---
    #     run = paragraph.add_run()
    #     # --- add the picture to that run ---
    #     run.add_text("{0:^44}완료".format(''))
    #     run.add_picture(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    #     cell = table.rows[0].cells[1]
    #     # --- by default a cell has one paragraph with zero runs ---
    #     paragraph = cell.paragraphs[0]
    #     # --- add a run in which to place the picture ---
    #     run = paragraph.add_run()
    #     # --- add the picture to that run ---
    #     run.add_text("{0:^44}진행".format(''))
    #     run.add_picture(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    # elif completed ==0:
    #     datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
    #     sourcei = pivoti
    #     charti = getPieChart(sourcei)
    #     charti.save(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
    #     table = document.add_table(rows=1, cols=1)
    #     cell = table.rows[0].cells[0]
    #     # --- by default a cell has one paragraph with zero runs ---
    #     paragraph = cell.paragraphs[0]
    #     # --- add a run in which to place the picture ---
    #     run = paragraph.add_run()
    #     # --- add the picture to that run ---
        # run.add_picture(f'./charts/pmi_{y}_{m}_{d}_{v}_1.png')
    if completed !=0:
        datac, pivotc, totalc = getPivotTable_event(df_completed, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/pmc_{y}_{m}_{d}_{v}_1.png')

else:
    document.add_heading('변경관리', level=1) 
    # t = completed + incompleted
    t = completed
    if t == completed :
        if t == 0 : 
            document.add_paragraph(f'총 {t} 건', style='List Bullet')
        else:
            document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
    else :
        document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 이슈: {incompleted} 건)', style='List Bullet')
    # document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    pass

# Chart - 라인 차트
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
df_filtered['Date'] = pd.to_datetime(df_filtered['completed_at']).dt.strftime('%Y%m')
print(df_filtered['completed_at'])
# data = counter_3d(df_filtered)
data = counter_3d(df_filtered,ym2)
# data.loc[(data['Date'] == '202402') & (data['합계'] == 144), '합계'] = 86
chart = getLineChart_new(data)
# chart = getLineChart2(df_filtered, month)
chart.save(f'./charts/cm_{regions}_{y}_{m}_{d}_2.png')

308     2024-04-09 13:56:56
388     2024-03-27 09:12:54
580     2024-01-30 14:45:00
688     2023-12-01 00:00:00
711     2023-12-01 00:00:00
806     2023-11-01 00:00:00
876     2023-10-01 00:00:00
891     2023-10-01 00:00:00
1087    2023-07-01 00:00:00
1271    2023-05-01 00:00:00
1295    2023-05-01 00:00:00
1330    2023-04-01 00:00:00
1341    2023-04-01 00:00:00
1381    2023-04-01 00:00:00
1518    2023-02-01 00:00:00
1522    2023-02-01 00:00:00
1642    2022-12-01 00:00:00
1643    2022-12-01 00:00:00
1678    2022-12-01 00:00:00
1735    2022-11-01 00:00:00
1737    2022-11-01 00:00:00
1742    2022-11-01 00:00:00
1749    2022-11-01 00:00:00
1760    2022-11-01 00:00:00
1874    2022-09-01 00:00:00
1914    2022-08-01 00:00:00
1996    2022-05-01 00:00:00
2018    2022-04-01 00:00:00
2027    2022-03-01 00:00:00
2049    2022-02-01 00:00:00
2060    2022-02-01 00:00:00
Name: completed_at, dtype: object
ym_index 28
realList ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
dup ['202211', '202204', '202311', '202404', '202304', '202209', '202212', '202310', '202307', '202403', '202312', '202401', '202302', '202208', '202203', '202202', '202305', '202205']
최대값: 202404
최솟값: 202202
YM ['202405']
YM ['202405', '202404']
CL [0, 1]
YM ['202405', '202404', '202403']
CL [0, 1, 1]
YM ['202405', '202404', '202403', '202402']
YM ['202405', '202404', '202403', '202402', '202401']
CL [0, 1, 1, 0, 1]
YM ['202405', '202404', '202403', '202402', '202401', '202312']
CL [0, 1, 1, 0, 1, 2]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311']
CL [0, 1, 1, 0, 1, 2, 1]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310']
CL [0, 1, 1, 0, 1, 2, 1, 2]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309']
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308']
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307']
CL [0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 1]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
      Date  합계
0   202405   0
1   202404   1
2   202403   1
3   202402   0
4   202401   1
5   202312   2
6   202311   1
7   202310   2
8   202309   0
9   202308   0
10  202307   1
11  202306   0

In [86]:
# df_filtered = df_filtered[ (df_filtered['월']==month) & (df_filtered['진행상태']=='Completed') ]
# total = len(df_filtered)

In [87]:
document.add_paragraph('월별 추세', style='List Bullet')
document.add_picture(f'./charts/cm_{regions}_{y}_{m}_{d}_2.png')

# Document
p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

document.add_paragraph('상세 현황(작업유형별)', style='List Bullet')
# rows = df_filtered.loc[(df_filtered['년']==year) & (df_filtered['월']==month)]
# print(rows)

if df_completed.empty:
    pass
else:
    data, pivot, total = getPivotTable_event(df_completed, month, regions)
    # print("data", data)
    # print("pivot", pivot)
    # print("total", total)
    source = flatten_4d(data)
    chart = get_1_4_HBarChart(data)

chart.save(f'./charts/cm_{regions}_{y}_{m}_{d}_3.png')
document.add_picture(f'./charts/cm_{regions}_{y}_{m}_{d}_3.png')

document.add_paragraph('상세 현황', style='List Bullet')

# print(df_filtered_current)

if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addTable3_all(df_completed)
    else:
        addTable3(df_completed, month)


document.add_page_break()

In [88]:
document.save('demo.docx')

## (신규포탈)요청관리(완료)

In [89]:
data_endpoint = 'http://10.11.66.85:8080/requests/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202301010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [90]:
df = pd.DataFrame(result['data'])

In [91]:
print(df)

          id  year month day region tenant customer     progress work_type  \
0      19583  2024     6  11     KR    PRD      CCS  In-progress        OS
1      19573  2024     6  11     NA    PRD      CCS  In-progress        DB
2      19611  2024     6  11     EU    PRD      CCS  In-progress        DB
3      19584  2024     6  11     KR    PRD      CCS  In-progress        DB
4      19559  2024     6  11     SG    PRD      CCS  In-progress        DB
...      ...   ...   ...  ..    ...    ...      ...          ...       ...
17953  16777  2024     4  11     CN    PRD      CCS         Done        FW
17954  14569  2024     4  11     EU    PRD      CCS         Done  SECURITY
17955  14570  2024     4  11     EU    PRD      CCS         Done  SECURITY
17956  11130  2024     4  11     KR    CDO      CCS  In-progress        OS
17957  16778  2024     4  11     CN    PRD      CCS         Done  SECURITY

                                                   title  ...  \
0                                           미사용 자원 회수 요청  ...
1                                         임시 MCCS라이센스 갱신  ...
2                                         임시 MCCS라이센스 갱신  ...
3                                         임시 MCCS라이센스 갱신  ...
4                                         임시 MCCS라이센스 갱신  ...
...                                                  ...  ...
17953                                            ims->cu  ...
17954    CnC(C_C)_Request to block the IPs_20230101_1503  ...
17955    CnC(C_C)_Request to block the IPs_20230101_1430  ...
17956  Unavailable ICMP ping for the Host: pb03dn023....  ...
17957       [중국 디지털키2] 방화벽 관련 문의 드립니다_DBSafer (20230101)  ...

                reporter sync_status           tk_created_at  \
0             박세호/CCS정보팀        None  2024-06-11 11:29:00+09
1      신영재/클라우드운영센터(협력사)        None  2024-06-11 11:16:03+09
2      신영재/클라우드운영센터(협력사)        None  2024-06-11 11:15:37+09
3      신영재/클라우드운영센터(협력사)        None  2024-06-11 11:15:01+09
4      신영재/클라우드운영센터(협력사)        None  2024-06-11 11:13:12+09
...                  ...         ...                     ...
17953             우건조 대리        None  2023-01-01 16:50:10+09
17954             Ganesh        None  2023-01-01 15:38:54+09
17955             Ganesh        None  2023-01-01 15:33:53+09
17956             Ganesh        None  2023-01-01 09:01:12+09
17957     맹재현/차량제어서비스개발팀        None  2023-01-01 03:24:56+09

                tk_updated_at          tk_resolved_at is_draft is_use  \
0      2024-06-11 11:29:36+09                    None    False   True
1      2024-06-11 11:16:10+09                    None    False   True
2      2024-06-11 11:16:16+09                    None    False   True
3      2024-06-11 12:39:05+09                    None    False   True
4      2024-06-11 11:37:56+09                    None    False   True
...                       ...                     ...      ...    ...
17953  2023-05-02 06:39:35+09  2023-05-02 06:39:35+09    False   True
17954  2023-01-19 00:05:11+09  2023-01-19 00:05:11+09    False   True
17955  2023-01-19 00:04:54+09  2023-01-19 00:04:54+09    False   True
17956  2023-01-27 06:07:43+09                    None    False   True
17957  2023-01-09 01:09:27+09  2023-01-09 01:09:27+09    False   True

       updater       created_at_str       updated_at_str
0        admin  2024-06-11 13:00:48  2024-06-11 13:00:48
1        admin  2024-06-11 13:00:48  2024-06-11 13:00:48
2        admin  2024-06-11 13:00:48  2024-06-11 13:00:48
3        admin  2024-06-11 13:00:48  2024-06-11 13:00:48
4        admin  2024-06-11 13:00:48  2024-06-11 13:00:48
...        ...                  ...                  ...
17953    admin  2024-04-11 14:14:59  2024-04-11 14:14:59
17954    admin  2024-04-11 14:14:59  2024-04-11 14:14:59
17955    admin  2024-04-11 14:14:59  2024-04-11 14:14:59
17956    admin  2024-04-11 14:14:59  2024-04-11 14:14:59
17957    admin  2024-04-11 14:14:59  2024-04-11 14:14:59

[17958 rows x 22 columns]

In [92]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'tenant', 'customer',
       'progress', 'work_type', 'title', 'ticket_no', 'assignee', 'reporter',
       'sync_status', 'tk_created_at', 'tk_updated_at', 'tk_resolved_at',
       'is_draft', 'is_use', 'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [93]:
df = df[['year', 'month', 'region', 'tenant', 'progress', 'work_type', 'title', 'assignee', 'reporter', 'sync_status',
         'tk_created_at', 'tk_updated_at', 'tk_resolved_at', 'is_draft', 'is_use']]

In [94]:
# description
df.columns = ['년', '월', '리전', '테넌트', '진행상태', 'Work Type', '제목', 'assignee', 'reporter', 'sync_status',
         'tk_created_at', 'tk_updated_at', 'tk_resolved_at', 'is_draft', 'is_use']

In [95]:
# df_delete = df [ df['sync_status'].isin('delted

In [96]:
df.head()

,년,월,리전,테넌트,진행상태,Work Type,제목,assignee,reporter,sync_status,tk_created_at,tk_updated_at,tk_resolved_at,is_draft,is_use
0,2024,6,KR,PRD,In-progress,OS,미사용 자원 회수 요청,,박세호/CCS정보팀,None,2024-06-11 11:29:00+09,2024-06-11 11:29:36+09,None,False,True
1,2024,6,NA,PRD,In-progress,DB,임시 MCCS라이센스 갱신,신영재/클라우드운영센터(협력사),신영재/클라우드운영센터(협력사),None,2024-06-11 11:16:03+09,2024-06-11 11:16:10+09,None,False,True
2,2024,6,EU,PRD,In-progress,DB,임시 MCCS라이센스 갱신,신영재/클라우드운영센터(협력사),신영재/클라우드운영센터(협력사),None,2024-06-11 11:15:37+09,2024-06-11 11:16:16+09,None,False,True
3,2024,6,KR,PRD,In-progress,DB,임시 MCCS라이센스 갱신,신영재/클라우드운영센터(협력사),신영재/클라우드운영센터(협력사),None,2024-06-11 11:15:01+09,2024-06-11 12:39:05+09,None,False,True
4,2024,6,SG,PRD,In-progress,DB,임시 MCCS라이센스 갱신,신영재/클라우드운영센터(협력사),신영재/클라우드운영센터(협력사),None,2024-06-11 11:13:12+09,2024-06-11 11:37:56+09,None,False,True

In [97]:
# tk_resolved_at 칼럼을 날짜 형식으로 변환
# df['tk_resolved_at'] = pd.to_datetime(df['tk_resolved_at'])

# 월별 건수 계산
# df['Month'] = df['tk_resolved_at'].dt.to_period('M') # 월별 기간으로 변환


# print(monthly_counts)
# print(type(monthly_counts))
# print(df_filtered_month['Date'])
# print(type(df_filtered_month))

# ym = '202311'

# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
print(len(df_filtered))
# df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['Date'].isin([ym])]

df_filtered['tk_resolved_at'] = pd.to_datetime(df_filtered['tk_resolved_at'])
# df_filtered['tk_created_at'] = pd.to_datetime(df_filtered['tk_created_at'])
df_filtered['Date'] = df_filtered['tk_resolved_at'].dt.strftime('%Y%m') # 월별 기간으로 변환
# df_filtered['Date'] = df_filtered['tk_created_at'].dt.strftime('%Y%m') # 월별 기간으로 변환
monthly_counts = df_filtered['Date'].value_counts().sort_index()
# df_filtered_count = monthly_counts.to_frame()
df_filtered_count = pd.DataFrame({'Date': monthly_counts.index, '합계': monthly_counts.values})
print(df_filtered_count)

402
      Date  합계
0   202301   3
1   202302  26
2   202303  11
3   202304  20
4   202305  13
5   202306  14
6   202307  20
7   202308  34
8   202309  11
9   202310  40
10  202311  31
11  202312  18
12  202401  14
13  202402  54
14  202403  11
15  202404  31
16  202405  36
17  202406   8

In [98]:

# print(df_filtered)

# Pivoting
# pivot, total = getPivotTable(df, month, y)

df_completed = df_filtered[ df_filtered['Date'].isin([ym2]) ]
completed = len(df_completed)

# df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['In-progress']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# incompleted = len(df_incompleted)

print("completed:", completed)
# print("incompleted:", incompleted)

completed: 36

In [99]:
# df_filtered = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['진행상태']=='완료') & (df_filtered['월']==month)]
df_filtered['Work Type'] = df_filtered['Work Type'].astype(str)
df_filtered

,년,월,리전,테넌트,진행상태,Work Type,제목,assignee,reporter,sync_status,tk_created_at,tk_updated_at,tk_resolved_at,is_draft,is_use,Date
35,2024,6,RU,PRD,In-progress,FW,[zabbix] 러시아 zabbix 방화벽 해제 요청,강진구/클라우드운영센터(협력사),박유나/CCS플랫폼팀,None,2024-06-10 18:44:53+09,2024-06-11 08:07:14+09,NaT,False,True,NaN
37,2024,6,RU,PRD,Done,SECURITY,CnC(C_C)_Request to block the IPs_20240610_0839,Ram,RAM SENTHIL KUMAR R/CCSInfraSection(GDC),None,2024-06-10 18:35:36+09,2024-06-11 10:20:40+09,2024-06-11 10:20:40+09:00,False,True,202406
129,2024,6,RU,PRD,Done,SECURITY,CnC(C_C)_Request to block the IPs_20240607_1613,Saju,Saju,None,2024-06-07 18:10:58+09,2024-06-10 15:39:05,2024-06-10 15:39:05+09:00,False,True,202406
178,2024,6,RU,PRD,In-progress,DB,Zabbix database is not available. MySQL databa...,박기완/클라우드운영센터(협력사),정진호/클라우드운영센터(협력사),None,2024-06-06 21:26:08+09,2024-06-11 08:09:26,NaT,False,True,NaN
205,2024,6,RU,PRD,Done,SECURITY,CnC(C_C)_Request to block the IPs_20240605_0854,mohammed,mohammed,None,2024-06-05 16:45:54+09,2024-06-07 18:40:48,2024-06-07 18:40:48+09:00,False,True,202406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17322,2024,4,RU,PRD,Done,FW,러시아 ISS 방화벽 요청,박기완/클라우드운영센터(협력사),박지민/CCS글로벌전개팀,None,2023-01-26 06:38:50+09,2023-03-14 03:54:23+09,2023-03-14 03:54:23+09:00,False,True,202303
17446,2024,4,RU,PRD,Done,NETWORK,[요청] RU CCS SBS PRD Network 상태 및 Infra Issue 확...,박기완/클라우드운영센터(협력사),서정현/CCS플랫폼팀,None,2023-01-19 04:36:11+09,2023-01-19 06:14:32+09,2023-01-19 06:14:32+09:00,False,True,202301
17512,2024,4,RU,PRD,In-progress,FW,RU LMS 운영계 방화벽 해제 요청 - Mobis,박기완/클라우드운영센터(협력사),Arushanyan Surbine,None,2023-01-17 06:31:42+09,2023-02-01 05:17:02+09,2023-02-01 05:17:02+09:00,False,True,202302
17646,2024,4,RU,PRD,Done,OS,[RU] 중복 IP관련 문의 건,임정현/클라우드운영센터(협력사),방주희/CCS제어팀,None,2023-01-12 06:34:16+09,2023-01-16 04:50:43+09,2023-01-16 04:50:43+09:00,False,True,202301
17756,2024,4,RU,PRD,Done,SECURITY,[ccsrucdmss01 VM] Connection Issue,Ahmed/클라우드운영센터(협력사),Arushanyan Surbine,None,2023-01-09 07:48:06+09,2023-01-10 05:38:13+09,2023-01-10 05:38:13+09:00,False,True,202301

In [100]:
if len(regions) > 1: # == 'All':
    # Data
    rows = df_filtered.loc[df_filtered['Date'].isin([ym2])]
    
    data, pivot, total = getPivotTable_event(rows, month, regions)
    source = pivot
    
    # if incompleted == 0:
    #     chart = getPieChart(source)
    # else:
    chart = getStackedHBarChart1(source)
    chart.save(f'./charts/cm_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

# Chart - 라인 차트


# df_filtered_count['Date'] = df_filtered_count['Date'].astype(str)
# print(df_filtered_count.info())
# print(df_filtered_count)
# df_filtered_count['Year'] =  df_filtered_count['Date'].str[:4]
# df_filtered_count['Month'] =  df_filtered_count['Date'].str[4:]
# df_filtered_count['new'] = pd.to_datetime(df_filtered_count['Year'] + df_filtered_count['Month'], format='%Y%m').dt.strftime('%Y%m')
# df_filtered_count['Date'] = df_filtered_count['new']




# df_filtered_count.columns = ['Date','합계']
# df_filtered_count['합계'] = df_filtered_count['합계'].astype(int)
# df_filtered_count.reset_index(drop=True, inplace=True)

# df_filtered_count = df_filtered_count[['Date', '합계']].rename(columns={'index': 'Date'})
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# print(df_filtered['Date'])
# data = counter_3d(df_filtered)
# ymym='202310'
print(df_filtered_count)
# data = counter_3d(df_filtered_count,ym)

# today = datetime.date.today()
# current_date = today
# start_date = current_date - timedelta(days=365)
# print(current_date)
# print(start_date)
# df_filtered_count['Date'] = pd.to_datetime(df_filtered_count['Date'])
# print(df_filtered_count['Date'])
tempList = ['202201','202202','202203','202204','202205','202206','202207','202208','202209','202210','202211','202212',
           '202301', '202302','202303','202304','202305','202306','202307','202308','202309','202310','202311','202312',
           '202401','202402','202403','202404','202405','202406','202407','202408','202409','202410','202411','202412']

realList = []

print(ym2)
ym_index = tempList.index(ym2)

print("ym_index",ym_index)

for i in tempList[ym_index:ym_index-13:-1]:
    realList.append(i)

print(realList)    
    
recent = df_filtered_count[df_filtered_count['Date'].astype(str).isin(realList)]
print(recent)
                                           
chart = getLineChart_new(recent)
# chart = getLineChart2(df_filtered2, month)
chart.save(f'./charts/cm_{regions}_{y}_{m}_{d}_2.png')

      Date  합계
0   202301   3
1   202302  26
2   202303  11
3   202304  20
4   202305  13
5   202306  14
6   202307  20
7   202308  34
8   202309  11
9   202310  40
10  202311  31
11  202312  18
12  202401  14
13  202402  54
14  202403  11
15  202404  31
16  202405  36
17  202406   8
202405
ym_index 28
['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305']
      Date  합계
4   202305  13
5   202306  14
6   202307  20
7   202308  34
8   202309  11
9   202310  40
10  202311  31
11  202312  18
12  202401  14
13  202402  54
14  202403  11
15  202404  31
16  202405  36

In [101]:
print(ym2)
rows = df_filtered[df_filtered['Date'].isin([ym2])]

print(rows)
data, pivot, total = getPivotTable_event(rows, month, regions)
source = flatten_5d(data)
print(source)
chart = get_1_5_HBarChart(source)
chart.save(f'./charts/cm_{regions}_{y}_{m}_{d}_1.png')
# chart = get_1_5_StackedHBarChart(source)

# chart = getLineChart2(df_filtered2, month)
# chart.show()
# chart.save(f'./charts/cm_{region}_{y}_{m}_{d}_2.png')

202405
         년  월  리전  테넌트  진행상태 Work Type  \
551   2024  5  RU  PRD  Done  SECURITY
600   2024  5  RU  PRD  Done  SECURITY
653   2024  5  RU  PRD  Done  SECURITY
745   2024  5  RU  PRD  Done  SECURITY
809   2024  5  RU  PRD  Done  SECURITY
847   2024  5  RU  PRD  Done        FW
865   2024  5  RU  PRD  Done  SECURITY
880   2024  5  RU  PRD  Done        OS
940   2024  5  RU  PRD  Done  SECURITY
1003  2024  5  RU  PRD  Done  SECURITY
1021  2024  5  RU  PRD  Done        FW
1098  2024  5  RU  PRD  Done  SECURITY
1162  2024  5  RU  PRD  Done  SECURITY
1242  2024  5  RU  PRD  Done  SECURITY
1260  2024  5  RU  PRD  Done        OS
1302  2024  5  RU  PRD  Done  SECURITY
1325  2024  5  RU  PRD  Done   NETWORK
1437  2024  5  RU  PRD  Done  SECURITY
1456  2024  5  RU  PRD  Done        FW
1485  2024  5  RU  PRD  Done  SECURITY
1541  2024  5  RU  PRD  Done  SECURITY
1659  2024  5  RU  PRD  Done  SECURITY
1714  2024  5  RU  PRD  Done  SECURITY
1785  2024  5  RU  PRD  Done  SECURITY
1832  2024  4  RU  PRD  Done  SECURITY
1857  2024  4  RU  PRD  Done   NETWORK
1915  2024  4  RU  PRD  Done  SECURITY
1964  2024  4  RU  PRD  Done  SECURITY
1991  2024  4  RU  PRD  Done        FW
2002  2024  4  RU  PRD  Done  SECURITY
2067  2024  4  RU  PRD  Done        FW
2121  2024  4  RU  PRD  Done        FW
3336  2024  4  RU  PRD  Done        DB
3884  2024  4  RU  PRD  Done        FW
4008  2024  4  RU  PRD  Done        DB
5124  2024  4  RU  PRD  Done        DB

                                                   제목           assignee  \
551   CnC(C_C)_Request to block the IPs_20240529_0926           mohammed
600   CnC(C_C)_Request to block the IPs_20240528_1452               Saju
653   CnC(C_C)_Request to block the IPs_20240527_1432               Saju
745   CnC(C_C)_Request to block the IPs_20240524_1024                Ram
809   CnC(C_C)_Request to block the IPs_20240523_0831                Ram
847                                [RU] SBS 방화벽 해제 요청  강진구/클라우드운영센터(협력사)
865   CnC(C_C)_Request to block the IPs_20240522_1013           mohammed
880                                     [러시아] OS 문의 건  홍성현/클라우드운영센터(협력사)
940   CnC(C_C)_Request to block the IPs_20240521_0836           mohammed
1003  CnC(C_C)_Request to block the IPs_20240520_0818           mohammed
1021                               [RU] LMS 방화벽 해제 요청  강진구/클라우드운영센터(협력사)
1098  CnC(C_C)_Request to block the IPs_20240517_0901   DHANDAPANI A/GDC
1162  CnC(C_C)_Request to block the IPs_20240516_1014   DHANDAPANI A/GDC
1242  CnC(C_C)_Request to block the IPs_20240514_0932   DHANDAPANI A/GDC
1260                               러시아 VM OS버전 조사요청 건  홍성현/클라우드운영센터(협력사)
1302  CnC(C_C)_Request to block the IPs_20240513_1400               Saju
1325                               [RU] LMS 방화벽 해제 요청  박진홍/클라우드운영센터(협력사)
1437  CnC(C_C)_Request to block the IPs_20240509_0836                Ram
1456                                   [RU] 방화벽 해제 요청  박진홍/클라우드운영센터(협력사)
1485  CnC(C_C)_Request to block the IPs_20240508_0938                Ram
1541  CnC(C_C)_Request to block the IPs_20240507_0856   DHANDAPANI A/GDC
1659  CnC(C_C)_Request to block the IPs_20240503_1007           mohammed
1714  CnC(C_C)_Request to block the IPs_20240502_0821           mohammed
1785  CnC(C_C)_Request to block the IPs_20240430_1419               Saju
1832  CnC(C_C)_Request to block the IPs_20240429_1514               Saju
1857                                    센터 IP 대역 문의 건  남원우/클라우드운영센터(협력사)
1915  CnC(C_C)_Request to block the IPs_20240426_1522               Saju
1964  CnC(C_C)_Request to block the IPs_20240425_0826           mohammed
1991                                 [요청] 방화벽 오픈 요청 건  박진홍/클라우드운영센터(협력사)
2002  CnC(C_C)_Request to block the IPs_20240424_0806           mohammed
2067                           러시아 권역 방화벽 오픈 요청 드립니다.  강진구/클라우드운영센터(협력사)
2121            러시아 CCS 권역 장비에 대해서 방화벽 정책 만료 기한 확인 요청  남원우/클라우드운영센터(협력사)
3336                      [API G/W] 러시아 운영계 레디스 설치 요청  송윤진/클라우드운영센터(협력사)
3884                          [RU] 러시아 방화벽 오픈 요청드립니다.  박진홍/클라우드운영센터(협력사)
4008                           [긴급] API G/W 레디스 설치 요청  송윤진/클라우드운영센터(협력사)
5124                          [긴급] 레디스 버전 업그레이드 지원 요청  송윤진/클라우드운영센터(협력사)

                     reporter sync_status           tk_created_at  \
551                  mohammed        None  2024-05-29 18:15:17+09
600                      Saju        None  2024-05-28 18:08:45+09
653                      Saju        None  2024-05-27 18:16:01+09
745   RAM SENTHIL KUMAR R/GDC        None  2024-05-24 17:30:03+09
809   RAM SENTHIL KUMAR R/GDC        None  2024-05-23 18:40:19+09
847                홍금비/CCS제어팀        None  2024-05-23 10:04:59+09
865                  mohammed        None  2024-05-22 18:00:16+09
880                방주희/CCS제어팀        None  2024-05-22 15:31:42+09
940                  mohammed        None  2024-05-21 17:36:59+09
1003                 mohammed        None  2024-05-20 20:19:22+09
1021       이규남 책임연구원 CCS서버개발팀        None  2024-05-20 15:24:06+09
1098         DHANDAPANI A/GDC        None  2024-05-17 21:16:54+09
1162         DHANDAPANI A/GDC        None  2024-05-16 17:35:20+09
1242         DHANDAPANI A/GDC        None  2024-05-14 20:54:47+09
1260        최원석/클라우드운영센터(협력사)        None  2024-05-14 12:28:48+09
1302                     Saju        None  2024-05-13 20:34:22+09
1325        백승훈 연구원 전자네트워크시험팀        None  2024-05-13 14:38:00+09
1437  RAM SENTHIL KUMAR R/GDC        None  2024-05-09 17:33:20+09
1456              박유나/CCS플랫폼팀        None  2024-05-09 13:05:02+09
1485  RAM SENTHIL KUMAR R/GDC        None  2024-05-08 17:51:33+09
1541         DHANDAPANI A/GDC        None  2024-05-07 18:30:18+09
1659                 mohammed        None  2024-05-03 16:32:27+09
1714                 mohammed        None  2024-05-02 16:45:59+09
1785                     Saju        None  2024-04-30 16:55:52+09
1832                     Saju        None  2024-04-29 18:43:33+09
1857               방주희/CCS제어팀        None  2024-04-29 13:44:06+09
1915                     Saju        None  2024-04-26 17:08:07+09
1964                 mohammed        None  2024-04-25 17:35:07+09
1991              유애리/CCS플랫폼팀        None  2024-04-25 09:21:26+09
2002                 mohammed        None  2024-04-24 17:15:31+09
2067        권선호/CCS보안운영팀(협력사)        None  2024-04-23 13:49:58+09
2121        김대환/CCS보안운영팀(협력사)        None  2024-04-22 14:54:04+09
3336              정다은/CCS플랫폼팀        None  2024-03-25 11:01:21+09
3884            강민구/CCS신뢰성개발팀        None  2024-03-11 02:54:40+09
4008              정다은/CCS플랫폼팀        None  2024-03-07 01:17:04+09
5124            김정환/서비스플랫폼개발팀        None  2024-02-02 05:35:41+09

               tk_updated_at            tk_resolved_at  is_draft  is_use  \
551      2024-06-04 17:28:07 2024-05-30 13:16:59+09:00     False    True
600      2024-06-01 15:44:59 2024-05-29 08:56:30+09:00     False    True
653      2024-06-03 19:26:57 2024-05-28 16:57:06+09:00     False    True
745      2024-06-03 19:27:30 2024-05-27 14:20:02+09:00     False    True
809      2024-05-24 17:30:15 2024-05-24 14:52:15+09:00     False    True
847      2024-05-29 15:00:06 2024-05-29 15:00:06+09:00     False    True
865      2024-05-29 18:15:36 2024-05-23 11:56:16+09:00     False    True
880   2024-05-22 15:56:26+09 2024-05-22 15:56:26+09:00     False    True
940      2024-05-22 18:00:36 2024-05-21 18:01:14+09:00     False    True
1003     2024-05-21 18:01:40 2024-05-21 18:01:40+09:00     False    True
1021     2024-05-24 14:47:19 2024-05-24 14:47:19+09:00     False    True
1098     2024-05-21 18:17:58 2024-05-21 18:17:58+09:00     False    True
1162     2024-05-21 18:18:04 2024-05-21 18:17:11+09:00     False    True
1242     2024-05-21 18:18:10 2024-05-21 18:16:45+09:00     False    True
1260     2024-05-17 09:34:13 2024-05-17 09:34:13+09:00     False    True
1302     2024-05-14 13:13:12 2024-05-14 13:13:12+09:00     False    True
1325     2024-05-30 09:38:48 2024-05-30 09:38:48+09:00     False    True
1437     2024-05-23 18:46:07 2024-05-14 13:13:42+09:00     False    True
1456     2024-05-20 13:16:13 2024-05-20 13:16:13+09:00     False    True
1485     2024-05-14 13:14:08 2024-05-14 13:14:08+09:00     False    True
1541     2024-05-22 10:01:29 2024-05-22 10:01:29+09:00     False    True
1659     2024-05-08 14:21:27 2024-05-08 14:21:27+09:00     False    True
1714     2024-05-20 20:19:43 2024-05-08 14:18:57+09:00     False    True
1785     2024-05-01 13:37:53 2024-05-01 13:37:53+09:00     False    True
1832     2024-05-01 13:38:29 2024-05-01 13:38:29+09:00     False    True
1857     2024-05-01 13:57:02 2024-05-01 13:57:02+09:00     False    True
1915     2024-05-01 13:43:09 2024-05-01 13:43:09+09:00     False    True
1964     2024-05-01 13:44:37 2024-05-01 13:44:37+09:00     False    True
1991     2024-05-01 13:58:35 2024-05-01 13:58:35+09:00     False    True
2002     2024-05-02 16:46:19 2024-05-01 13:45:59+09:00     False    True
2067     2024-05-02 08:00:25 2024-05-02 08:00:25+09:00     False    True
2121     2024-05-01 13:56:25 2024-05-01 13:56:25+09:00     False    True
3336     2024-05-17 10:35:57 2024-05-17 10:35:57+09:00     False    True
3884     2024-05-01 13:57:46 2024-05-01 13:57:23+09:00     False    True
4008     2024-05-10 10:17:24 2024-05-10 10:17:24+09:00     False    True
5124     2024-05-07 10:13:19 2024-05-07 10:13:18+09:00     False    True

        Date
551   202405
600   202405
653   202405
745   202405
809   202405
847   202405
865   202405
880   202405
940   202405
1003  202405
1021  202405
1098  202405
1162  202405
1242  202405
1260  202405
1302  202405
1325  202405
1437  202405
1456  202405
1485  202405
1541  202405
1659  202405
1714  202405
1785  202405
1832  202405
1857  202405
1915  202405
1964  202405
1991  202405
2002  202405
2067  202405
2121  202405
3336  202405
3884  202405
4008  202405
5124  202405
    리전  진행상태 Work Type
0   RU  Done  SECURITY
1   RU  Done  SECURITY
2   RU  Done  SECURITY
3   RU  Done  SECURITY
4   RU  Done  SECURITY
5   RU  Done        FW
6   RU  Done  SECURITY
7   RU  Done        OS
8   RU  Done  SECURITY
9   RU  Done  SECURITY
10  RU  Done        FW
11  RU  Done  SECURITY
12  RU  Done  SECURITY
13  RU  Done  SECURITY
14  RU  Done        OS
15  RU  Done  SECURITY
16  RU  Done   NETWORK
17  RU  Done  SECURITY
18  RU  Done        FW
19  RU  Done  SECURITY
20  RU  Done  SECURITY
21  RU  Done  SECURITY
22  RU  Done  SECURITY
23  RU  Done  SECURITY
24  RU  Done  SECURITY
25  RU  Done   NETWORK
26  RU  Done  SECURITY
27  RU  Done  SECURITY
28  RU  Done        FW
29  RU  Done  SECURITY
30  RU  Done        FW
31  RU  Done        FW
32  RU  Done        DB
33  RU  Done        FW
34  RU  Done        DB
35  RU  Done        DB

In [102]:
# Document
# document.add_paragraph('요청 관리', style='List Number')
document.add_heading('요청 관리', level=1) 
# document.add_paragraph(f'총 {completed+incompleted}건 (완료)', style='List Bullet')
document.add_paragraph(f'총 {completed}건 (완료)', style='List Bullet')
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/cm_{regions}_{y}_{m}_{d}_2.png')
document.add_paragraph(f'상세 현황(워크타입별 분류)', style='List Bullet')
document.add_picture(f'./charts/cm_{regions}_{y}_{m}_{d}_1.png')
# if region == 'All':
#     # document.add_picture(f'./charts/cm_{region}_{y}_{m}_{d}_1.png')
#     document.add_picture(f'./charts/cm_{region}_{y}_{m}_{d}_2.png')
# else:
#     pass
document.add_page_break()

In [103]:
document.save('demo.docx')

## (신규포탈)자산관리(VM)(자동화버전)

In [104]:
data_endpoint = 'http://10.11.66.85:8080/assets/instances/aggregation/list' 
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [105]:
df = pd.DataFrame(result['data'])

In [106]:
print(df)

        id  year month day region az   tenant customer type     status  count  \
0     1465  2024    06  11     CN  1  NEW-STG     None   VM  COMPLETED    228
1     1484  2024    06  11     SG  1      STG     None   VM  COMPLETED    728
2     1483  2024    06  11     SG  1      PRD     None   VM  COMPLETED    993
3     1482  2024    06  11     RU  1      STG     None   VM  COMPLETED    119
4     1481  2024    06  11     RU  1      PRD     None   VM  COMPLETED    162
...    ...   ...   ...  ..    ... ..      ...      ...  ...        ...    ...
1479   617  2024    03  01     KR  1      PRD      CCS   VM  COMPLETED   1708
1480   616  2024    02  01     NA  2      STG      CCS   VM  COMPLETED    607
1481   615  2024    02  01     NA  2      PRD      CCS   VM  COMPLETED    907
1482   614  2024    02  01     SG  1      DEV      CCS   VM  COMPLETED      0
1483   613  2024    02  01     SG  1      STG      CCS   VM  COMPLETED    706

      is_draft  is_use updater       created_at_str       updated_at_str
0        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
1        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
2        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
3        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
4        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
...        ...     ...     ...                  ...                  ...
1479     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1480     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1481     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1482     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1483     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53

[1484 rows x 16 columns]

In [107]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'type', 'status', 'count', 'is_draft', 'is_use', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [108]:
df = df[['year', 'month', 'day', 'region', 'az', 'tenant', 'type', 'status', 'count', 'is_draft', 'is_use']]

In [109]:
# description
df.columns = [ '년', '월', '일', '리전', 'AZ', '테넌트', '유형', '진행상태', 'count', 'is_draft', 'is_use']

In [110]:
df.head()

      년   월   일  리전 AZ      테넌트  유형       진행상태  count  is_draft  is_use
0  2024  06  11  CN  1  NEW-STG  VM  COMPLETED    228     False    True
1  2024  06  11  SG  1      STG  VM  COMPLETED    728     False    True
2  2024  06  11  SG  1      PRD  VM  COMPLETED    993     False    True
3  2024  06  11  RU  1      STG  VM  COMPLETED    119     False    True
4  2024  06  11  RU  1      PRD  VM  COMPLETED    162     False    True

In [111]:
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
print(df_filtered)

df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].str.contains('PRD')]
print(df_filtered)

         년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  10  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  09  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  08  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  07  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 11 columns]
         년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  10  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  09  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  08  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  07  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 11 columns]

In [112]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].str.contains('PRD')]
print(df_filtered)
last_day = str(last_day)
print(df['일']==last_day)
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].str.contains('PRD') & df['년'].isin([year])
                         & df['월'].isin([month]) & df['일'].isin([last_day])]

print(df_filtered_current)

# Pivoting
# pivot, total = getPivotTable(df, month, year)

# df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# completed = len(df_completed)

# Pivoting
pivot, total = getPivotTable(df_filtered_current)

# df_ = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
total_instance = df_filtered_current['count'].sum()

         년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  10  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  09  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  08  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  07  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 11 columns]
0       False
1       False
2       False
3       False
4       False
        ...
1479    False
1480    False
1481    False
1482    False
1483    False
Name: 일, Length: 1484, dtype: bool
        년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
226  2024  05  31  RU  1  PRD  VM  COMPLETED    162     False    True

In [113]:
print(int(total_instance))
# print(df_filtered['count'].sum())

162

In [114]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    # Data
    # rows = df_filtered.loc[(df_filtered['월']==month) & (df_filtered['년']==y)]
    # data, pivot, total = getPivotTable_event(rows, month, region_list)
    source = pivot
       
    # Chart
    chart = getPieChart(source)
    chart.save(f'./charts/vm_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

In [115]:
df_filtered

         년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  10  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  09  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  08  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  07  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 11 columns]

In [116]:
# Chart - 라인 차트
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
print(ym2)
print("xxx",df_filtered)

df_filtered['날짜'] = pd.to_datetime(df_filtered['년'].astype(str) + '-' + 
                                   df_filtered['월'].astype(str).str.zfill(2) + '-' +
                                   df_filtered['일'].astype(str).str.zfill(2))
last_days = df_filtered.groupby(['년','월'])['날짜'].max()
df_filtered = df_filtered[df_filtered['날짜'].isin(last_days)]
# df_filtered = df_filtered.sort_values(by='날짜').groupby(['년','월']).tail(1)
print("yyy", df_filtered)

data = counter_3d_vm(df_filtered,ym2)
print("data",data)
chart = getLineChart2s(data)
chart.save(f'./charts/vm_{regions}_{y}_{m}_{d}_2.png')

202405
xxx          년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  10  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  09  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  08  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  07  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 11 columns]
yyy          년   월   일  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use  \
4     2024  06  11  RU  1  PRD  VM  COMPLETED    162     False    True
226   2024  05  31  RU  1  PRD  VM  COMPLETED    162     False    True
815   2024  02  01  RU  1  PRD  VM  COMPLETED     84     False    True
843   2024  01  01  RU  1  PRD  VM  COMPLETED     84     False    True
871   2023  12  01  RU  1  PRD  VM  COMPLETED     84     False    True
899   2023  11  01  RU  1  PRD  VM  COMPLETED     84     False    True
927   2023  10  01  RU  1  PRD  VM  COMPLETED     84     False    True
953   2023  09  01  RU  1  PRD  VM  COMPLETED     84     False    True
979   2023  08  01  RU  1  PRD  VM  COMPLETED     84     False    True
1005  2023  07  01  RU  1  PRD  VM  COMPLETED     84     False    True
1031  2023  06  01  RU  1  PRD  VM  COMPLETED     83     False    True
1057  2023  05  01  RU  1  PRD  VM  COMPLETED     82     False    True
1083  2023  04  01  RU  1  PRD  VM  COMPLETED     79     False    True
1109  2023  03  01  RU  1  PRD  VM  COMPLETED     79     False    True
1135  2023  02  01  RU  1  PRD  VM  COMPLETED     79     False    True
1159  2023  01  01  RU  1  PRD  VM  COMPLETED     79     False    True
1183  2022  12  01  RU  1  PRD  VM  COMPLETED     79     False    True
1207  2022  11  01  RU  1  PRD  VM  COMPLETED     78     False    True
1231  2022  10  01  RU  1  PRD  VM  COMPLETED     78     False    True
1252  2022  09  01  RU  1  PRD  VM  COMPLETED     78     False    True
1273  2022  08  01  RU  1  PRD  VM  COMPLETED     86     False    True
1294  2022  07  01  RU  1  PRD  VM  COMPLETED     86     False    True
1315  2022  06  01  RU  1  PRD  VM  COMPLETED     96     False    True
1334  2022  05  01  RU  1  PRD  VM  COMPLETED     96     False    True
1353  2022  04  01  RU  1  PRD  VM  COMPLETED     96     False    True
1372  2022  03  01  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  01  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  01  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  01  RU  1  PRD  VM  COMPLETED     85     False    True

             날짜
4    2024-06-11
226  2024-05-31
815  2024-02-01
843  2024-01-01
871  2023-12-01
899  2023-11-01
927  2023-10-01
953  2023-09-01
979  2023-08-01
1005 2023-07-01
1031 2023-06-01
1057 2023-05-01
1083 2023-04-01
1109 2023-03-01
1135 2023-02-01
1159 2023-01-01
1183 2022-12-01
1207 2022-11-01
1231 2022-10-01
1252 2022-09-01
1273 2022-08-01
1294 2022-07-01
1315 2022-06-01
1334 2022-05-01
1353 2022-04-01
1372 2022-03-01
1391 2022-02-01
1410 2022-01-01
1429 2024-04-01
1459 2024-03-01
       년   월  count
0   2022  01    108
1   2022  02     96
2   2022  03     97
3   2022  04     96
4   2022  05     96
5   2022  06     96
6   2022  07     86
7   2022  08     86
8   2022  09     78
9   2022  10     78
10  2022  11     78
11  2022  12     79
12  2023  01     79
13  2023  02     79
14  2023  03     79
15  2023  04     79
16  2023  05     82
17  2023  06     83
18  2023  07     84
19  2023  08     84
20  2023  09     84
21  2023  10     84
22  2023  11     84
23  2023  12     84
24  2024  01     84
25  2024  02     84
26  2024  03     85
27  2024  04     85
28  2024  05    162
29  2024  06    162
       년   월  count    Date
0   2022  01    108  202201
1   2022  02     96  202202
2   2022  03     97  202203
3   2022  04     96  202204
4   2022  05     96  202205
5   2022  06     96  202206
6   2022  07     86  202207
7   2022  08     86  202208
8   2022  09     78  202209
9   2022  10     78  202210
10  2022  11     78  202211
11  2022  12     79  202212
12  2023  01     79  202301
13  2023  02     79  202302
14  2023  03     79  202303
15  2023  04     79  202304
16  2023  05     82  202305
17  2023  06     83  202306
18  2023  07     84  202307
19  2023  08     84  202308
20  2023  09     84  202309
21  2023  10     84  202310
22  2023  11     84  202311
23  2023  12     84  202312
24  2024  01     84  202401
25  2024  02     84  202402
26  2024  03     85  202403
27  2024  04     85  202404
28  2024  05    162  202405
29  2024  06    162  202406
      Date  count
0   202201    108
1   202202     96
2   202203     97
3   202204     96
4   202205     96
5   202206     96
6   202207     86
7   202208     86
8   202209     78
9   202210     78
10  202211     78
11  202212     79
12  202301     79
13  202302     79
14  202303     79
15  202304     79
16  202305     82
17  202306     83
18  202307     84
19  202308     84
20  202309     84
21  202310     84
22  202311     84
23  202312     84
24  202401     84
25  202402     84
26  202403     85
27  202404     85
28  202405    162
29  202406    162 <class 'pandas.core.frame.DataFrame'>
df_extract       Date
0   202201
1   202202
2   202203
3   202204
4   202205
5   202206
6   202207
7   202208
8   202209
9   202210
10  202211
11  202212
12  202301
13  202302
14  202303
15  202304
16  202305
17  202306
18  202307
19  202308
20  202309
21  202310
22  202311
23  202312
24  202401
25  202402
26  202403
27  202404
28  202405
29  202406
df_index ['202201', '202202', '202203', '202204', '202205', '202206', '202207', '202208', '202209', '202210', '202211', '202212', '202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405', '202406']
202405
ym_index 28
data       Date  count
16  202305     82
17  202306     83
18  202307     84
19  202308     84
20  202309     84
21  202310     84
22  202311     84
23  202312     84
24  202401     84
25  202402     84
26  202403     85
27  202404     85
28  202405    162

In [117]:
# Document
# document.add_paragraph('자산 관리(vm)', style='List Number')
document.add_heading('자산 관리(vm)', level=1) 
document.add_paragraph(f'총 {int(total_instance)}인스턴스 (운영계)', style='List Bullet')

if len(regions) > 1: # == 'All':
    document.add_picture(f'./charts/vm_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

# Document
# addTable(df_filtered, regex, month)
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/vm_{regions}_{y}_{m}_{d}_2.png')
document.add_page_break()

In [118]:
document.save('demo.docx')

## (신규포탈)자산관리(DB)(완료)

In [119]:
data_endpoint = 'http://10.11.66.85:8080/assets/DB/aggregation/list' 
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [120]:
df = pd.DataFrame(result['data'])

In [121]:
print(df)

        id  year month day region az tenant customer      type     status  \
0     2653  2024    05  01     SG  1    STG      CCS     MARIA  COMPLETED
1     2557  2024    05  01     EU  2    STG      CCS  POSTGRES  COMPLETED
2     2558  2024    05  01     NA  1    STG      CCS  POSTGRES  COMPLETED
3     2559  2024    05  01     EU  2    PRD      CCS     REDIS  COMPLETED
4     2560  2024    05  01     EU  1    STG      CCS     MONGO  COMPLETED
...    ...   ...   ...  ..    ... ..    ...      ...       ...        ...
2647   188  2022    02  01     RU  1    STG      CCS     MARIA  COMPLETED
2648   189  2022    02  01     RU  1    STG      CCS     REDIS  COMPLETED
2649   190  2022    02  01     RU  1    STG      CCS     MONGO  COMPLETED
2650   191  2022    02  01     RU  1    DEV      CCS  POSTGRES  COMPLETED
2651   192  2022    02  01     RU  1    DEV      CCS    TIBERO  COMPLETED

      count  is_draft  is_use updater       created_at_str  \
0         0     False    True   test2  2024-06-04 13:21:00
1        14     False    True   test2  2024-06-04 13:21:00
2         9     False    True   test2  2024-06-04 13:21:00
3        33     False    True   test2  2024-06-04 13:21:00
4        13     False    True   test2  2024-06-04 13:21:00
...     ...       ...     ...     ...                  ...
2647      0     False    True     김범준  2024-04-04 15:29:31
2648      0     False    True     김범준  2024-04-04 15:29:31
2649      0     False    True     김범준  2024-04-04 15:29:31
2650      1     False    True     김범준  2024-04-04 15:29:31
2651      0     False    True     김범준  2024-04-04 15:29:31

           updated_at_str
0     2024-06-04 13:21:00
1     2024-06-04 13:21:00
2     2024-06-04 13:21:00
3     2024-06-04 13:21:00
4     2024-06-04 13:21:00
...                   ...
2647  2024-04-04 15:29:31
2648  2024-04-04 15:29:31
2649  2024-04-04 15:29:31
2650  2024-04-04 15:29:31
2651  2024-04-04 15:29:31

[2652 rows x 16 columns]

In [122]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'type', 'status', 'count', 'is_draft', 'is_use', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [123]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'type', 'status', 'count', 'is_draft', 'is_use']]

In [124]:
# description
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '유형', 'status', 'count', 'is_draft', 'is_use']

In [125]:
df.head()

      년   월  리전 AZ  테넌트        유형     status  count  is_draft  is_use
0  2024  05  SG  1  STG     MARIA  COMPLETED      0     False    True
1  2024  05  EU  2  STG  POSTGRES  COMPLETED     14     False    True
2  2024  05  NA  1  STG  POSTGRES  COMPLETED      9     False    True
3  2024  05  EU  2  PRD     REDIS  COMPLETED     33     False    True
4  2024  05  EU  1  STG     MONGO  COMPLETED     13     False    True

In [126]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

# Pivoting
# pivot, total = getPivotTable(df, month, year)

# df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# completed = len(df_completed)

# Pivoting
# pivot, total = getPivotTable(df_filtered, month)
pivot2, total = getPivotTable2(df_filtered_current)
pivot2 = pivot2.reset_index()
print(pivot2, total)

df_ = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
total_instance = df_['count'].sum()

리전        유형  RU  합계    비중
0      REDIS   6   6  46.2
1   POSTGRES   4   4  30.8
2      MONGO   3   3  23.1
3      MARIA   0   0   0.0
4      Mongo   0   0   0.0
5     TIBERO   0   0   0.0 13

In [127]:
print(total_instance)
print(month)
print(df_)

13
05
       년   월  리전 AZ  테넌트        유형     status  count  is_draft  is_use
17  2024  05  RU  1  PRD     REDIS  COMPLETED      6     False    True
32  2024  05  RU  1  PRD  POSTGRES  COMPLETED      4     False    True
59  2024  05  RU  1  PRD     MONGO  COMPLETED      3     False    True
87  2024  05  RU  1  PRD    TIBERO  COMPLETED      0     False    True
88  2024  05  RU  1  PRD     MARIA  COMPLETED      0     False    True
89  2024  05  RU  1  PRD     Mongo  COMPLETED      0     False    True
93  2024  05  RU  1  PRD    TIBERO  COMPLETED      0     False    True

In [128]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    # Data
    # rows = df_filtered.loc[(df_filtered['월']==month) & (df_filtered['년']==y)]
    # data, pivot, total = getPivotTable_event(rows, month, region_list)
    pivot, total = getPivotTable(df_filtered_current)
    source = pivot
    
    print("source", source)
    
    # Chart
    chart = getPieChart(source)
    chart.save(f'./charts/db_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

source = df_filtered
print(source)
source['Date'] = pd.to_datetime(source['년'].astype(str) + source['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
index_zero = source[source['count']==0].index
print(index_zero)
source.drop(index_zero, inplace=True)
    
# data = counter_3d(source)
# print("soruce:",source['Date'])

data = counter_3d_db(source,ym2)

chart = getStackedVBarChart1(data)
chart.save(f'./charts/db_{regions}_{y}_{m}_{d}_2.png')

         년   월  리전 AZ  테넌트        유형     status  count  is_draft  is_use
17    2024  05  RU  1  PRD     REDIS  COMPLETED      6     False    True
32    2024  05  RU  1  PRD  POSTGRES  COMPLETED      4     False    True
59    2024  05  RU  1  PRD     MONGO  COMPLETED      3     False    True
87    2024  05  RU  1  PRD    TIBERO  COMPLETED      0     False    True
88    2024  05  RU  1  PRD     MARIA  COMPLETED      0     False    True
...    ...  ..  .. ..  ...       ...        ...    ...       ...     ...
2640  2022  02  RU  1  PRD  POSTGRES  COMPLETED     10     False    True
2641  2022  02  RU  1  PRD    TIBERO  COMPLETED      0     False    True
2642  2022  02  RU  1  PRD     MARIA  COMPLETED      0     False    True
2643  2022  02  RU  1  PRD     REDIS  COMPLETED      3     False    True
2644  2022  02  RU  1  PRD     MONGO  COMPLETED      0     False    True

[157 rows x 10 columns]
Int64Index([  87,   88,   89,   93,  131,  132,  286,  287,  391,  392,  496,
             497,  601,  602,  706,  707,  816,  817,  901,  902,  976,  977,
            1056, 1057, 1136, 1137, 1211, 1212, 1291, 1292, 1293, 1371, 1372,
            1373, 1467, 1468, 1469, 1554, 1555, 1556, 1643, 1644, 1730, 1731,
            1817, 1818, 1904, 1905, 1909, 1994, 1995, 1999, 2082, 2083, 2087,
            2173, 2174, 2178, 2261, 2262, 2263, 2267, 2355, 2356, 2357, 2361,
            2450, 2451, 2452, 2456, 2536, 2537, 2539, 2641, 2642, 2644],
           dtype='int64')
         년   월  리전 AZ  테넌트        유형     status  count  is_draft  is_use  \
17    2024  05  RU  1  PRD     REDIS  COMPLETED      6     False    True
32    2024  05  RU  1  PRD  POSTGRES  COMPLETED      4     False    True
59    2024  05  RU  1  PRD     MONGO  COMPLETED      3     False    True
130   2024  04  RU  1  PRD  POSTGRES  COMPLETED      4     False    True
133   2024  04  RU  1  PRD     MONGO  COMPLETED      3     False    True
...    ...  ..  .. ..  ...       ...        ...    ...       ...     ...
2421  2024  03  RU  1  PRD     MONGO  COMPLETED      3     False    True
2535  2022  01  RU  1  PRD  POSTGRES  COMPLETED     10     False    True
2538  2022  01  RU  1  PRD     REDIS  COMPLETED      3     False    True
2640  2022  02  RU  1  PRD  POSTGRES  COMPLETED     10     False    True
2643  2022  02  RU  1  PRD     REDIS  COMPLETED      3     False    True

        Date
17    202405
32    202405
59    202405
130   202404
133   202404
...      ...
2421  202403
2535  202201
2538  202201
2640  202202
2643  202202

[81 rows x 11 columns]
        Date        유형  count
17    202405     REDIS      6
32    202405  POSTGRES      4
59    202405     MONGO      3
130   202404  POSTGRES      4
133   202404     MONGO      3
...      ...       ...    ...
2421  202403     MONGO      3
2535  202201  POSTGRES     10
2538  202201     REDIS      3
2640  202202  POSTGRES     10
2643  202202     REDIS      3

[81 rows x 3 columns] <class 'pandas.core.frame.DataFrame'>
df_extract         Date
17    202405
32    202405
59    202405
130   202404
133   202404
...      ...
2421  202403
2535  202201
2538  202201
2640  202202
2643  202202

[81 rows x 1 columns]
df_index ['202201', '202202', '202203', '202204', '202205', '202206', '202207', '202208', '202209', '202210', '202211', '202212', '202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405']
202405
ym_index 28

In [129]:
# document.add_paragraph('자산 관리(db)', style='List Number')
document.add_heading('자산 관리(db)', level=1) 
document.add_paragraph(f'총 {int(total_instance)}인스턴스(운영계)', style='List Bullet')

print(pivot2)

if len(regions) > 1: # == 'All':
    document.add_picture(f'./charts/db_{regions}_{y}_{m}_{d}_1.png')
    document.add_paragraph(f'월별 추세', style='List Bullet')
    document.add_picture(f'./charts/db_{regions}_{y}_{m}_{d}_2.png')
    
    document.add_paragraph(f'유형/리전별 현황', style='List Bullet')
    # Document
    addPivot2Table(pivot2)
else:
    document.add_paragraph(f'월별 추세', style='List Bullet')
    document.add_picture(f'./charts/db_{regions}_{y}_{m}_{d}_2.png')

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)
document.add_page_break()

리전        유형  RU  합계    비중
0      REDIS   6   6  46.2
1   POSTGRES   4   4  30.8
2      MONGO   3   3  23.1
3      MARIA   0   0   0.0
4      Mongo   0   0   0.0
5     TIBERO   0   0   0.0

In [130]:
document.save('demo.docx')

## (신규포탈)자산관리(k8s)(완료)

In [131]:
from datetime import datetime, timedelta
from calendar import monthrange
# def period(yyy, mmm):
#     first_days = []
#     last_days = []
    
#     for month in range(1, 13):  # Loop through each month (1 to 12)
#         # Get the first day of the month
#         first_day = datetime(year, month, 1)
        
#         # Get the last day of the month
#         next_month = month % 12 + 1 if month != 12 else 12
#         print(next_month)
#         last_day = datetime(year, next_month, 1) - timedelta(days=1)
        
#         first_days.append(first_day)
#         last_days.append(last_day)
        
#         # print("first_days", first_days)
#         print("last_days", last_days)
        
#         if mmm == month:
            # return first_day.strftime('%Y-%m-%d'), last_day.strftime('%Y-%m-%d')

def period(year, month):
    first_day = datetime(year, month, 1)
    last_day = datetime(year, month, monthrange(year, month)[1])
    return first_day.strftime('%Y-%m-%d'), last_day.strftime('%Y-%m-%d')

In [132]:
data_endpoint = 'http://10.11.66.85:8080/assets/kubernetes/list/all'
# data_endpoint = 'http://10.11.66.85:8080/assets/kubernetes/list/all'
# data_endpoint = 'http://10.11.66.85:8080/kubernetes/list/all'
# Request header
request_header = {
    "skip": 0,
    "limit": 50000,
    # "from_YYYYMMDDHH24MI": "202401010000",
    # "to_YYYYMMDDHH24MI": "202402030000",
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "cluster_name": "",
    "is_monitoring": True,
    "is_draft": False,
    "is_use": True
}
# Call the function
async with httpx.AsyncClient(timeout=httpx.Timeout(read_timeout=30)) as client:
    result = await fetch_data(access_token, data_endpoint, request_header)

ReadTimeout:

In [ ]:
df = pd.DataFrame(result['data'])

In [ ]:
df.columns

In [ ]:
df = df[['year', 'month', 'day', 'region', 'az', 'tenant', 'progress', 
         'cluster_name', 'node_type', 'node_name', 'node_ips', 'api_vip',
         'flavor', 'network_zone', 'contacts', 'k8s_version',
         'is_monitoring', 'comment', 'api_cert_expired_date', 'ca_cert_expired_date',
         'etcd_cert_expired_date', 'is_draft', 'is_use']]

In [ ]:
df.columns = [ '년', '월', '일', '리전', 'AZ', '테넌트', '진행상태',
       '클러스터명', 'node_type', 'node_name', 'node_ips', 'api_vip',
       'Flavor', '네트워크', '담당팀', 'k8s_version',
       '모니터링 유무', '비고', 'api_cert_expired_date', 'ca_cert_expired_date',
       'etcd_cert_expired_date', 'is_draft', 'is_use']

In [ ]:
df

In [ ]:
# 월별추세용, 상세현황용
# df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered = df[ df['테넌트'].isin(['PRD']) & df['리전'].isin(regions) & ~(df['클러스터명'].isin(['local']))]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) & ~(df['클러스터명'].isin(['local']))]

# print(df_filtered)
# print(df_filtered_current)

# Pivoting
# pivot, total = getPivotTable(df, month, y)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['COMPLETED']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
print(df_completed)
completed = len(df_completed)

df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['In-progress']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
incompleted = len(df_incompleted)

In [ ]:
# print(df_filtered_current)
print(completed, incompleted)

In [ ]:
# if regex != 'RU':
# df_filtered = df[[ '리전', '클러스터명', '모니터링 유무']]
# df_filtered = df[df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & ~(df['클러스터명'].isin(['local']))]
# df_filtered = df[ df['테넌트'].isin(['PRD']) & ~(df['클러스터명'].isin(['local']))]

print("df_filtered",df_filtered)
# Pivoting
# pivot, total = getPivotTable(df, month, year)

df_month = df_filtered[ df_filtered['년'].isin([year]) & df_filtered['월'].isin([month])]
print("df_month", df_month)
total = len(df_month)
print(total)

# year = int(year)
# month = int(month)

In [ ]:
# Pivoting
# pivot, total = getPivotTable(df, month)

# m_k8s = today + relativedelta(months=-2)
# m_k8s_split = int(m_k8s.strftime("%m").lstrip("0").replace(" 0"," "))
# print(m_k8s_split)

# if month == 1:
#     df_premonth = df_filtered[(df_filtered['년']==y-1) & (df_filtered['월']==m_k8s_split)]
# else:
#     df_premonth = df_filtered[(df_filtered['년']==y) & (df_filtered['월']==month-1)]
    
# df_curmonth = df_filtered[(df_filtered['년']==y) & (df_filtered['월']==month)]
# total = len(df_month)
# print(total)

# print("이전달", df_premonth)
# print("현재달", df_curmonth)

In [ ]:
# print(df)
# df = df[df['테넌트'].isin(['PRD'])]

yeari = int(year)
monthi = int(month)
proyear = int(yeari)
print(yeari, monthi)
# premonth = monthi - 1
if monthi == 1:
    premonth = 12
    yeari = yeari - 1
else:
    premonth = monthi - 1

df_filtered['date'] = df_filtered['년'] + '-' + df_filtered['월'] + '-' + df_filtered['일']
# Convert the 'date' column to pandas datetime
df_filtered['date'] = pd.to_datetime(df_filtered['date'])

if monthi == 1:
    first_date, last_date = period(proyear, monthi)
else:
    first_date, last_date = period(yeari, monthi)
    
print(first_date, last_date)
df_curmonth = df_filtered[(df_filtered['date'] >= first_date) & (df_filtered['date'] <= last_date)]
# df_curmonth = df_curmonth.drop(columns=['id','created_at','updated_at','updater','comment','date'])
df_curmonth = df_curmonth[['년','월','일','리전','테넌트','클러스터명','node_name']]
print("curmonth",df_curmonth)

# Or filter rows based on a specific date range
first_date, last_date = period(yeari, premonth)
print(first_date, last_date)
df_premonth = df_filtered[(df_filtered['date'] >= first_date) & (df_filtered['date'] <= last_date)]
# df_premonth = df_premonth.drop(columns=['id','created_at','updated_at','updater','comment','date'])
df_premonth = df_premonth[['년','월','일','리전','테넌트','클러스터명','node_name']]
print("premonth",df_premonth)

# df_result_sub = pd.concat([df_premonth,df_curmonth,df_curmonth]).drop_duplicates(keep=False)

In [ ]:
# node_name을 기준으로 추가된 행 찾기
df_added_rows = df_curmonth[~df_curmonth['node_name'].isin(df_premonth['node_name'])]

# node_name을 기준으로 삭제된 행 찾기
df_deleted_rows = df_premonth[~df_premonth['node_name'].isin(df_curmonth['node_name'])]

print("added",df_added_rows)
print("deleted",df_deleted_rows)

In [ ]:
# Chart - Bar 차트
if len(regions) > 1: # == 'All':

    # Data
    # rows = df_filtered.loc[(df_filtered['월']==month)]
    rows = df_month

    data, pivot, total = getPivotTable_event(rows, month, regions)
    source = pivot

    # Chart
    # if incompleted == 0:
    chart = getPieChart(source)
    # else:
    #     source = flatten_2d(data)
    #     chart = getStackedHBarChart(source)    

    # source = pivot
    # if incompleted == 0:
    #     chart = getPieChart(source)
    # else:
    #     chart = getStackedHBarChart1(source)
    chart.save(f'./charts/k8s_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

# Chart - Line 차트
df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
print(ym2)
print(df_filtered)
data = counter_3d(df_filtered,ym2)
# data = counter_3d_k8s(df_filtered,ym)
chart = getLineChart_new(data)
# chart = getLineChart2(df_filtered, month)
chart.save(f'./charts/k8s_{regions}_{y}_{m}_{d}_3.png')

# Document
# document.add_paragraph('자산 관리(k8s)', style='List Number')
document.add_heading('자산 관리(k8s)', level=1) 
document.add_paragraph(f'총 {total}노드(운영계)', style='List Bullet')

# Chart - Bar 차트
if len(regions) > 1: # == 'All':
    document.add_picture(f'./charts/k8s_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

document.add_paragraph('월별 추세', style='List Bullet')
document.add_picture(f'./charts/k8s_{regions}_{y}_{m}_{d}_3.png')   

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

# Document
document.add_paragraph('상세 현황', style='List Bullet')
# Table 생성
df_month = df_month[(df_month['월']==month)]
df_month = df_month[[ '리전','AZ','클러스터명', '비고']]
df_month = df_month.groupby(df_month.columns.tolist(), as_index=False).size()
df_month.rename(columns={'size':'노드수', '비고':'모니터링 유무'}, inplace=True)
df_month = df_month[[ '리전','AZ','클러스터명','노드수', '모니터링 유무']]

print("df_month",df_month)

if len(df_month) == 0:
    pass
else:
    addTable(df_month)

# df_curmonth = df_curmonth[(df_curmonth['월']==month)]
# df_curmonth = df_curmonth[[ '리전','node_name']]
# df_premonth = df_premonth[[ '리전','node_name']]

In [ ]:
df_added_rows = df_added_rows[[ '리전','node_name']]
df_deleted_rows = df_deleted_rows[[ '리전','node_name']]

print("added", df_added_rows)
print("deleted", df_deleted_rows)

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

document.add_paragraph('전월 대비 삭제된 노드', style='List Bullet')
# A-B (삭제된 건)
# df_result_sub = pd.concat([df_premonth,df_curmonth,df_curmonth]).drop_duplicates(keep=False)
# print(df_result_sub)

if len(df_deleted_rows) == 0:
    pass
else:
    addTable(df_deleted_rows)

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)
    
document.add_paragraph('전월 대비 추가된 노드', style='List Bullet')
# B-A (추가된 건)
# df_result_add = pd.concat([df_curmonth,df_premonth,df_premonth]).drop_duplicates(keep=False)
# print(df_result_add)
if len(df_added_rows) == 0:
    pass
else:
    addTable(df_added_rows)

# document.add_paragraph('월별 추세', style='List Bullet')
# document.add_picture(f'./charts/k8s_{region}_{y}_{m}_{d}_3.png')   
document.add_page_break()
    
# elif regex == 'RU':
#     document.add_page_break()
#     pass

In [ ]:
document.save('demo.docx')

## (신규포탈)용량관리(완료)

In [133]:
data_endpoint = 'http://10.11.66.85:8080/capacities/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [134]:
df = pd.DataFrame(result['data'])

In [135]:
print(df)

        id  year month day region az tenant customer     progress  \
0     1030  2024    05  01     KR  2    PRD      CCS  In-progress
1     1069  2024    05  01     NA  1    PRD      CCS  In-progress
2     1075  2024    05  01     NA  2    PRD      CCS  In-progress
3     1018  2024    05  01     KR  1    PRD      CCS  In-progress
4     1047  2024    05  01     KR  2    PRD      CCS  In-progress
...    ...   ...   ...  ..    ... ..    ...      ...          ...
1120   862  2024    03  01     EU  1    PRD      CCS  In-progress
1121   293  2023    08  01     EU  1    PRD      CCS  In-progress
1122   717  2024    02  01     KR  2    PRD      CCS  In-progress
1123   507  2023    11  01     EU  1    PRD      CCS    Completed
1124   389  2023    10  01     KR  2    PRD      CCS  In-progress

     resource_type ticket_no  \
0        Host(CPU)         -
1          Storage         -
2        Host(CPU)         -
3     Host(Memory)         -
4     Host(Memory)         -
...            ...       ...
1120       Storage         -
1121     Host(CPU)         -
1122  Host(Memory)         -
1123     Host(CPU)         -
1124     Host(CPU)      None

                                                  title   note  is_draft  \
0     운영계 - 임계치 도달,- PAAS-PRD-C5-01R10 CPU 105% 초과로 ...  긴급 대응     False
1     운영계 - 임계치 도달,- aggr_node01_SSD01_data 사용율 70% ...  긴급 대응     False
2     운영계 - 임계치 도달,- US-WEST-1-PRD-M5-0105-GEN2 CPU ...  증설 검토     False
3            신운영계 - 임계치 도달,- LINUX Memory 60% 초과로 증설 검토  증설 검토     False
4     운영계 - 임계치 도달,- PAAS-PRD-C5-01R10 Memory 70% 초과...  할당 중지     False
...                                                 ...    ...       ...
1120  운영계 - 임계치 도달,- aggr_node02_data(SAS) 사용율 75% 초...  긴급 대응     False
1121     운영계 - 임계치 도달,- CCS-LINUX CPU 할당률 75% 초과로 증설 검토  증설 검토     False
1122   운영계 - 임계치 도달,- PRD-M5-02R11 Memory 75% 초과로 할당 중지  할당 중지     False
1123  운영계 - 임계치 도달,- GCS-LINUX CPU 60% 초과로 증설 검토 -> ...  증설 검토     False
1124  운영계 - 임계치 도달,- IAAS-PRD-C5-01R10 CPU 75% 초과로 증...  증설 검토     False

      is_use updater       created_at_str       updated_at_str
0       True     남원우  2024-06-03 14:03:57  2024-06-03 14:03:57
1       True     남원우  2024-06-03 14:03:57  2024-06-03 14:03:57
2       True     남원우  2024-06-03 14:03:57  2024-06-03 14:03:57
3       True     남원우  2024-06-03 14:03:57  2024-06-03 14:03:57
4       True     남원우  2024-06-03 14:03:57  2024-06-03 14:03:57
...      ...     ...                  ...                  ...
1120    True     남원우  2024-04-05 16:36:55  2024-04-05 16:36:55
1121    True     남원우  2024-04-05 16:36:55  2024-04-05 16:36:55
1122    True     남원우  2024-04-05 16:36:55  2024-04-05 16:36:55
1123    True     남원우  2024-04-05 16:36:55  2024-04-05 16:36:55
1124    True     남원우  2024-04-05 16:36:55  2024-04-05 16:36:55

[1125 rows x 18 columns]

In [136]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'resource_type', 'ticket_no', 'title', 'note', 'is_draft',
       'is_use', 'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [137]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'progress', 'resource_type', 'ticket_no', 'title', 'note', 'is_draft', 'is_use']]

In [138]:
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '카테고리', 'Ticket', '제목', '내용설명', 'is_draft', 'is_use']

In [139]:
df.head()

,년,월,리전,AZ,테넌트,진행상태,카테고리,Ticket,제목,내용설명,is_draft,is_use
0,2024,05,KR,2,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- PAAS-PRD-C5-01R10 CPU 105% 초과로 ...",긴급 대응,False,True
1,2024,05,NA,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- aggr_node01_SSD01_data 사용율 70% ...",긴급 대응,False,True
2,2024,05,NA,2,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- US-WEST-1-PRD-M5-0105-GEN2 CPU ...",증설 검토,False,True
3,2024,05,KR,1,PRD,In-progress,Host(Memory),-,"신운영계 - 임계치 도달,- LINUX Memory 60% 초과로 증설 검토",증설 검토,False,True
4,2024,05,KR,2,PRD,In-progress,Host(Memory),-,"운영계 - 임계치 도달,- PAAS-PRD-C5-01R10 Memory 70% 초과...",할당 중지,False,True

In [140]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

# Pivoting
# pivot, total = getPivotTable(df, month, y)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
completed = len(df_completed)

df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['In-progress']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
incompleted = len(df_incompleted)

In [141]:
print(df_filtered_current)
print(completed, incompleted)

        년   월  리전 AZ  테넌트         진행상태       카테고리 Ticket  \
95   2024  05  RU  1  PRD  In-progress  Host(CPU)      -
106  2024  05  RU  1  PRD  In-progress    Storage      -

                                                    제목   내용설명  is_draft  \
95   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
106  운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False

     is_use
95     True
106    True
0 2

In [142]:
print(completed, incompleted)

0 2

In [143]:
df_filtered

,년,월,리전,AZ,테넌트,진행상태,카테고리,Ticket,제목,내용설명,is_draft,is_use
95,2024,05,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
106,2024,05,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
155,2024,04,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
206,2024,04,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
239,2023,11,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
266,2023,12,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
290,2023,08,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 검토,False,True
301,2023,11,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
317,2023,07,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
375,2024,01,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
395,2024,02,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
419,2023,09,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 검토,False,True
421,2023,08,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
448,2023,05,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
455,2024,03,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
469,2023,12,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
519,2023,05,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 55% 초과로 증설 ...",증설 검토,False,True
562,2023,06,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 검토,False,True
573,2023,04,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 고려,False,True
610,2023,10,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 검토,False,True
618,2023,06,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
696,2024,02,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
699,2024,03,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...",할당 중지,False,True
711,2024,01,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...",증설 검토,False,True
790,2023,04,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 85% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
904,2023,03,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 고려,False,True
963,2023,07,RU,1,PRD,In-progress,Storage,-,"운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...",증설 검토,False,True
970,2023,09,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
1097,2023,10,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True
1115,2023,03,RU,1,PRD,In-progress,Host(CPU),-,"운영계 - 임계치 도달,- 운영계 CPU자원 85% 초과로 할당 중지,- 호스트 R...",할당 중지,False,True

In [144]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':

    # Data
    rowsc = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Completed']))]
    rowsi = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['In-progress']))]
        
    document.add_heading('용량관리', level=1) 
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/cpmc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/cpmi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format(''))
        run.add_picture(f'./charts/cpmc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}진행".format(''))
        run.add_picture(f'./charts/cpmi_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/cpmi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/cpmi_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/cpmc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/cpmc_{y}_{m}_{d}_{v}_1.png')
    
else:
    document.add_heading('용량관리', level=1) 
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 진행: {incompleted})', style='List Bullet')
    pass

# Chart - 라인 차트
# chart = getLineChart2(df_filtered, month)
# chart.save(f'./charts/cpm_{region}_{y}_{m}_{d}_2.png')
# Chart - 라인 차트
df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# data = counter_3d(df_filtered,ym)
data = counter_3d_regular(df_filtered,ym2)
# chart = getLineChart_new(data)
chart = getLineChart_capacity(data)
# chart = getLineChart(data)
chart.save(f'./charts/cpm_{regions}_{y}_{m}_{d}_2.png')

         년   월  리전 AZ  테넌트         진행상태       카테고리 Ticket  \
95    2024  05  RU  1  PRD  In-progress  Host(CPU)      -
106   2024  05  RU  1  PRD  In-progress    Storage      -
155   2024  04  RU  1  PRD  In-progress    Storage      -
206   2024  04  RU  1  PRD  In-progress  Host(CPU)      -
239   2023  11  RU  1  PRD  In-progress  Host(CPU)      -
266   2023  12  RU  1  PRD  In-progress    Storage      -
290   2023  08  RU  1  PRD  In-progress    Storage      -
301   2023  11  RU  1  PRD  In-progress    Storage      -
317   2023  07  RU  1  PRD  In-progress  Host(CPU)      -
375   2024  01  RU  1  PRD  In-progress  Host(CPU)      -
395   2024  02  RU  1  PRD  In-progress    Storage      -
419   2023  09  RU  1  PRD  In-progress    Storage      -
421   2023  08  RU  1  PRD  In-progress  Host(CPU)      -
448   2023  05  RU  1  PRD  In-progress  Host(CPU)      -
455   2024  03  RU  1  PRD  In-progress    Storage      -
469   2023  12  RU  1  PRD  In-progress  Host(CPU)      -
519   2023  05  RU  1  PRD  In-progress    Storage      -
562   2023  06  RU  1  PRD  In-progress    Storage      -
573   2023  04  RU  1  PRD  In-progress    Storage      -
610   2023  10  RU  1  PRD  In-progress    Storage      -
618   2023  06  RU  1  PRD  In-progress  Host(CPU)      -
696   2024  02  RU  1  PRD  In-progress  Host(CPU)      -
699   2024  03  RU  1  PRD  In-progress  Host(CPU)      -
711   2024  01  RU  1  PRD  In-progress    Storage      -
790   2023  04  RU  1  PRD  In-progress  Host(CPU)      -
904   2023  03  RU  1  PRD  In-progress    Storage      -
963   2023  07  RU  1  PRD  In-progress    Storage      -
970   2023  09  RU  1  PRD  In-progress  Host(CPU)      -
1097  2023  10  RU  1  PRD  In-progress  Host(CPU)      -
1115  2023  03  RU  1  PRD  In-progress  Host(CPU)      -

                                                     제목   내용설명  is_draft  \
95    운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
106   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
155   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
206   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
239   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
266   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
290   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 검토     False
301   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
317   운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
375   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
395   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
419   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 검토     False
421   운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
448   운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
455   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
469   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
519   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 55% 초과로 증설 ...  증설 검토     False
562   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 검토     False
573   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 고려     False
610   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 검토     False
618   운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
696   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
699   운영계 - 임계치 도달,- 운영계 CPU 자원 90% 초과로 할당 중지,- 호스트 ...  할당 중지     False
711   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용율 50% 초과로 증설 ...  증설 검토     False
790   운영계 - 임계치 도달,- 운영계 CPU자원 85% 초과로 할당 중지,- 호스트 R...  할당 중지     False
904   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 고려     False
963   운영계 - 임계치 도달,- 운영계 스토리지 node01 사용률 50% 초과로 증설 ...  증설 검토     False
970   운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
1097  운영계 - 임계치 도달,- 운영계 CPU자원 90% 초과로 할당 중지,- 호스트 R...  할당 중지     False
1115  운영계 - 임계치 도달,- 운영계 CPU자원 85% 초과로 할당 중지,- 호스트 R...  할당 중지     False

      is_use    Date
95      True  202405
106     True  202405
155     True  202404
206     True  202404
239     True  202311
266     True  202312
290     True  202308
301     True  202311
317     True  202307
375     True  202401
395     True  202402
419     True  202309
421     True  202308
448     True  202305
455     True  202403
469     True  202312
519     True  202305
562     True  202306
573     True  202304
610     True  202310
618     True  202306
696     True  202402
699     True  202403
711     True  202401
790     True  202304
904     True  202303
963     True  202307
970     True  202309
1097    True  202310
1115    True  202303
        Date         진행상태
95    202405  In-progress
106   202405  In-progress
155   202404  In-progress
206   202404  In-progress
239   202311  In-progress
266   202312  In-progress
290   202308  In-progress
301   202311  In-progress
317   202307  In-progress
375   202401  In-progress
395   202402  In-progress
419   202309  In-progress
421   202308  In-progress
448   202305  In-progress
455   202403  In-progress
469   202312  In-progress
519   202305  In-progress
562   202306  In-progress
573   202304  In-progress
610   202310  In-progress
618   202306  In-progress
696   202402  In-progress
699   202403  In-progress
711   202401  In-progress
790   202304  In-progress
904   202303  In-progress
963   202307  In-progress
970   202309  In-progress
1097  202310  In-progress
1115  202303  In-progress <class 'pandas.core.frame.DataFrame'>
df_extract         Date
95    202405
106   202405
155   202404
206   202404
239   202311
266   202312
290   202308
301   202311
317   202307
375   202401
395   202402
419   202309
421   202308
448   202305
455   202403
469   202312
519   202305
562   202306
573   202304
610   202310
618   202306
696   202402
699   202403
711   202401
790   202304
904   202303
963   202307
970   202309
1097  202310
1115  202303
df_index ['202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405']
202405
ym_index 14

WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.
WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.

In [145]:
data

        Date         진행상태
95    202405  In-progress
106   202405  In-progress
155   202404  In-progress
206   202404  In-progress
239   202311  In-progress
266   202312  In-progress
290   202308  In-progress
301   202311  In-progress
317   202307  In-progress
375   202401  In-progress
395   202402  In-progress
419   202309  In-progress
421   202308  In-progress
448   202305  In-progress
455   202403  In-progress
469   202312  In-progress
519   202305  In-progress
562   202306  In-progress
610   202310  In-progress
618   202306  In-progress
696   202402  In-progress
699   202403  In-progress
711   202401  In-progress
963   202307  In-progress
970   202309  In-progress
1097  202310  In-progress

In [146]:
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/cpm_{regions}_{y}_{m}_{d}_2.png')

# Document
p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

document.add_paragraph(f'자원 이슈 현황', style='List Bullet')
if df_filtered[(df_filtered['년']==year) & (df_filtered['월']==month)].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        # addTable3_all(df_filtered_current, regex, month)
        addTable_capacity_all(df_filtered_current, month)
    else:
        addTable_capacity(df_filtered_current, month)

document.add_page_break()

In [147]:
document.save('demo.docx')

## (신규포탈)백업관리(완료)

In [148]:
data_endpoint = 'http://10.11.66.85:8080/backups/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [149]:
df = pd.DataFrame(result['data'])

In [150]:
print(df)

          id  year month day region az tenant customer   status     db_type  \
0      30667  2024    05  01     SG  1    PRD      CCS  Success     MongoDB
1      31009  2024    05  01     SG  1    PRD      CCS  Success     MongoDB
2      31008  2024    05  01     SG  1    PRD      CCS  Success     MongoDB
3      31007  2024    05  01     SG  1    PRD      CCS  Success     MongoDB
4      31006  2024    05  01     SG  1    PRD      CCS  Success     MongoDB
...      ...   ...   ...  ..    ... ..    ...      ...      ...         ...
17252   2263  2022    12  01     NA  1    PRD      CCS  Success  PostgreSQL
17253   2264  2022    12  01     NA  1    PRD      CCS  Success  PostgreSQL
17254   2265  2022    12  01     NA  1    PRD      CCS  Success  PostgreSQL
17255   2266  2022    12  01     NA  1    PRD      CCS     Fail  PostgreSQL
17256   2267  2022    12  01     NA  1    PRD      CCS  Success  PostgreSQL

                instance_name     instance_ip backup_freq         note  \
0        mongo-drive-au-kmc03    10.107.71.51        None         None
1         cpx-id-tfs-mg-dbp03    10.107.86.63        None         None
2         cpx-id-tfs-mg-dbp02   10.107.86.241        None         None
3         cpx-id-tfs-mg-dbp01    10.107.86.17        None         None
4      ccs2-id-pis-h-mg-dbp03   10.107.86.210        None         None
...                       ...             ...         ...          ...
17252       ccsnaparkcamdbp02   10.112.203.44        None         None
17253            ccsnavrdbp01   10.112.203.53        None         None
17254            ccsnavrdbp02   10.112.203.54        None         None
17255         ccsnadbmondbp01  10.112.203.225        None  sherpa 수집서버
17256        ccsnakuslmsdbp01   10.112.224.47        None         None

       is_draft  is_use updater       created_at_str       updated_at_str
0         False    True     송윤진  2024-06-04 10:33:16  2024-06-04 10:33:16
1         False    True     송윤진  2024-06-04 10:33:16  2024-06-04 10:33:16
2         False    True     송윤진  2024-06-04 10:33:16  2024-06-04 10:33:16
3         False    True     송윤진  2024-06-04 10:33:16  2024-06-04 10:33:16
4         False    True     송윤진  2024-06-04 10:33:16  2024-06-04 10:33:16
...         ...     ...     ...                  ...                  ...
17252     False    True   test2  2024-01-09 09:03:21  2024-01-09 09:03:21
17253     False    True   test2  2024-01-09 09:03:21  2024-01-09 09:03:21
17254     False    True   test2  2024-01-09 09:03:21  2024-01-09 09:03:21
17255     False    True   test2  2024-01-09 09:03:21  2024-01-09 09:03:21
17256     False    True   test2  2024-01-09 09:03:21  2024-01-09 09:03:21

[17257 rows x 19 columns]

In [151]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'status', 'db_type', 'instance_name', 'instance_ip', 'backup_freq',
       'note', 'is_draft', 'is_use', 'updater', 'created_at_str',
       'updated_at_str'],
      dtype='object')

In [152]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'status', 'db_type', 'instance_name', 'instance_ip', 'backup_freq',
         'note', 'is_draft', 'is_use']]

In [153]:
# description
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '성패', '유형', 'Instance', 'instance_ip', 'freq_full_archive',
       '비고', 'is_draft', 'is_use']

In [154]:
df.head()

,년,월,리전,AZ,테넌트,성패,유형,Instance,instance_ip,freq_full_archive,비고,is_draft,is_use
0,2024,05,SG,1,PRD,Success,MongoDB,mongo-drive-au-kmc03,10.107.71.51,None,None,False,True
1,2024,05,SG,1,PRD,Success,MongoDB,cpx-id-tfs-mg-dbp03,10.107.86.63,None,None,False,True
2,2024,05,SG,1,PRD,Success,MongoDB,cpx-id-tfs-mg-dbp02,10.107.86.241,None,None,False,True
3,2024,05,SG,1,PRD,Success,MongoDB,cpx-id-tfs-mg-dbp01,10.107.86.17,None,None,False,True
4,2024,05,SG,1,PRD,Success,MongoDB,ccs2-id-pis-h-mg-dbp03,10.107.86.210,None,None,False,True

In [155]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
df_filtered2 = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['성패'].isin(['Fail']) & df['월'].isin([month]) ]

# Pivoting
pivot, total = getPivotTable(df_filtered_current)

df_completed = df_filtered[ df_filtered['성패'].isin(['Success']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
completed = len(df_completed)

df_incompleted = df_filtered[ df_filtered['성패'].isin(['Fail']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
incompleted = len(df_incompleted)

In [156]:
print(df_filtered_current)
print(completed, incompleted)

         년   월  리전 AZ  테넌트       성패          유형        Instance  \
499   2024  05  RU  1  PRD  Success     MongoDB  ccsprumongop03
500   2024  05  RU  1  PRD  Success     MongoDB  ccsprumongop01
575   2024  05  RU  1  PRD  Success     MongoDB  ccsprumongop02
1083  2024  05  RU  1  PRD  Success  PostgreSQL      ccsrudbp01
1084  2024  05  RU  1  PRD  Success  PostgreSQL      ccsrudbp02
1085  2024  05  RU  1  PRD  Success  PostgreSQL     ccsprudbp01
1086  2024  05  RU  1  PRD  Success  PostgreSQL     ccsprudbp02

        instance_ip freq_full_archive    비고  is_draft  is_use
499    10.107.19.83              None  None     False    True
500    10.107.19.81              None  None     False    True
575    10.107.19.82              None  None     False    True
1083   10.107.19.21              None  None     False    True
1084  10.107.19.123              None  None     False    True
1085   10.107.19.24              None  None     False    True
1086   10.107.19.25              None  None     False    True
7 0

In [157]:
# df_filtered = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') ]
# df_filtered_current = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월']==month) & (df['년']==y)]
# # df_filtered2 = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월간']=='O')]
# df_filtered2 = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['성패']=='X') & (df['월']==month) & (df['년']==y)]

# # Pivoting
# pivot, total = getPivotTable(df_filtered, month, y)

# df_completed = df_filtered[(df_filtered['년']==y) & (df_filtered['월']==month) & (df_filtered['성패']=='O') ]
# completed_rows = len(df_completed)
# completed = counter(df_completed, regex)

# df_incompleted = df_filtered[(df_filtered['년']==y) &  (df_filtered['월']==month) & (df_filtered['성패']!='O') ]
# incompleted_rows = len (df_incompleted)
# incompleted = counter(df_incompleted, regex)

In [158]:
print(completed, incompleted)

7 0

In [159]:
df_filtered_selectedColumns=df_filtered2[['년','월','비고','리전','AZ','유형' ]]
df_filtered_selectedColumns.sort_values(by=['리전','유형'], ascending=True, inplace=True)
df_filtered_selectedColumns.reset_index(drop=True, inplace=True)
# a=df_filtered_selectedColumns[['클러스터명','프로메테우스 설치 유무']]
a=df_filtered_selectedColumns
group_a = a.groupby(['리전','유형','비고'])
group_b=pd.DataFrame(group_a.size())

group_a = a.groupby(['년','월','비고','리전','AZ','유형'])
group_b=pd.DataFrame(group_a.size())
group_b=group_b.reset_index()
# group_b.columns=['리전','클러스터명','노드수']
group_b.sort_values(by=['리전','유형'], ascending=True, inplace=True)
# group_b.sort_values(by=['노드수'], ascending=False, inplace=True)
group_b.reset_index(drop=True, inplace=True)
drop_a=group_b.drop_duplicates(['리전','유형','비고'], keep = 'first')
drop_a.reset_index(drop=True, inplace=True)
# drop_a.rename(columns = {'O':'노드수'},inplace=True)
# drop_a
# drop_a
# group_b

df_filtered_selectedColumns=df_filtered2[['년','월','비고','리전','AZ','유형' ]]
df_filtered_selectedColumns.sort_values(by=['리전','유형'], ascending=True, inplace=True)
df_filtered_selectedColumns.reset_index(drop=True, inplace=True)
# a=df_filtered_selectedColumns[['클러스터명','프로메테우스 설치 유무']]
a=df_filtered_selectedColumns

group_a = a.groupby(['리전','유형', '비고'])
group_c=pd.DataFrame(group_a.size())
group_c

group_c=group_c.reset_index()
group_c
group_c.columns=['리전','유형','비고','DB 인스턴스 Qty']
group_c.sort_values(by=['리전','유형'], ascending=True, inplace=True)
# group_b.sort_values(by=['노드수'], ascending=False, inplace=True)
group_c.reset_index(drop=True, inplace=True)
# # value_a.rename(columns = {['클러스터명':'클러스터명','노드수':'노드수']},inplace=True)
# drop_a

# group_c
drop_a['DB 인스턴스 Qty'] = group_c['DB 인스턴스 Qty']

df_filtered_final = drop_a[['년', '월', '비고', '리전', 'AZ', '유형', 'DB 인스턴스 Qty']]
# non_stand_final = (df_filtered_final[(df_filtered_final['비고']!='비표준설치(담당자설치)')])
# df_filtered_final = df_filtered_final[ (df_filtered_final['월']==month) ]
# # group_c
# # group_a.size()
df_filtered_final

# non_stand_final

Empty DataFrame
Columns: [년, 월, 비고, 리전, AZ, 유형, DB 인스턴스 Qty]
Index: []

In [160]:
# Chart - Pie 차트
# if len(regions) > 1: # == 'All':
    
#     # Data
#     # rows = df_filtered.loc[df_filtered['년'].isin([year]) & df_filtered['월'].isin([year])]
#     rows = df_filtered_current
    
#     data, pivot, total = getPivotTable_event(rows, month, regions)
#     source = pivot
    
#     # Chart
#     if incompleted == 0:
#         chart = getPieChart(source)
#     else:
#         source = flatten_2d(data)
#         chart = getStackedHBarChart(source)    
        
#     chart.save(f'./charts/bm_{regions}_{y}_{m}_{d}_1.png')
# else:
#     pass

current_date = datetime.now()
one_year_ago = current_date - timedelta(days=365)
current_date_str = current_date.strftime('%Y%m')
one_year_ago_str = one_year_ago.strftime('%Y%m')

# Chart - 라인 차트
df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
filtered_df = df_filtered[(df_filtered['Date'] >= one_year_ago_str) & ( df_filtered['Date'] <= current_date_str)]
non_stand = filtered_df[(filtered_df['비고']=='비표준설치(담당자설치)')]

print(non_stand, type(non_stand))
chart = getLineChart3(filtered_df, non_stand)
chart.save(f'./charts/bm_{regions}_{y}_{m}_{d}_2.png')

Empty DataFrame
Columns: [년, 월, 리전, AZ, 테넌트, 성패, 유형, Instance, instance_ip, freq_full_archive, 비고, is_draft, is_use, Date]
Index: [] <class 'pandas.core.frame.DataFrame'>

WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.
WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.
WARN Infinite extent for field "__count": [Infinity, -Infinity]

In [161]:
# Document
document.add_heading('백업 관리', level=1) 

t = completed + incompleted
if t == completed :
    if t == 0 : 
        document.add_paragraph(f'총 {t} 건', style='List Bullet')
    else:
        document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
else :
    # document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 이슈: {incompleted} 건)', style='List Bullet')
    document.add_paragraph(f'총 {t} 건 (성공: {completed} / 실패[미진행포함]: {incompleted})', style='List Bullet')

# Document
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/bm_{regions}_{y}_{m}_{d}_2.png')

if len(regions) > 1: # == 'All':
    document.add_paragraph('실패/미진행 현황', style='List Bullet')
else:
    document.add_paragraph('상세 현황', style='List Bullet')

if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        df_filtered_final.sort_values('비고', ascending=False)
        addTable_1_8_all(df_filtered_final, month)
    else:
        addTable_1_8(df_filtered_current, month)
    
document.add_page_break()

In [162]:
document.save('demo.docx')

## (신규포탈)보안관리(완료)

In [163]:
data_endpoint = 'http://10.11.66.85:8080/securities/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [164]:
df = pd.DataFrame(result['data'])

In [165]:
print(df)

        id  year month day region az tenant customer   progress task_type  \
0     6441  2024    05  01     EU  1    PRD      CCS  Completed      None
1     6582  2024    05  01     NA  1    PRD      CCS  Completed      None
2     6430  2024    05  01     EU  1    PRD      CCS  Completed      None
3     6701  2024    05  01     SG  1    PRD      CCS  Completed      None
4     6033  2024    04  01     EU  1    PRD      CCS  Completed      None
...    ...   ...   ...  ..    ... ..    ...      ...        ...       ...
3346  1037  2023    06  01     EU  1    PRD      CCS  Completed      None
3347  1725  2023    11  01     SG  1    PRD      CCS  Completed      None
3348  1994  2024    01  01     SG  1    PRD      CCS  Completed      None
3349  1867  2024    01  01     EU  1    PRD      CCS  Completed      None
3350   746  2023    04  01     SG  1    PRD      CCS  Completed      None

                                                  title     ticket_no  \
0       CnC(C_C)_Request to block the IPs_20240518_1402  EUCLOUD-7807
1     CnC(C_C)_Request to block the IPs_20240518_180151  NACLOUD-4279
2     CnC(C_C)_Request to block the IPs_20240515_124922  EUCLOUD-7776
3     CnC(C_C)_Request to block the IPs_20240518_184022  SGCLOUD-5017
4       CnC(C_C)_Request to block the IPs_20240405_0222  EUCLOUD-7427
...                                                 ...           ...
3346    CnC(C_C)_Request to block the IPs_20230612_2208  EUCLOUD-5295
3347    CnC(C_C)_Request to block the IPs_20231119_0135  SGCLOUD-3729
3348    CnC(C_C)_Request to block the IPs_20240118_0580  SGCLOUD-3973
3349    CnC(C_C)_Request to block the IPs_20231230_2108  EUCLOUD-6712
3350    CnC(C_C)_Request to block the IPs_20230412_2032  SGCLOUD-2447

      is_draft  is_use updater       created_at_str       updated_at_str
0        False    True     문광훈  2024-06-10 15:26:04  2024-06-10 15:26:04
1        False    True     문광훈  2024-06-10 15:26:04  2024-06-10 15:26:04
2        False    True     문광훈  2024-06-10 15:26:04  2024-06-10 15:26:04
3        False    True     문광훈  2024-06-10 15:26:04  2024-06-10 15:26:04
4        False    True     문광훈  2024-06-10 15:26:04  2024-06-10 15:26:04
...        ...     ...     ...                  ...                  ...
3346     False    True     문광훈  2024-02-05 13:08:30  2024-02-05 13:08:30
3347     False    True     문광훈  2024-02-05 13:08:30  2024-02-05 13:08:30
3348     False    True     문광훈  2024-02-05 13:08:30  2024-02-05 13:08:30
3349     False    True     문광훈  2024-02-05 13:08:30  2024-02-05 13:08:30
3350     False    True     문광훈  2024-02-05 13:08:30  2024-02-05 13:08:30

[3351 rows x 17 columns]

In [166]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'progress', 'task_type', 'title', 'ticket_no', 'is_draft', 'is_use',
       'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [167]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'progress', 'task_type', 'title', 'ticket_no', 'is_draft', 'is_use']]

In [168]:
# description
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '진행상태', '유형', '제목', 'Ticket', 'is_draft', 'is_use']

In [169]:
df.head()

,년,월,리전,AZ,테넌트,진행상태,유형,제목,Ticket,is_draft,is_use
0,2024,05,EU,1,PRD,Completed,None,CnC(C_C)_Request to block the IPs_20240518_1402,EUCLOUD-7807,False,True
1,2024,05,NA,1,PRD,Completed,None,CnC(C_C)_Request to block the IPs_20240518_180151,NACLOUD-4279,False,True
2,2024,05,EU,1,PRD,Completed,None,CnC(C_C)_Request to block the IPs_20240515_124922,EUCLOUD-7776,False,True
3,2024,05,SG,1,PRD,Completed,None,CnC(C_C)_Request to block the IPs_20240518_184022,SGCLOUD-5017,False,True
4,2024,04,EU,1,PRD,Completed,None,CnC(C_C)_Request to block the IPs_20240405_0222,EUCLOUD-7427,False,True

In [170]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

# Pivoting
# pivot, total = getPivotTable(df, month, year)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
completed = len(df_completed)

df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['In-progress']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
incompleted = len(df_incompleted)

In [171]:
print(df_filtered)
print(df_filtered_current)
print(completed, incompleted)

         년   월  리전 AZ  테넌트       진행상태    유형  \
11    2024  05  RU  1  PRD  Completed  None
19    2024  04  RU  1  PRD  Completed  None
52    2024  04  RU  1  PRD  Completed  None
53    2024  04  RU  1  PRD  Completed  None
56    2024  04  RU  1  PRD  Completed  None
...    ...  ..  .. ..  ...        ...   ...
3282  2023  12  RU  1  PRD  Completed  None
3324  2023  02  RU  1  PRD  Completed  None
3336  2022  05  RU  1  PRD  Completed  None
3340  2023  02  RU  1  PRD  Completed  None
3343  2023  12  RU  1  PRD  Completed  None

                                                   제목        Ticket  is_draft  \
11    CnC(C_C)_Request to block the IPs_20240516_1014  RUCLOUD-1289     False
19    CnC(C_C)_Request to block the IPs_20240419_0932  RUCLOUD-1265     False
52    CnC(C_C)_Request to block the IPs_20240409_0840  RUCLOUD-1255     False
53    CnC(C_C)_Request to block the IPs_20240422_1414  RUCLOUD-1267     False
56    CnC(C_C)_Request to block the IPs_20240411_0943  RUCLOUD-1257     False
...                                               ...           ...       ...
3282  CnC(C_C)_Request to block the IPs_20231229_0857  RUCLOUD-1163     False
3324  CnC(C_C)_Request to block the IPs_20230205_0732   RUCLOUD-886     False
3336                                      긴급 보안점검 요청    RUCLOUD-693     False
3340  CnC(C_C)_Request to block the IPs_20230206_0617   RUCLOUD-892     False
3343  CnC(C_C)_Request to block the IPs_20231211_1417  RUCLOUD-1149     False

      is_use
11      True
19      True
52      True
53      True
56      True
...      ...
3282    True
3324    True
3336    True
3340    True
3343    True

[155 rows x 11 columns]
        년   월  리전 AZ  테넌트       진행상태    유형  \
11   2024  05  RU  1  PRD  Completed  None
258  2024  05  RU  1  PRD  Completed  None
285  2024  05  RU  1  PRD  Completed  None
329  2024  05  RU  1  PRD  Completed  None
335  2024  05  RU  1  PRD  Completed  None
425  2024  05  RU  1  PRD  Completed  None
439  2024  05  RU  1  PRD  Completed  None
455  2024  05  RU  1  PRD  Completed  None
464  2024  05  RU  1  PRD  Completed  None
475  2024  05  RU  1  PRD  Completed  None
507  2024  05  RU  1  PRD  Completed  None
533  2024  05  RU  1  PRD  Completed  None
589  2024  05  RU  1  PRD  Completed  None
591  2024  05  RU  1  PRD  Completed  None
594  2024  05  RU  1  PRD  Completed  None
599  2024  05  RU  1  PRD  Completed  None
692  2024  05  RU  1  PRD  Completed  None
751  2024  05  RU  1  PRD  Completed  None

                                                  제목        Ticket  is_draft  \
11   CnC(C_C)_Request to block the IPs_20240516_1014  RUCLOUD-1289     False
258  CnC(C_C)_Request to block the IPs_20240514_0932  RUCLOUD-1288     False
285  CnC(C_C)_Request to block the IPs_20240531_1352  RUCLOUD-1306     False
329  CnC(C_C)_Request to block the IPs_20240523_0831  RUCLOUD-1300     False
335  CnC(C_C)_Request to block the IPs_20240508_0938  RUCLOUD-1282     False
425  CnC(C_C)_Request to block the IPs_20240529_0926  RUCLOUD-1304     False
439  CnC(C_C)_Request to block the IPs_20240502_0821  RUCLOUD-1278     False
455  CnC(C_C)_Request to block the IPs_20240528_1452  RUCLOUD-1303     False
464  CnC(C_C)_Request to block the IPs_20240520_0818  RUCLOUD-1293     False
475  CnC(C_C)_Request to block the IPs_20240517_0901  RUCLOUD-1290     False
507  CnC(C_C)_Request to block the IPs_20240503_1007  RUCLOUD-1279     False
533  CnC(C_C)_Request to block the IPs_20240509_0836  RUCLOUD-1284     False
589  CnC(C_C)_Request to block the IPs_20240524_1024  RUCLOUD-1301     False
591  CnC(C_C)_Request to block the IPs_20240521_0836  RUCLOUD-1294     False
594  CnC(C_C)_Request to block the IPs_20240527_1432  RUCLOUD-1302     False
599  CnC(C_C)_Request to block the IPs_20240522_1013  RUCLOUD-1298     False
692  CnC(C_C)_Request to block the IPs_20240513_1400  RUCLOUD-1286     False
751  CnC(C_C)_Request to block the IPs_20240507_0856  RUCLOUD-1280     False

     is_use
11     True
258    True
285    True
329    True
335    True
425    True
439    True
455    True
464    True
475    True
507    True
533    True
589    True
591    True
594    True
599    True
692    True
751    True
18 0

In [172]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    
    # Data
    rowsc = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Completed']))]
    rowsi = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['In-progress']))]
    
    document.add_heading('보안 관리', level=1) 
    
    # Document
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 미완료: {incompleted})', style='List Bullet')
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/smc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/smi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format(''))
        run.add_picture(f'./charts/smc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}미완료".format(''))
        run.add_picture(f'./charts/smi_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0 and incompleted ==0:
        pass
        
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_security(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/smi_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/smi_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/smc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/smc_{y}_{m}_{d}_{v}_1.png')

else:
    document.add_heading('보안 관리', level=1) 
    document.add_paragraph(f'총 {completed+incompleted}건 (완료: {completed} / 미완료: {incompleted})', style='List Bullet')
    pass

# Chart - 라인 차트
df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
data = counter_3d(df_filtered,ym2)

# if data is None:
#     pass
# else:
chart = getLineChart_new(data)
# chart = getLineChart2(df_filtered, month)
# data = counter_3d(df_filtered, month)
# chart = getLineChart(data)
chart.save(f'./charts/sm_{regions}_{y}_{m}_{d}_2.png')
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/sm_{regions}_{y}_{m}_{d}_2.png')

ym_index 28
realList ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
dup ['202405', '202211', '202311', '202404', '202206', '202310', '202302', '202403', '202312', '202309', '202401', '202202', '202308', '202205', '202402']
최대값: 202405
최솟값: 202202
YM ['202405']
CL [18]
YM ['202405', '202404']
CL [18, 19]
YM ['202405', '202404', '202403']
CL [18, 19, 8]
YM ['202405', '202404', '202403', '202402']
CL [18, 19, 8, 18]
YM ['202405', '202404', '202403', '202402', '202401']
CL [18, 19, 8, 18, 12]
YM ['202405', '202404', '202403', '202402', '202401', '202312']
CL [18, 19, 8, 18, 12, 14]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311']
CL [18, 19, 8, 18, 12, 14, 17]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310']
CL [18, 19, 8, 18, 12, 14, 17, 9]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309']
CL [18, 19, 8, 18, 12, 14, 17, 9, 8]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308']
CL [18, 19, 8, 18, 12, 14, 17, 9, 8, 11]
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307']
YM ['202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306']
      Date  합계
0   202405  18
1   202404  19
2   202403   8
3   202402  18
4   202401  12
5   202312  14
6   202311  17
7   202310   9
8   202309   8
9   202308  11
10  202307   0
11  202306   0

In [173]:
p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

document.add_paragraph('상세 현황', style='List Bullet')
# Document
if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addTable_security_all(df_filtered_current, month)
    else:
        addTable_security(df_filtered_current, month)

document.add_page_break()

In [174]:
document.save('demo.docx')

## (신규포탈)하드웨어 정기점검(완료)

In [175]:
data_endpoint = 'http://10.11.66.85:8080/regular_checks/list'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "progress": [],
    "freq": [],
    "vendor": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [176]:
df = pd.DataFrame(result['data'])

In [177]:
print(df)

      id  year month day region az   progress       freq         vendor  \
0    841  2024    05  01     RU  1     Failed    Monthly            A10
1    840  2024    05  01     EU  2  Completed    Monthly       Paloalto
2    838  2024    05  01     EU  1  Completed    Monthly  Cisco(Server)
3    847  2024    05  01     RU  1     Failed    Monthly           Dell
4    828  2024    05  01     EU  1     Failed    Monthly            A10
..   ...   ...   ...  ..    ... ..        ...        ...            ...
811  590  2023    02  01     KR  1  Completed    Monthly         Netapp
812  475  2022    12  01     NA  1  Completed    Monthly      Netbackup
813  210  2023    08  01     NA  1  Completed    Monthly      Netbackup
814  605  2022    02  01     NA  1  Completed  Quarterly         Arista
815  466  2023    06  01     NA  1  Completed  Quarterly             HP

                                                 title  \
0                      RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
1     (월별) 월별_점검_eu101-PA-5250_(24년05월).docx월별_점검_e...
2                           24년5월_현대오토에버 TMS 정기점검 (5월)
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
4                   유지보수 계약 내의 정기점검 부재 (정기정검 계약 계획 없음)
..                                                 ...
811  KR>NetApp : (월별) 월별_netapp_KR_23년 2월 정기점검 레포트....
812       NA>Netbackup : (월별) NA_netbackup_2022_12.pdf
813      NA>Netbackup : (월별) NA_netbackup_2023_08.pdf
814  NA>Arista : (분기) 분기 점검 CCS_NA Arista(22년 1분기).pdf
815     NA>HP : (분기) 분기점검_HP_북미 점검문서(23년2분기).xlsx (6월)

                                           description  is_draft  is_use  \
0    <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
1                                                 None     False    True
2                                                 None     False    True
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
4                   유지보수 계약 내의 정기점검 부재 (정기정검 계약 계획 없음)     False    True
..                                                 ...       ...     ...
811                                               None     False    True
812                                               None     False    True
813                                               None     False    True
814                                               None     False    True
815                                               None     False    True

    updater       created_at_str       updated_at_str
0       박진홍  2024-06-03 17:00:54  2024-06-03 17:00:54
1       박진홍  2024-06-03 17:00:54  2024-06-03 17:00:54
2       박진홍  2024-06-03 17:00:54  2024-06-03 17:00:54
3       박진홍  2024-06-03 17:00:54  2024-06-03 17:00:54
4       박진홍  2024-06-03 17:00:54  2024-06-03 17:00:54
..      ...                  ...                  ...
811   test2  2024-01-05 13:32:00  2024-01-05 13:32:00
812   test2  2024-01-05 13:32:00  2024-01-05 13:32:00
813   test2  2024-01-05 13:32:00  2024-01-05 13:32:00
814   test2  2024-01-05 13:32:00  2024-01-05 13:32:00
815   test2  2024-01-05 13:32:00  2024-01-05 13:32:00

[816 rows x 16 columns]

In [178]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'progress', 'freq',
       'vendor', 'title', 'description', 'is_draft', 'is_use', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [179]:
df = df[['year', 'month', 'region', 'progress', 'freq', 'vendor', 'title', 'description', 'is_draft', 'is_use']]

In [180]:
df.columns = ['년', '월', '리전', '진행상태', '유형', '공급사', '제목', '내용', 'is_draft', 'is_use']

In [181]:
df.tail(100)

,년,월,리전,진행상태,유형,공급사,제목,내용,is_draft,is_use
716,2023,02,SG,Failed,Monthly,Arista,SG>Arista : 정기점검 미대상 (정기정검 계약 계획 없음),정기점검 미대상 (정기정검 계약 계획 없음),False,True
717,2022,11,EU,Failed,Monthly,Paloalto,유지보수 계약 내의 정기점검 부재,유지보수 계약 내의 정기점검 부재,False,True
718,2022,09,NA,Completed,Monthly,Netbackup,NA>Netbackup : (월별) 월별 NA_netbackup_2022_09.pdf,None,False,True
719,2022,04,EU,Completed,Quarterly,Arista,EU>Arista : (분기) 분기 점검 CCS_EU Arista(22년 2분기).ods,None,False,True
720,2022,11,EU,Completed,Monthly,WAF,EU>WAF : (월별) 현대오토에버_웹방화벽 분석 보고서 - 22년 11월.xlsx,None,False,True
...,...,...,...,...,...,...,...,...,...,...
811,2023,02,KR,Completed,Monthly,Netapp,KR>NetApp : (월별) 월별_netapp_KR_23년 2월 정기점검 레포트....,None,False,True
812,2022,12,NA,Completed,Monthly,Netbackup,NA>Netbackup : (월별) NA_netbackup_2022_12.pdf,None,False,True
813,2023,08,NA,Completed,Monthly,Netbackup,NA>Netbackup : (월별) NA_netbackup_2023_08.pdf,None,False,True
814,2022,02,NA,Completed,Quarterly,Arista,NA>Arista : (분기) 분기 점검 CCS_NA Arista(22년 1분기).pdf,None,False,True
815,2023,06,NA,Completed,Quarterly,HP,NA>HP : (분기) 분기점검_HP_북미 점검문서(23년2분기).xlsx (6월),None,False,True

In [182]:
# 월별추세용, 상세현황용
df_filtered = df[df['리전'].isin(regions)]
df_filtered_current = df[ df['리전'].isin(regions) & df['년'].isin([year]) & df['월'].isin([month]) ]

print("df", df)
print("dfdf",df_filtered)

# # Pivoting
# pivot, total = getPivotTable_regular(df, month, year)

df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
completed = len(df_completed)

df_incompleted = df_filtered[ df_filtered['진행상태'].isin(['Failed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
incompleted = len(df_incompleted)

df_completed_chart = df_filtered[ df_filtered['진행상태'].isin(['Completed'])]

df         년   월  리전       진행상태         유형            공급사  \
0    2024  05  RU     Failed    Monthly            A10
1    2024  05  EU  Completed    Monthly       Paloalto
2    2024  05  EU  Completed    Monthly  Cisco(Server)
3    2024  05  RU     Failed    Monthly           Dell
4    2024  05  EU     Failed    Monthly            A10
..    ...  ..  ..        ...        ...            ...
811  2023  02  KR  Completed    Monthly         Netapp
812  2022  12  NA  Completed    Monthly      Netbackup
813  2023  08  NA  Completed    Monthly      Netbackup
814  2022  02  NA  Completed  Quarterly         Arista
815  2023  06  NA  Completed  Quarterly             HP

                                                    제목  \
0                      RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
1     (월별) 월별_점검_eu101-PA-5250_(24년05월).docx월별_점검_e...
2                           24년5월_현대오토에버 TMS 정기점검 (5월)
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
4                   유지보수 계약 내의 정기점검 부재 (정기정검 계약 계획 없음)
..                                                 ...
811  KR>NetApp : (월별) 월별_netapp_KR_23년 2월 정기점검 레포트....
812       NA>Netbackup : (월별) NA_netbackup_2022_12.pdf
813      NA>Netbackup : (월별) NA_netbackup_2023_08.pdf
814  NA>Arista : (분기) 분기 점검 CCS_NA Arista(22년 1분기).pdf
815     NA>HP : (분기) 분기점검_HP_북미 점검문서(23년2분기).xlsx (6월)

                                                    내용  is_draft  is_use
0    <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
1                                                 None     False    True
2                                                 None     False    True
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
4                   유지보수 계약 내의 정기점검 부재 (정기정검 계약 계획 없음)     False    True
..                                                 ...       ...     ...
811                                               None     False    True
812                                               None     False    True
813                                               None     False    True
814                                               None     False    True
815                                               None     False    True

[816 rows x 10 columns]
dfdf         년   월  리전    진행상태         유형       공급사  \
0    2024  05  RU  Failed    Monthly       A10
3    2024  05  RU  Failed    Monthly      Dell
5    2024  05  RU  Failed    Monthly  Paloalto
21   2024  05  RU  Failed    Monthly    Netapp
26   2024  05  RU  Failed  Quarterly    Arista
..    ...  ..  ..     ...        ...       ...
772  2023  12  RU  Failed    Monthly       A10
784  2022  08  RU  Failed    Monthly       A10
786  2023  09  RU  Failed    Monthly      Dell
800  2023  06  RU  Failed    Monthly      Dell
803  2023  02  RU  Failed    Monthly  Paloalto

                                  제목  \
0    RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
3    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
5    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
21   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
26   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
..                               ...
772  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
784                         정기점검 미대상
786  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
800  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
803  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중

                                                    내용  is_draft  is_use
0    <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
5                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
21                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
26                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
..                                                 ...       ...     ...
772                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
784       RU A10 유지보수 계약 부재에 따라, 22년 7월 부터 정기점검 대상 제외됨     False    True
786                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
800                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
803                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True

[117 rows x 10 columns]

In [183]:
print(df_filtered)
print(df_filtered_current)
print(completed, incompleted)

        년   월  리전    진행상태         유형       공급사  \
0    2024  05  RU  Failed    Monthly       A10
3    2024  05  RU  Failed    Monthly      Dell
5    2024  05  RU  Failed    Monthly  Paloalto
21   2024  05  RU  Failed    Monthly    Netapp
26   2024  05  RU  Failed  Quarterly    Arista
..    ...  ..  ..     ...        ...       ...
772  2023  12  RU  Failed    Monthly       A10
784  2022  08  RU  Failed    Monthly       A10
786  2023  09  RU  Failed    Monthly      Dell
800  2023  06  RU  Failed    Monthly      Dell
803  2023  02  RU  Failed    Monthly  Paloalto

                                  제목  \
0    RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
3    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
5    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
21   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
26   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
..                               ...
772  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
784                         정기점검 미대상
786  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
800  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
803  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중

                                                    내용  is_draft  is_use
0    <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
5                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
21                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
26                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
..                                                 ...       ...     ...
772                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
784       RU A10 유지보수 계약 부재에 따라, 22년 7월 부터 정기점검 대상 제외됨     False    True
786                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
800                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
803                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True

[117 rows x 10 columns]
       년   월  리전    진행상태         유형       공급사  \
0   2024  05  RU  Failed    Monthly       A10
3   2024  05  RU  Failed    Monthly      Dell
5   2024  05  RU  Failed    Monthly  Paloalto
21  2024  05  RU  Failed    Monthly    Netapp
26  2024  05  RU  Failed  Quarterly    Arista

                                 제목  \
0   RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
3   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
5   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
21  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
26  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중

                                                   내용  is_draft  is_use
0   <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
3                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
5                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
21                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
26                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
0 5

In [184]:
# Chart - Pie 차트
t = completed + incompleted
if len(regions) > 1: # == 'All':
    
    # Data
    rowsc = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Completed']))]
    rowsi = df_filtered_current.loc[(df_filtered_current['진행상태'].isin(['Failed']))]

    document.add_heading('정기점검', level=1) 
    document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 미진행: {incompleted} 건)', style='List Bullet')
    if completed !=0 and incompleted !=0:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        chartc = getPieChart(sourcec)
        charti = getPieChart(sourcei)
        chartc.save(f'./charts/rcc_{y}_{m}_{d}_{v}_1.png')
        charti.save(f'./charts/rci_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=2)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}완료".format(''))
        run.add_picture(f'./charts/rcc_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
        cell = table.rows[0].cells[1]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_text("{0:^44}미진행".format(''))
        run.add_picture(f'./charts/rci_{y}_{m}_{d}_{v}_1.png', width=Inches(3.55))
    elif completed ==0:
        datai, pivoti, totali = getPivotTable_event(rowsi, month, regions)
        sourcei = pivoti
        charti = getPieChart(sourcei)
        charti.save(f'./charts/rci_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/rci_{y}_{m}_{d}_{v}_1.png')
    else:
        datac, pivotc, totalc = getPivotTable_event(rowsc, month, regions)
        sourcec = pivotc
        chartc = getPieChart(sourcec)
        chartc.save(f'./charts/rcc_{y}_{m}_{d}_{v}_1.png')
        table = document.add_table(rows=1, cols=1)
        # --- get the first cell of the first row ---
        cell = table.rows[0].cells[0]
        # --- by default a cell has one paragraph with zero runs ---
        paragraph = cell.paragraphs[0]
        # --- add a run in which to place the picture ---
        run = paragraph.add_run()
        # --- add the picture to that run ---
        run.add_picture(f'./charts/rcc_{y}_{m}_{d}_{v}_1.png')

else:
    document.add_heading('정기점검', level=1)
    if t == completed:
        if t == 0 : 
            document.add_paragraph(f'총 {t} 건', style='List Bullet')
        else:
            document.add_paragraph(f'총 {t} 건 (완료)', style='List Bullet')
    else :
        document.add_paragraph(f'총 {t} 건 (완료: {completed} 건 / 미진행: {incompleted} 건)', style='List Bullet')
    pass

# Chart - 라인 차트
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# df_completed_date_count = (df_filtered[(df_filtered['진행상태']=='완료')])
data = counter_3d_regular(df_filtered,ym2)
# chart = getLineChart_new(data)
# print("df_filtered", df_filtered)
# print("df_completed_date_count", df_completed_date_count)
chart = getLineChart_regular(data)

#chart = getLineChart2(df_filtered, month)
# data = counter_3d(df_completed_chart, month)
# chart = getLineChart(data)
chart.save(f'./charts/rc_{regions}_{y}_{m}_{d}_2.png')

        년   월  리전    진행상태         유형       공급사  \
0    2024  05  RU  Failed    Monthly       A10
3    2024  05  RU  Failed    Monthly      Dell
5    2024  05  RU  Failed    Monthly  Paloalto
21   2024  05  RU  Failed    Monthly    Netapp
26   2024  05  RU  Failed  Quarterly    Arista
..    ...  ..  ..     ...        ...       ...
772  2023  12  RU  Failed    Monthly       A10
784  2022  08  RU  Failed    Monthly       A10
786  2023  09  RU  Failed    Monthly      Dell
800  2023  06  RU  Failed    Monthly      Dell
803  2023  02  RU  Failed    Monthly  Paloalto

                                  제목  \
0    RU : 러시아 로컬벤더사의 정기점검 및 유지보수 확인중
3    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
5    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
21   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
26   RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
..                               ...
772  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
784                         정기점검 미대상
786  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
800  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중
803  RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중

                                                    내용  is_draft  is_use  \
0    <ul><li><strong>대상: A10, &nbsp;Netapp, Dell, P...     False    True
3                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
5                      RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
21                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
26                     RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
..                                                 ...       ...     ...
772                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
784       RU A10 유지보수 계약 부재에 따라, 22년 7월 부터 정기점검 대상 제외됨     False    True
786                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
800                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True
803                    RU : 러시아 로컬벤더사의 정기점검 담당자&절차 확인중     False    True

       Date
0    202405
3    202405
5    202405
21   202405
26   202405
..      ...
772  202312
784  202208
786  202309
800  202306
803  202302

[117 rows x 11 columns]
       Date    진행상태
0    202405  Failed
3    202405  Failed
5    202405  Failed
21   202405  Failed
26   202405  Failed
..      ...     ...
772  202312  Failed
784  202208  Failed
786  202309  Failed
800  202306  Failed
803  202302  Failed

[117 rows x 2 columns] <class 'pandas.core.frame.DataFrame'>
df_extract        Date
0    202405
3    202405
5    202405
21   202405
26   202405
..      ...
772  202312
784  202208
786  202309
800  202306
803  202302

[117 rows x 1 columns]
df_index ['202201', '202202', '202203', '202204', '202205', '202206', '202207', '202208', '202209', '202210', '202211', '202212', '202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405']
202405
ym_index 28

WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.
WARN Invalid field type "nominal" for aggregate: "count", using "quantitative" instead.

In [185]:
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/rc_{regions}_{y}_{m}_{d}_2.png')   

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)


# Document
document.add_paragraph('상세 현황', style='List Bullet')
if df_filtered[df_filtered['월']==month].empty :
    pass
else:
    if len(regions) > 1: # == 'All':
        addTable_insp_all(df_filtered_current, month)
    else:
        addTable_insp(df_filtered_current, month)

document.add_page_break()

In [186]:
document.save('demo.docx')

## (신규포탈)데이터베이스 라이센스 관리(완료)

In [187]:
data_endpoint = 'http://10.11.66.85:8080/assets/licenses/list'
# data_endpoint = 'http://localhost:8000/licenses/list/all'
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "vendor": [],
    "license_type": [],
    "is_draft": False,
    "is_use": True
    # "report_type": 0
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [188]:
df = pd.DataFrame(result['data'])

In [189]:
print(df)

          id  year month day region az tenant customer  vendor  license_num  \
0      13789  2024    05  01     SG  1    PRD     None    MCCS  MSC2301-049
1      14037  2024    05  01     KR  2    PRD     None  Tibero          nan
2      14036  2024    05  01     KR  2    PRD     None  Tibero          nan
3      14035  2024    05  01     KR  2    PRD     None  Tibero          nan
4      14034  2024    05  01     KR  1    PRD     None  Tibero          nan
...      ...   ...   ...  ..    ... ..    ...      ...     ...          ...
10632   5392  2022    10  01     KR  1    PRD     None    MCCS  MSC2011-055
10633   5393  2022    10  01     KR  1    PRD     None    MCCS  MSC2011-055
10634   5394  2022    10  01     KR  1    PRD     None    MCCS  MSC2011-055
10635   5395  2022    10  01     KR  1    PRD     None    MCCS  MSC2011-055
10636   5396  2022    10  01     KR  1    PRD     None    MCCS  MSC2011-055

       ...                                      instance_name comment  \
0      ...  ccsauccspgpushdbp01-prd-r0107-au.ap-southeast....    None
1      ...        ccskrdkc2kpgldbp0101.ap-northeast-2.prd.h53    None
2      ...          ccskrdkc2hpgldbp02.ap-northeast-2.prd.h53    None
3      ...          ccskrdkc2hpgldbp01.ap-northeast-2.prd.h53    None
4      ...                                 ccskricpsscmsdbp02    None
...    ...                                                ...     ...
10632  ...                                      ccskrlmsdbp02    None
10633  ...                                     ccskrannodbp01    None
10634  ...                                     ccskrannodbp02    None
10635  ...                                     ccskrlocadbp01    None
10636  ...                                     ccskrlocadbp02    None

      occurred_at resolved_at is_draft is_use  reviewer  updater  \
0            None        None    False   True      None      채한길
1            None        None    False   True      None      채한길
2            None        None    False   True      None      채한길
3            None        None    False   True      None      채한길
4            None        None    False   True      None      채한길
...           ...         ...      ...    ...       ...      ...
10632        None        None    False   True      None    test2
10633        None        None    False   True      None    test2
10634        None        None    False   True      None    test2
10635        None        None    False   True      None    test2
10636        None        None    False   True      None    test2

            created_at_str       updated_at_str
0      2024-06-03 16:23:12  2024-06-03 16:23:12
1      2024-06-03 16:23:12  2024-06-03 16:23:12
2      2024-06-03 16:23:12  2024-06-03 16:23:12
3      2024-06-03 16:23:12  2024-06-03 16:23:12
4      2024-06-03 16:23:12  2024-06-03 16:23:12
...                    ...                  ...
10632  2024-01-04 18:12:32  2024-01-04 18:12:32
10633  2024-01-04 18:12:32  2024-01-04 18:12:32
10634  2024-01-04 18:12:32  2024-01-04 18:12:32
10635  2024-01-04 18:12:32  2024-01-04 18:12:32
10636  2024-01-04 18:12:32  2024-01-04 18:12:32

[10637 rows x 22 columns]

In [190]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'vendor', 'license_num', 'expired_at', 'license_type', 'instance_name',
       'comment', 'occurred_at', 'resolved_at', 'is_draft', 'is_use',
       'reviewer', 'updater', 'created_at_str', 'updated_at_str'],
      dtype='object')

In [191]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'vendor', 'license_num',
         'license_type', 'instance_name', 'comment', 'expired_at', 
         'occurred_at', 'resolved_at', 'is_draft', 'is_use']]

In [192]:
df.columns = ['년', '월', '리전', 'AZ', '테넌트', '공급사', 'license_num',
              '유형', 'instance_name', '비고', 'expired_at',
              'occurred_at', 'resolved_at', 'is_draft', 'is_use']

In [193]:
df.head()

,년,월,리전,AZ,테넌트,공급사,license_num,유형,instance_name,비고,expired_at,occurred_at,resolved_at,is_draft,is_use
0,2024,05,SG,1,PRD,MCCS,MSC2301-049,LICENSED,ccsauccspgpushdbp01-prd-r0107-au.ap-southeast....,None,None,None,None,False,True
1,2024,05,KR,2,PRD,Tibero,nan,LICENSED,ccskrdkc2kpgldbp0101.ap-northeast-2.prd.h53,None,None,None,None,False,True
2,2024,05,KR,2,PRD,Tibero,nan,LICENSED,ccskrdkc2hpgldbp02.ap-northeast-2.prd.h53,None,None,None,None,False,True
3,2024,05,KR,2,PRD,Tibero,nan,LICENSED,ccskrdkc2hpgldbp01.ap-northeast-2.prd.h53,None,None,None,None,False,True
4,2024,05,KR,1,PRD,Tibero,nan,LICENSED,ccskricpsscmsdbp02,None,None,None,None,False,True

In [194]:
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
# df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
#temp_license = df[df['리전'].apply(lambda x: True if re.search(regex, x) else False) & (df['테넌트']== 'PRD') & (df['월간']=='O') & (df['라이선스']== '임시')]
print(df_filtered)
# Pivoting
# pivot, total = getPivotTable(df, month, year)

df_origin = df_filtered[df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) & df_filtered['유형'].isin(['LICENSED'])]
origin = len(df_origin)

df_temp = df_filtered[df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) & df_filtered['유형'].isin(['TEMPORARY'])]
temp = len(df_temp)
# print(total)
# df
# df_completed = df_filtered[ (df_filtered['년']==y) & (df_filtered['월']==month) & (df_filtered['진행상태']=='완료') ]
# completed = len(df_completed)

# df_incompleted = df_filtered[ (df_filtered['년']==y) & (df_filtered['월']==month) & (df_filtered['진행상태']!='완료') ]
# incompleted = len(df_incompleted)

          년   월  리전 AZ  테넌트   공급사  license_num        유형 instance_name    비고  \
290    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
291    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
292    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
293    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
793    2024  04  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
...     ...  ..  .. ..  ...   ...          ...       ...           ...   ...
10325  2022  09  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
10591  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
10592  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
10593  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
10594  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None

      expired_at occurred_at resolved_at  is_draft  is_use
290         None        None        None     False    True
291         None        None        None     False    True
292         None        None        None     False    True
293         None        None        None     False    True
793         None        None        None     False    True
...          ...         ...         ...       ...     ...
10325       None        None        None     False    True
10591       None        None        None     False    True
10592       None        None        None     False    True
10593       None        None        None     False    True
10594       None        None        None     False    True

[116 rows x 15 columns]

In [195]:
print(origin, temp)

4 0

In [196]:
# df_filtered[(df_filtered['월']==month)& (df_filtered['유형']== '임시')]
df_filtered[df_filtered['년'].isin([year]) & df_filtered['월'].isin([month])]
print(df_filtered)

print(len(df_temp))

          년   월  리전 AZ  테넌트   공급사  license_num        유형 instance_name    비고  \
290    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
291    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
292    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
293    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
793    2024  04  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
...     ...  ..  .. ..  ...   ...          ...       ...           ...   ...
10325  2022  09  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
10591  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
10592  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
10593  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
10594  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None

      expired_at occurred_at resolved_at  is_draft  is_use
290         None        None        None     False    True
291         None        None        None     False    True
292         None        None        None     False    True
293         None        None        None     False    True
793         None        None        None     False    True
...          ...         ...         ...       ...     ...
10325       None        None        None     False    True
10591       None        None        None     False    True
10592       None        None        None     False    True
10593       None        None        None     False    True
10594       None        None        None     False    True

[116 rows x 15 columns]
0

In [197]:
df_filtered['유형'] = df_filtered['유형'].astype(str)
a=df_filtered.groupby('유형')['월'].count().reset_index()
a.rename(columns = {'월':'합계'},inplace=True)
print(a)

         유형   합계
0  LICENSED  116

In [198]:
if len(regions) > 1: # == 'All':
    # Data
    # rows = df_filtered.loc[(df_filtered['년']==y) & (df_filtered['월']==month)]
    # rows = df_filtered_current
    rows = df_filtered.loc[df_filtered['년'].isin([year]) & df_filtered['월'].isin([month])]
    print(set(rows['리전']))
    
    data, pivot, total = getPivotTable_event_db_license_2(rows, month, regions)
    source = pivot
    print(source)
    # Chart
    # if temp == 0:
    chart = getPieChart(source)
    # else:
    #     source = flatten_2d(data)
    #     chart = getStackedHBarChart(source)
        
    chart.save(f'./charts/db_license_{regions}_{y}_{m}_{d}_1.png')
else:
    rows = df_filtered.loc[ df_filtered['년'].isin([year]) & df_filtered['월'].isin([month])]
    data, pivot, total = getPivotTable_event_db_license(rows, month, regions)
    pass


# source = pivot
# source = flatten_d_db_license(data)

In [199]:
df_filtered

,년,월,리전,AZ,테넌트,공급사,license_num,유형,instance_name,비고,expired_at,occurred_at,resolved_at,is_draft,is_use
290,2024,05,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp02,None,None,None,None,False,True
291,2024,05,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp01,None,None,None,None,False,True
292,2024,05,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsrudbp02,None,None,None,None,False,True
293,2024,05,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsrudbp01,None,None,None,None,False,True
793,2024,04,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp02,None,None,None,None,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10325,2022,09,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp02,None,None,None,None,False,True
10591,2022,10,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsrudbp01,None,None,None,None,False,True
10592,2022,10,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsrudbp02,None,None,None,None,False,True
10593,2022,10,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp01,None,None,None,None,False,True
10594,2022,10,RU,1,PRD,MCCS,MSC2011-026,LICENSED,ccsprudbp02,None,None,None,None,False,True

In [200]:
# Chart - 라인 차트
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
data = counter_3d_license(df_filtered,ym2)
chart = getStacked_1_11_VBarChart1(data)
chart.save(f'./charts/db_license_{regions}_{y}_{m}_{d}_2.png')

          년   월  리전 AZ  테넌트   공급사  license_num        유형 instance_name    비고  \
290    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
291    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
292    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
293    2024  05  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
793    2024  04  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
...     ...  ..  .. ..  ...   ...          ...       ...           ...   ...
10325  2022  09  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None
10591  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp01  None
10592  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED    ccsrudbp02  None
10593  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp01  None
10594  2022  10  RU  1  PRD  MCCS  MSC2011-026  LICENSED   ccsprudbp02  None

      expired_at occurred_at resolved_at  is_draft  is_use    Date
290         None        None        None     False    True  202405
291         None        None        None     False    True  202405
292         None        None        None     False    True  202405
293         None        None        None     False    True  202405
793         None        None        None     False    True  202404
...          ...         ...         ...       ...     ...     ...
10325       None        None        None     False    True  202209
10591       None        None        None     False    True  202210
10592       None        None        None     False    True  202210
10593       None        None        None     False    True  202210
10594       None        None        None     False    True  202210

[116 rows x 16 columns]
         Date        유형   공급사
290    202405  LICENSED  MCCS
291    202405  LICENSED  MCCS
292    202405  LICENSED  MCCS
293    202405  LICENSED  MCCS
793    202404  LICENSED  MCCS
...       ...       ...   ...
10325  202209  LICENSED  MCCS
10591  202210  LICENSED  MCCS
10592  202210  LICENSED  MCCS
10593  202210  LICENSED  MCCS
10594  202210  LICENSED  MCCS

[116 rows x 3 columns] <class 'pandas.core.frame.DataFrame'>
df_extract          Date
290    202405
291    202405
292    202405
293    202405
793    202404
...       ...
10325  202209
10591  202210
10592  202210
10593  202210
10594  202210

[116 rows x 1 columns]
df_index ['202201', '202202', '202203', '202204', '202205', '202206', '202207', '202208', '202209', '202210', '202211', '202212', '202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405']
202405
ym_index 28

In [201]:
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
# data = counter_3d(df_filtered)
chart = getStacked_1_11_VBarChart2(data)
chart.save(f'./charts/db_license_{regions}_{y}_{m}_{d}_3.png')

In [202]:
# Document
document.add_heading('데이터베이스 라이선스 관리', level=1)
t = origin + temp
if t == origin :
    document.add_paragraph(f'총 {t} 건 (정식 라이선스)', style='List Bullet')
else :
    document.add_paragraph(f'총 {t} 건 (정식 라이선스: {origin} 건 / 임시라이선스: {temp} 건)', style='List Bullet')

if len(regions) > 1: # == 'All':
    document.add_picture(f'./charts/db_license_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

# Document
if temp != 0 :
    document.add_paragraph('임시 라이선스 사용 내역', style='List Bullet')
    
if df_temp.empty :
    pass
else:
    addTable_DB_license(df_temp, month)

# addTable(df_filtered, regex, month)
document.add_paragraph('라이선스 유형별 라이선스 수', style='List Bullet')
document.add_picture(f'./charts/db_license_{regions}_{y}_{m}_{d}_2.png')

p = document.add_paragraph('')
run = p.add_run()
run.add_break(WD_BREAK.LINE)

document.add_paragraph('데이터베이스 공급사별 라이선스 수', style='List Bullet')
document.add_picture(f'./charts/db_license_{regions}_{y}_{m}_{d}_3.png')
# document.add_paragraph('월별 추세', style='List Bullet')
# document.add_picture(f'./charts/db_license_{region}_{y}_{m}_{d}_3.png')
# document.add_page_break()

In [203]:
document.save('demo.docx')

## Save Document

In [204]:
# m2 = today.month

In [205]:
document.save(f'월간보고서_{regions}_contents_{y}_{m}_{d}.docx')

## 보고서 표지 (커버 쉬트)

In [206]:
# Cover Page
from docxtpl import DocxTemplate

# DRM 방지(cover-page-template.docx)
file_path=os.path.abspath("")
srcpath = findfile("cover-page-template.docx.org", file_path)
dir, file = os.path.split(srcpath)
shutil.copy2(srcpath, dir+"\cover-page-template.docx")

doc = DocxTemplate("cover-page-template.docx")
# month_split = month.strip("월")

context = { 
    #'Service' : "HMC CCS Infra 운영/관리",      
    'Title' : "Monthly Report",    
    'Region' : regions,        
    'Year' : "2024",
    'Month' : f"{month}",
    'Department' : "클라우드운영센터"
}
doc.render(context)

doc.save(f'월간보고서_cover_{regions}.docx')

In [207]:
from docx import Document
from docxcompose.composer import Composer

composer = None
doc1 = Document(f'월간보고서_cover_{regions}.docx')
composer = Composer(doc1)

doc2 = Document(f'월간보고서_{regions}_contents_{y}_{m}_{d}.docx')
composer.append(doc2)

composer.save(f'월간보고서_{regions}_{y}_{m}_{d}.docx')
# composer.save(f'{year}_{month}_MonthlyReport_{region}.docx)

## (신규포탈)자산관리(VM)(기존)

In [208]:
data_endpoint = 'http://10.11.66.85:8080/assets/instances/aggregation/list' 
# Request header
request_header = {
    "skip": 0,
    "limit": 100000,
    "from_YYYYMMDDHH24MI": "202401010000",
    "to_YYYYMMDDHH24MI": format_now,
    "region": [],
    "az": [],
    "tenant": [],
    "customer": [],
    "progress": [],
    "is_draft": False,
    "is_use": True
}
# Call the function
result = await fetch_data(access_token, data_endpoint, request_header)

In [209]:
df = pd.DataFrame(result['data'])

In [210]:
print(df)

        id  year month day region az   tenant customer type     status  count  \
0     1465  2024    06  11     CN  1  NEW-STG     None   VM  COMPLETED    228
1     1484  2024    06  11     SG  1      STG     None   VM  COMPLETED    728
2     1483  2024    06  11     SG  1      PRD     None   VM  COMPLETED    993
3     1482  2024    06  11     RU  1      STG     None   VM  COMPLETED    119
4     1481  2024    06  11     RU  1      PRD     None   VM  COMPLETED    162
...    ...   ...   ...  ..    ... ..      ...      ...  ...        ...    ...
1479   617  2024    03  01     KR  1      PRD      CCS   VM  COMPLETED   1708
1480   616  2024    02  01     NA  2      STG      CCS   VM  COMPLETED    607
1481   615  2024    02  01     NA  2      PRD      CCS   VM  COMPLETED    907
1482   614  2024    02  01     SG  1      DEV      CCS   VM  COMPLETED      0
1483   613  2024    02  01     SG  1      STG      CCS   VM  COMPLETED    706

      is_draft  is_use updater       created_at_str       updated_at_str
0        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
1        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
2        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
3        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
4        False    True   admin  2024-06-11 12:00:06  2024-06-11 12:00:06
...        ...     ...     ...                  ...                  ...
1479     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1480     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1481     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1482     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53
1483     False    True   test2  2024-05-03 15:16:53  2024-05-03 15:16:53

[1484 rows x 16 columns]

In [211]:
df.columns

Index(['id', 'year', 'month', 'day', 'region', 'az', 'tenant', 'customer',
       'type', 'status', 'count', 'is_draft', 'is_use', 'updater',
       'created_at_str', 'updated_at_str'],
      dtype='object')

In [212]:
df = df[['year', 'month', 'region', 'az', 'tenant', 'type', 'status', 'count', 'is_draft', 'is_use']]

In [213]:
# description
df.columns = [ '년', '월', '리전', 'AZ', '테넌트', '유형', '진행상태', 'count', 'is_draft', 'is_use']

In [214]:
df.head()

      년   월  리전 AZ      테넌트  유형       진행상태  count  is_draft  is_use
0  2024  06  CN  1  NEW-STG  VM  COMPLETED    228     False    True
1  2024  06  SG  1      STG  VM  COMPLETED    728     False    True
2  2024  06  SG  1      PRD  VM  COMPLETED    993     False    True
3  2024  06  RU  1      STG  VM  COMPLETED    119     False    True
4  2024  06  RU  1      PRD  VM  COMPLETED    162     False    True

In [215]:
# 월별추세용, 상세현황용
df_filtered = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD'])]
df_filtered_current = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]

# Pivoting
# pivot, total = getPivotTable(df, month, year)

# df_completed = df_filtered[ df_filtered['진행상태'].isin(['Completed']) & df_filtered['년'].isin([year]) & df_filtered['월'].isin([month]) ]
# completed = len(df_completed)

# Pivoting
pivot, total = getPivotTable(df_filtered_current)

df_ = df[ df['리전'].isin(regions) & df['테넌트'].isin(['PRD']) & df['년'].isin([year]) & df['월'].isin([month]) ]
total_instance = df_['count'].sum()

In [216]:
print(int(total_instance))

5022

In [217]:
# Chart - Pie 차트
if len(regions) > 1: # == 'All':
    # Data
    # rows = df_filtered.loc[(df_filtered['월']==month) & (df_filtered['년']==y)]
    # data, pivot, total = getPivotTable_event(rows, month, region_list)
    source = pivot
       
    # Chart
    chart = getPieChart(source)
    chart.save(f'./charts/vm_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

In [218]:
df_filtered

         년   월  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 10 columns]

In [219]:
# Chart - 라인 차트
# df_filtered['Date'] = pd.to_datetime(df_filtered['년'].astype(str) + df_filtered['월'].astype(str), format='%Y%m').dt.strftime('%Y%m')
print(ym2)
print("xxx",df_filtered)
data = counter_3d_vm(df_filtered,ym2)
print("data",data)
chart = getLineChart2s(data)
chart.save(f'./charts/vm_{regions}_{y}_{m}_{d}_2.png')

202405
xxx          년   월  리전 AZ  테넌트  유형       진행상태  count  is_draft  is_use
4     2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
24    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
46    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
64    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
86    2024  06  RU  1  PRD  VM  COMPLETED    162     False    True
...    ...  ..  .. ..  ...  ..        ...    ...       ...     ...
1372  2022  03  RU  1  PRD  VM  COMPLETED     97     False    True
1391  2022  02  RU  1  PRD  VM  COMPLETED     96     False    True
1410  2022  01  RU  1  PRD  VM  COMPLETED    108     False    True
1429  2024  04  RU  1  PRD  VM  COMPLETED     85     False    True
1459  2024  03  RU  1  PRD  VM  COMPLETED     85     False    True

[70 rows x 10 columns]
       년   월  count
0   2022  01    108
1   2022  02     96
2   2022  03     97
3   2022  04     96
4   2022  05     96
5   2022  06     96
6   2022  07     86
7   2022  08     86
8   2022  09     78
9   2022  10     78
10  2022  11     78
11  2022  12     79
12  2023  01     79
13  2023  02     79
14  2023  03     79
15  2023  04     79
16  2023  05     82
17  2023  06     83
18  2023  07     84
19  2023  08     84
20  2023  09     84
21  2023  10     84
22  2023  11     84
23  2023  12     84
24  2024  01     84
25  2024  02     84
26  2024  03     85
27  2024  04     85
28  2024  05   5022
29  2024  06   1782
       년   월  count    Date
0   2022  01    108  202201
1   2022  02     96  202202
2   2022  03     97  202203
3   2022  04     96  202204
4   2022  05     96  202205
5   2022  06     96  202206
6   2022  07     86  202207
7   2022  08     86  202208
8   2022  09     78  202209
9   2022  10     78  202210
10  2022  11     78  202211
11  2022  12     79  202212
12  2023  01     79  202301
13  2023  02     79  202302
14  2023  03     79  202303
15  2023  04     79  202304
16  2023  05     82  202305
17  2023  06     83  202306
18  2023  07     84  202307
19  2023  08     84  202308
20  2023  09     84  202309
21  2023  10     84  202310
22  2023  11     84  202311
23  2023  12     84  202312
24  2024  01     84  202401
25  2024  02     84  202402
26  2024  03     85  202403
27  2024  04     85  202404
28  2024  05   5022  202405
29  2024  06   1782  202406
      Date  count
0   202201    108
1   202202     96
2   202203     97
3   202204     96
4   202205     96
5   202206     96
6   202207     86
7   202208     86
8   202209     78
9   202210     78
10  202211     78
11  202212     79
12  202301     79
13  202302     79
14  202303     79
15  202304     79
16  202305     82
17  202306     83
18  202307     84
19  202308     84
20  202309     84
21  202310     84
22  202311     84
23  202312     84
24  202401     84
25  202402     84
26  202403     85
27  202404     85
28  202405   5022
29  202406   1782 <class 'pandas.core.frame.DataFrame'>
df_extract       Date
0   202201
1   202202
2   202203
3   202204
4   202205
5   202206
6   202207
7   202208
8   202209
9   202210
10  202211
11  202212
12  202301
13  202302
14  202303
15  202304
16  202305
17  202306
18  202307
19  202308
20  202309
21  202310
22  202311
23  202312
24  202401
25  202402
26  202403
27  202404
28  202405
29  202406
df_index ['202201', '202202', '202203', '202204', '202205', '202206', '202207', '202208', '202209', '202210', '202211', '202212', '202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405', '202406']
202405
ym_index 28
data       Date  count
16  202305     82
17  202306     83
18  202307     84
19  202308     84
20  202309     84
21  202310     84
22  202311     84
23  202312     84
24  202401     84
25  202402     84
26  202403     85
27  202404     85
28  202405   5022

In [220]:
# Document
# document.add_paragraph('자산 관리(vm)', style='List Number')
document.add_heading('자산 관리(vm)', level=1) 
document.add_paragraph(f'총 {int(total_instance)}인스턴스 (운영계)', style='List Bullet')

if len(regions) > 1: # == 'All':
    document.add_picture(f'./charts/vm_{regions}_{y}_{m}_{d}_1.png')
else:
    pass

# Document
# addTable(df_filtered, regex, month)
document.add_paragraph(f'월별 추세', style='List Bullet')
document.add_picture(f'./charts/vm_{regions}_{y}_{m}_{d}_2.png')
document.add_page_break()

In [221]:
document.save('demo.docx')